// Code generated by sdk/pandorest; DO NOT EDIT.

package tmdb

// AuthenticationDeleteSessionResponse is an object the document declares inline.
type AuthenticationDeleteSessionResponse struct {
	Success *bool `json:"success,omitempty"`
}
