// Code generated by sdk/pandorest; DO NOT EDIT.

package tmdb

// MovieWatchProvidersResponseResultsCA is an object the document declares inline.
type MovieWatchProvidersResponseResultsCA struct {
	Buy      []MovieWatchProvidersResponseResultsCABuy      `json:"buy,omitzero"`
	Flatrate []MovieWatchProvidersResponseResultsCAFlatrate `json:"flatrate,omitzero"`
	Link     string                                         `json:"link,omitempty"`
	Rent     []MovieWatchProvidersResponseResultsCARent     `json:"rent,omitzero"`
}
