// Code generated by sdk/pandorest; DO NOT EDIT.

package tmdb

// MovieWatchProvidersResponseResultsMY is an object the document declares inline.
type MovieWatchProvidersResponseResultsMY struct {
	Flatrate []MovieWatchProvidersResponseResultsMYFlatrate `json:"flatrate,omitzero"`
	Link     string                                         `json:"link,omitempty"`
}
