// Code generated by sdk/pandorest; DO NOT EDIT.

package tmdb

// MovieWatchProvidersResponseResultsTW is an object the document declares inline.
type MovieWatchProvidersResponseResultsTW struct {
	Flatrate []MovieWatchProvidersResponseResultsTWFlatrate `json:"flatrate,omitzero"`
	Link     string                                         `json:"link,omitempty"`
}
