// Code generated by sdk/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesWatchProvidersResponseResultsBG is an object the document declares inline.
type TvSeriesWatchProvidersResponseResultsBG struct {
	Flatrate []TvSeriesWatchProvidersResponseResultsBGFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
