// Code generated by sdk/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesWatchProvidersResponseResultsBA is an object the document declares inline.
type TvSeriesWatchProvidersResponseResultsBA struct {
	Flatrate []TvSeriesWatchProvidersResponseResultsBAFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
