// Code generated by sdk/pandorest; DO NOT EDIT.

package tmdb

// TvSeasonWatchProvidersResponseResultsAG is an object the document declares inline.
type TvSeasonWatchProvidersResponseResultsAG struct {
	Flatrate []TvSeasonWatchProvidersResponseResultsAGFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
