// Code generated by sdk/pandorest; DO NOT EDIT.

package tmdb

// TvSeasonWatchProvidersResponseResultsPH is an object the document declares inline.
type TvSeasonWatchProvidersResponseResultsPH struct {
	Flatrate []TvSeasonWatchProvidersResponseResultsPHFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
