// Code generated by sdk/pandorest; DO NOT EDIT.

package tmdb

// TvSeasonWatchProvidersResponseResultsIT is an object the document declares inline.
type TvSeasonWatchProvidersResponseResultsIT struct {
	Buy      []TvSeasonWatchProvidersResponseResultsITBuy      `json:"buy,omitzero"`
	Flatrate []TvSeasonWatchProvidersResponseResultsITFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
