// Code generated by sdk/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesAddRatingRequest is an object the document declares inline.
type TvSeriesAddRatingRequest struct {
	Value float64 `json:"value,omitempty"`
}
