// Code generated by sdk/pandorest; DO NOT EDIT.

package tmdb

// TvSeasonWatchProvidersResponseResultsHK is an object the document declares inline.
type TvSeasonWatchProvidersResponseResultsHK struct {
	Flatrate []TvSeasonWatchProvidersResponseResultsHKFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
