// Code generated by sdk/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesEpisodeGroupsResponse is an object the document declares inline.
type TvSeriesEpisodeGroupsResponse struct {
	Id      int                                    `json:"id,omitempty"`
	Results []TvSeriesEpisodeGroupsResponseResults `json:"results,omitzero"`
}
