// Code generated by sdk/pandorest; DO NOT EDIT.

package tmdb

// TvSeasonWatchProvidersResponseResultsMG is an object the document declares inline.
type TvSeasonWatchProvidersResponseResultsMG struct {
	Flatrate []TvSeasonWatchProvidersResponseResultsMGFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
