// Code generated by sdk/pandorest; DO NOT EDIT.

package tmdb

// WatchProvidersAvailableRegionsResponse is an object the document declares inline.
type WatchProvidersAvailableRegionsResponse struct {
	Results []WatchProvidersAvailableRegionsResponseResults `json:"results,omitzero"`
}
