// Code generated by sdk/pandorest; DO NOT EDIT.

package emby

// MBBackupApiRestoreOptions is the "MBBackup.Api.RestoreOptions" schema.
type MBBackupApiRestoreOptions struct {
	RestoreServerId *bool  `json:"RestoreServerId,omitempty"`
	UseFiles        string `json:"UseFiles,omitempty"`
}
