// Code generated by sdk/pandorest; DO NOT EDIT.

package emby

// BrandingBrandingOptions is the "Branding.BrandingOptions" schema.
type BrandingBrandingOptions struct {
	CustomCss       string `json:"CustomCss,omitempty"`
	LoginDisclaimer string `json:"LoginDisclaimer,omitempty"`
}
