// Code generated by sdk/pandorest; DO NOT EDIT.

package emby

// UserLibraryDeleteHomeSections is the "UserLibrary.DeleteHomeSections" schema.
type UserLibraryDeleteHomeSections struct {
	Ids []string `json:"Ids,omitzero"`
}
