// Package emby is a typed client for Emby Server REST API 4.10.0.40, generated by pandorest
// from the definitions in api-defs/emby-4.10.0.40, which were imported from api-defs/emby-openapi-4.10.0.40.json.
//
// # Layout
//
// Every operation of the API is a method on Client, in a file of its own named
// <tag>_method_<operation>.go. Each model is in <tag>_model_<model>.go and each
// tag's enums in <tag>_constants.go; a model or enum more than one tag uses is
// under common_. The requests go through the hand-written base client,
// github.com/katbyte/pandorest/client.
//
// # Calls
//
// A method takes a context, then the path parameters in path order, then the
// request body (input: the model for a JSON body, or an io.Reader and its
// content type for raw bytes), then, when the operation has query or header
// parameters, a <Name>OperationOptions. Unset options are not sent: a
// boolean or a number is a pointer, sent when set (so 0 and false can be
// asked for), an empty string or list is skipped, and a list is sent
// comma-joined or as one parameter for each element, as the document says.
//
// It returns a <Name>OperationResponse holding HttpResponse and, when the
// operation answers JSON, Model. HttpResponse is set whenever the server
// answered, including alongside an error, and its body can be read again. An
// operation that answers a file leaves the body unread in
// HttpResponse.Body for the caller to read and close. A status the operation
// does not document is an error, and client.StatusCode reads the status from
// it.
//
// A list operation, one whose options page with StartIndex and Limit, also has a
// <Name>Complete method that pages through every result.
//
// Dates are strings: the servers send RFC 3339 with seven fractional digits,
// sometimes with no zone.
//
// # Workarounds
//
// The importer fixed these bugs in the document before generating from it:
//
//   - emby-undeclared-responses
//   - emby-undeclared-path-parameters
//   - emby-no-content-status
//   - emby-playlist-create-user-id
//   - emby-library-available-options-query
//   - emby-next-up-legacy
//   - emby-playstate-seek-query
//   - emby-library-delete-id
//   - emby-comma-separated-arrays
//   - emby-null-result-no-content
//   - emby-openapi-documents
//   - emby-recording-folders-query-result
//   - emby-parent-path-text
//   - emby-codec-display-text
//   - emby-property-condition-value
//   - emby-undeclared-query
//   - emby-tone-map-options
package emby
