// Code generated by sdk/pandorest; DO NOT EDIT.

package emby

// BaseRefreshRequest is the "BaseRefreshRequest" schema.
type BaseRefreshRequest struct {
	ReplaceThumbnailImages *bool `json:"ReplaceThumbnailImages,omitempty"`
}
