// Code generated by sdk/pandorest; DO NOT EDIT.

package emby

// SyncDataResponse is the "SyncDataResponse" schema.
type SyncDataResponse struct {
	ItemIdsToRemove []string `json:"ItemIdsToRemove,omitzero"`
}
