// Code generated by sdk/pandorest; DO NOT EDIT.

package emby

// QueryResultUserDto is the "QueryResult_UserDto" schema.
type QueryResultUserDto struct {
	Items            []UserDto `json:"Items,omitzero"`
	TotalRecordCount int       `json:"TotalRecordCount,omitempty"`
}
