// Code generated by sdk/pandorest; DO NOT EDIT.

package emby

// CopyData is the "CopyData" schema.
type CopyData struct {
	CopyOptions []string `json:"CopyOptions,omitzero"`
	ToUserIds   []string `json:"ToUserIds,omitzero"`
	UserId      string   `json:"UserId,omitempty"`
}
