// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"io"
	"net/http"
	"testing"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

func TestOperationGetAudioByIdByStreamFileName(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "audio/mpeg", "file bytes")
	result, err := c.GetAudioByIdByStreamFileName(t.Context(), "p/id", "p/streamFileName", GetAudioByIdByStreamFileNameOperationOptions{
		DeviceProfileId:      "v-DeviceProfileId",
		DeviceId:             "v-DeviceId",
		Container:            "v-Container",
		AudioCodec:           "v-AudioCodec",
		EnableAutoStreamCopy: new(true),
		AudioSampleRate:      new(7),
		AudioBitRate:         new(7),
		AudioChannels:        new(7),
		MaxAudioChannels:     new(7),
		Static:               new(true),
		CopyTimestamps:       new(true),
		StartTimeTicks:       new(int64(7)),
		Width:                new(7),
		Height:               new(7),
		MaxWidth:             new(7),
		MaxHeight:            new(7),
		VideoBitRate:         new(7),
		SubtitleStreamIndex:  new(7),
		SubtitleMethod:       SubtitleDeliveryMethodEncode,
		MaxVideoBitDepth:     new(7),
		VideoCodec:           "v-VideoCodec",
		AudioStreamIndex:     new(7),
		VideoStreamIndex:     new(7),
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/Audio/p%2Fid/p%2FstreamFileName")
	expectQuery(t, r, "DeviceProfileId", "v-DeviceProfileId")
	expectQuery(t, r, "DeviceId", "v-DeviceId")
	expectQuery(t, r, "Container", "v-Container")
	expectQuery(t, r, "AudioCodec", "v-AudioCodec")
	expectQuery(t, r, "EnableAutoStreamCopy", "true")
	expectQuery(t, r, "AudioSampleRate", "7")
	expectQuery(t, r, "AudioBitRate", "7")
	expectQuery(t, r, "AudioChannels", "7")
	expectQuery(t, r, "MaxAudioChannels", "7")
	expectQuery(t, r, "Static", "true")
	expectQuery(t, r, "CopyTimestamps", "true")
	expectQuery(t, r, "StartTimeTicks", "7")
	expectQuery(t, r, "Width", "7")
	expectQuery(t, r, "Height", "7")
	expectQuery(t, r, "MaxWidth", "7")
	expectQuery(t, r, "MaxHeight", "7")
	expectQuery(t, r, "VideoBitRate", "7")
	expectQuery(t, r, "SubtitleStreamIndex", "7")
	expectQuery(t, r, "SubtitleMethod", "Encode")
	expectQuery(t, r, "MaxVideoBitDepth", "7")
	expectQuery(t, r, "VideoCodec", "v-VideoCodec")
	expectQuery(t, r, "AudioStreamIndex", "7")
	expectQuery(t, r, "VideoStreamIndex", "7")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	streamed, _ := io.ReadAll(result.HttpResponse.Body)
	_ = result.HttpResponse.Body.Close()
	if string(streamed) != "file bytes" {
		t.Errorf("streamed body = %q", streamed)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.GetAudioByIdByStreamFileName(t.Context(), "p/id", "p/streamFileName", GetAudioByIdByStreamFileNameOperationOptions{
		DeviceProfileId:      "v-DeviceProfileId",
		DeviceId:             "v-DeviceId",
		Container:            "v-Container",
		AudioCodec:           "v-AudioCodec",
		EnableAutoStreamCopy: new(true),
		AudioSampleRate:      new(7),
		AudioBitRate:         new(7),
		AudioChannels:        new(7),
		MaxAudioChannels:     new(7),
		Static:               new(true),
		CopyTimestamps:       new(true),
		StartTimeTicks:       new(int64(7)),
		Width:                new(7),
		Height:               new(7),
		MaxWidth:             new(7),
		MaxHeight:            new(7),
		VideoBitRate:         new(7),
		SubtitleStreamIndex:  new(7),
		SubtitleMethod:       SubtitleDeliveryMethodEncode,
		MaxVideoBitDepth:     new(7),
		VideoCodec:           "v-VideoCodec",
		AudioStreamIndex:     new(7),
		VideoStreamIndex:     new(7),
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
