// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// MBBackupApiAllBackupsInfo is the "MBBackup.Api.AllBackupsInfo" schema.
type MBBackupApiAllBackupsInfo struct {
	FullBackupInfo *MBBackupBackupInfo  `json:"FullBackupInfo,omitempty"`
	LightBackups   []MBBackupBackupInfo `json:"LightBackups,omitzero"`
}
