// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetBrandingConfigurationOperationResponse is the result of GetBrandingConfiguration.
type GetBrandingConfigurationOperationResponse struct {
	HttpResponse *http.Response
	Model        *BrandingBrandingOptions
}

// GetBrandingConfiguration calls GET /Branding/Configuration. Gets branding configuration.
func (c Client) GetBrandingConfiguration(ctx context.Context) (result GetBrandingConfigurationOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod: http.MethodGet,
		Path:       "/Branding/Configuration",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model BrandingBrandingOptions
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
