// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"io"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostEncodingCodecParametersOperationResponse is the result of PostEncodingCodecParameters.
type PostEncodingCodecParametersOperationResponse struct {
	HttpResponse *http.Response
}

// PostEncodingCodecParametersOperationOptions holds the query and header parameters of PostEncodingCodecParameters.
type PostEncodingCodecParametersOperationOptions struct {
	// Codec Id
	CodecId string

	// Parameter Context
	ParameterContext MediaEncodingCodecParameterContext
}

// ToHeaders returns the header parameters the options set.
func (o PostEncodingCodecParametersOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PostEncodingCodecParametersOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.CodecId != "" {
		out.Append("CodecId", o.CodecId)
	}
	if o.ParameterContext != "" {
		out.Append("ParameterContext", string(o.ParameterContext))
	}
	return &out
}

// PostEncodingCodecParameters calls POST /Encoding/CodecParameters. Updates the parameters for a specified codec.
//
// input is sent as contentType, or as application/octet-stream when that is empty.
func (c Client) PostEncodingCodecParameters(ctx context.Context, input io.Reader, contentType string, options PostEncodingCodecParametersOperationOptions) (result PostEncodingCodecParametersOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/octet-stream",
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          "/Encoding/CodecParameters",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.SetBody(input, contentType); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
