// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetEncodingCodecParametersOperationResponse is the result of GetEncodingCodecParameters.
type GetEncodingCodecParametersOperationResponse struct {
	HttpResponse *http.Response
	Model        *EditObjectContainer
}

// GetEncodingCodecParametersOperationOptions holds the query and header parameters of GetEncodingCodecParameters.
type GetEncodingCodecParametersOperationOptions struct {
	// Codec Id
	CodecId string

	// Parameter Context
	ParameterContext MediaEncodingCodecParameterContext
}

// ToHeaders returns the header parameters the options set.
func (o GetEncodingCodecParametersOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetEncodingCodecParametersOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.CodecId != "" {
		out.Append("CodecId", o.CodecId)
	}
	if o.ParameterContext != "" {
		out.Append("ParameterContext", string(o.ParameterContext))
	}
	return &out
}

// GetEncodingCodecParameters calls GET /Encoding/CodecParameters. Gets the parameters for a specified codec.
func (c Client) GetEncodingCodecParameters(ctx context.Context, options GetEncodingCodecParametersOperationOptions) (result GetEncodingCodecParametersOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/Encoding/CodecParameters",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model EditObjectContainer
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
