// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostCollectionsByIdItemsDeleteOperationResponse is the result of PostCollectionsByIdItemsDelete.
type PostCollectionsByIdItemsDeleteOperationResponse struct {
	HttpResponse *http.Response
}

// PostCollectionsByIdItemsDeleteOperationOptions holds the query and header parameters of PostCollectionsByIdItemsDelete.
type PostCollectionsByIdItemsDeleteOperationOptions struct {
	// Item id, comma delimited
	Ids string
}

// ToHeaders returns the header parameters the options set.
func (o PostCollectionsByIdItemsDeleteOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PostCollectionsByIdItemsDeleteOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Ids != "" {
		out.Append("Ids", o.Ids)
	}
	return &out
}

// PostCollectionsByIdItemsDelete calls POST /Collections/{Id}/Items/Delete. Removes items from a collection.
func (c Client) PostCollectionsByIdItemsDelete(ctx context.Context, id string, options PostCollectionsByIdItemsDeleteOperationOptions) (result PostCollectionsByIdItemsDeleteOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          fmt.Sprintf("/Collections/%s/Items/Delete", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
