// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// ActionsPostbackAction is the "Actions.PostbackAction" schema.
type ActionsPostbackAction struct {
	CommandParameterPropertyId string `json:"CommandParameterPropertyId,omitempty"`
	PostbackCommandId          string `json:"PostbackCommandId,omitempty"`
	TargetEditorId             string `json:"TargetEditorId,omitempty"`
}
