// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// ExternalIdInfo is the "ExternalIdInfo" schema.
type ExternalIdInfo struct {
	IsSupportedAsIdentifier *bool  `json:"IsSupportedAsIdentifier,omitempty"`
	Key                     string `json:"Key,omitempty"`
	Name                    string `json:"Name,omitempty"`
	UrlFormatString         string `json:"UrlFormatString,omitempty"`
	Website                 string `json:"Website,omitempty"`
}
