// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// EditorsEditorBase is the "Editors.EditorBase" schema.
type EditorsEditorBase struct {
	AllowEmpty              *bool             `json:"AllowEmpty,omitempty"`
	Description             string            `json:"Description,omitempty"`
	DisplayName             string            `json:"DisplayName,omitempty"`
	EditorType              CommonEditorTypes `json:"EditorType,omitempty"`
	FeatureRequiresPremiere *bool             `json:"FeatureRequiresPremiere,omitempty"`
	Id                      string            `json:"Id,omitempty"`
	IsAdvanced              *bool             `json:"IsAdvanced,omitempty"`
	IsReadOnly              *bool             `json:"IsReadOnly,omitempty"`
	Name                    string            `json:"Name,omitempty"`
	ParentId                string            `json:"ParentId,omitempty"`
}
