// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// RemoteSearchResult is the "RemoteSearchResult" schema.
type RemoteSearchResult struct {
	AlbumArtist           *RemoteSearchResult  `json:"AlbumArtist,omitempty"`
	Artists               []RemoteSearchResult `json:"Artists,omitzero"`
	DisambiguationComment string               `json:"DisambiguationComment,omitempty"`
	EndDate               string               `json:"EndDate,omitempty"`
	GameSystem            string               `json:"GameSystem,omitempty"`
	ImageUrl              string               `json:"ImageUrl,omitempty"`
	IndexNumber           int                  `json:"IndexNumber,omitempty"`
	IndexNumberEnd        int                  `json:"IndexNumberEnd,omitempty"`
	Name                  string               `json:"Name,omitempty"`
	OriginalTitle         string               `json:"OriginalTitle,omitempty"`
	Overview              string               `json:"Overview,omitempty"`
	ParentIndexNumber     int                  `json:"ParentIndexNumber,omitempty"`
	PersonType            PersonType           `json:"PersonType,omitempty"`
	PremiereDate          string               `json:"PremiereDate,omitempty"`
	ProductionYear        int                  `json:"ProductionYear,omitempty"`
	ProviderIds           map[string]string    `json:"ProviderIds,omitzero"`
	Role                  string               `json:"Role,omitempty"`
	SearchProviderName    string               `json:"SearchProviderName,omitempty"`
	SortIndexNumber       int                  `json:"SortIndexNumber,omitempty"`
	SortParentIndexNumber int                  `json:"SortParentIndexNumber,omitempty"`
	StartDate             string               `json:"StartDate,omitempty"`
	ThumbnailUrl          string               `json:"ThumbnailUrl,omitempty"`
	Type                  string               `json:"Type,omitempty"`
}
