// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// TupleDoubleDouble is the "Tuple_Double-Double" schema.
type TupleDoubleDouble struct {
	Item1 float64 `json:"Item1,omitempty"`
	Item2 float64 `json:"Item2,omitempty"`
}
