// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// ChapterInfo is the "ChapterInfo" schema.
type ChapterInfo struct {
	ChapterIndex       int        `json:"ChapterIndex,omitempty"`
	ImageTag           string     `json:"ImageTag,omitempty"`
	MarkerType         MarkerType `json:"MarkerType,omitempty"`
	Name               string     `json:"Name,omitempty"`
	StartPositionTicks int64      `json:"StartPositionTicks,omitempty"`
}
