// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// MediaPathInfo is the "MediaPathInfo" schema.
type MediaPathInfo struct {
	NetworkPath string `json:"NetworkPath,omitempty"`
	Password    string `json:"Password,omitempty"`
	Path        string `json:"Path,omitempty"`
	Username    string `json:"Username,omitempty"`
}
