// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// ResolutionWithRate is the "ResolutionWithRate" schema.
type ResolutionWithRate struct {
	FrameRate  float64     `json:"FrameRate,omitempty"`
	Height     int         `json:"Height,omitempty"`
	Resolution *Resolution `json:"Resolution,omitempty"`
	Width      int         `json:"Width,omitempty"`
}
