// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// GlobalizationCultureDto is the "Globalization.CultureDto" schema.
type GlobalizationCultureDto struct {
	DisplayName                 string   `json:"DisplayName,omitempty"`
	Name                        string   `json:"Name,omitempty"`
	ThreeLetterISOLanguageName  string   `json:"ThreeLetterISOLanguageName,omitempty"`
	ThreeLetterISOLanguageNames []string `json:"ThreeLetterISOLanguageNames,omitzero"`
	TwoLetterISOLanguageName    string   `json:"TwoLetterISOLanguageName,omitempty"`
	TwoLetterISOLanguageNames   []string `json:"TwoLetterISOLanguageNames,omitzero"`
}
