// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// ServerConfiguration is the "ServerConfiguration" schema.
type ServerConfiguration struct {
	AllowLegacyLocalNetworkPassword      *bool                   `json:"AllowLegacyLocalNetworkPassword,omitempty"`
	AutoRunWebApp                        *bool                   `json:"AutoRunWebApp,omitempty"`
	BannerText                           string                  `json:"BannerText,omitempty"`
	CachePath                            string                  `json:"CachePath,omitempty"`
	CertificatePassword                  string                  `json:"CertificatePassword,omitempty"`
	CertificatePath                      string                  `json:"CertificatePath,omitempty"`
	CollapseVideoFolders                 *bool                   `json:"CollapseVideoFolders,omitempty"`
	DashboardSourcePath                  string                  `json:"DashboardSourcePath,omitempty"`
	DatabaseAnalysisLimit                int                     `json:"DatabaseAnalysisLimit,omitempty"`
	DatabaseCacheSizeMB                  int                     `json:"DatabaseCacheSizeMB,omitempty"`
	DisableAsyncIO                       *bool                   `json:"DisableAsyncIO,omitempty"`
	DisableOutgoingIPv6                  *bool                   `json:"DisableOutgoingIPv6,omitempty"`
	EnableAutoUpdate                     *bool                   `json:"EnableAutoUpdate,omitempty"`
	EnableAutomaticRestart               *bool                   `json:"EnableAutomaticRestart,omitempty"`
	EnableCaseSensitiveItemIds           *bool                   `json:"EnableCaseSensitiveItemIds,omitempty"`
	EnableDashboardResponseCaching       *bool                   `json:"EnableDashboardResponseCaching,omitempty"`
	EnableDebugLevelLogging              *bool                   `json:"EnableDebugLevelLogging,omitempty"`
	EnableExternalContentInSuggestions   *bool                   `json:"EnableExternalContentInSuggestions,omitempty"`
	EnableHttps                          *bool                   `json:"EnableHttps,omitempty"`
	EnableOriginalTrackTitles            *bool                   `json:"EnableOriginalTrackTitles,omitempty"`
	EnablePeopleLetterSubFolders         *bool                   `json:"EnablePeopleLetterSubFolders,omitempty"`
	EnableRemoteAccess                   *bool                   `json:"EnableRemoteAccess,omitempty"`
	EnableSavedMetadataForPeople         *bool                   `json:"EnableSavedMetadataForPeople,omitempty"`
	EnableSqLiteMmio                     *bool                   `json:"EnableSqLiteMmio,omitempty"`
	EnableUPnP                           *bool                   `json:"EnableUPnP,omitempty"`
	HttpServerPortNumber                 int                     `json:"HttpServerPortNumber,omitempty"`
	HttpsPortNumber                      int                     `json:"HttpsPortNumber,omitempty"`
	ImageExtractionTimeoutMs             int                     `json:"ImageExtractionTimeoutMs,omitempty"`
	ImageExtractorUpgraded1              *bool                   `json:"ImageExtractorUpgraded1,omitempty"`
	ImageSavingConvention                ImageSavingConvention   `json:"ImageSavingConvention,omitempty"`
	IsBehindProxy                        *bool                   `json:"IsBehindProxy,omitempty"`
	IsInMaintenanceMode                  *bool                   `json:"IsInMaintenanceMode,omitempty"`
	IsPortAuthorized                     *bool                   `json:"IsPortAuthorized,omitempty"`
	IsRemoteIPFilterBlacklist            *bool                   `json:"IsRemoteIPFilterBlacklist,omitempty"`
	IsStartupWizardCompleted             *bool                   `json:"IsStartupWizardCompleted,omitempty"`
	LibraryMonitorDelaySeconds           int                     `json:"LibraryMonitorDelaySeconds,omitempty"`
	LocalNetworkAddresses                []string                `json:"LocalNetworkAddresses,omitzero"`
	LocalNetworkSubnets                  []string                `json:"LocalNetworkSubnets,omitzero"`
	LogAllQueryTimes                     *bool                   `json:"LogAllQueryTimes,omitempty"`
	LogFileRetentionDays                 int                     `json:"LogFileRetentionDays,omitempty"`
	MaintenanceModeMessage               string                  `json:"MaintenanceModeMessage,omitempty"`
	MaxAuthDbConnections                 int                     `json:"MaxAuthDbConnections,omitempty"`
	MaxLibraryDatabaseConnections        int                     `json:"MaxLibraryDatabaseConnections,omitempty"`
	MaxOtherDbConnections                int                     `json:"MaxOtherDbConnections,omitempty"`
	MetadataCountryCode                  string                  `json:"MetadataCountryCode,omitempty"`
	MetadataNetworkPath                  string                  `json:"MetadataNetworkPath,omitempty"`
	MetadataPath                         string                  `json:"MetadataPath,omitempty"`
	MigratedLibraryOptionsToDb           *bool                   `json:"MigratedLibraryOptionsToDb,omitempty"`
	MigratedToUserItemShares8            *bool                   `json:"MigratedToUserItemShares8,omitempty"`
	OptimizeDatabaseOnShutdown           *bool                   `json:"OptimizeDatabaseOnShutdown,omitempty"`
	PathSubstitutions                    []PathSubstitution      `json:"PathSubstitutions,omitzero"`
	PlaylistsUpgradedToM3U               *bool                   `json:"PlaylistsUpgradedToM3U,omitempty"`
	PreferredDetectedRemoteAddressFamily NetSocketsAddressFamily `json:"PreferredDetectedRemoteAddressFamily,omitempty"`
	PreferredMetadataLanguage            string                  `json:"PreferredMetadataLanguage,omitempty"`
	ProxyHeaderMode                      ProxyHeaderMode         `json:"ProxyHeaderMode,omitempty"`
	PublicHttpsPort                      int                     `json:"PublicHttpsPort,omitempty"`
	PublicPort                           int                     `json:"PublicPort,omitempty"`
	RemoteClientBitrateLimit             int                     `json:"RemoteClientBitrateLimit,omitempty"`
	RemoteIPFilter                       []string                `json:"RemoteIPFilter,omitzero"`
	RequireHttps                         *bool                   `json:"RequireHttps,omitempty"`
	RevertDebugLogging                   string                  `json:"RevertDebugLogging,omitempty"`
	RunAtStartup                         *bool                   `json:"RunAtStartup,omitempty"`
	ServerName                           string                  `json:"ServerName,omitempty"`
	SimultaneousStreamLimit              int                     `json:"SimultaneousStreamLimit,omitempty"`
	SortRemoveWords                      []string                `json:"SortRemoveWords,omitzero"`
	TvChannelsRefreshed                  *bool                   `json:"TvChannelsRefreshed,omitempty"`
	UICulture                            string                  `json:"UICulture,omitempty"`
	UninstalledPlugins                   []string                `json:"UninstalledPlugins,omitzero"`
	VacuumDatabaseOnStartup              *bool                   `json:"VacuumDatabaseOnStartup,omitempty"`
	ValidateImageTags                    *bool                   `json:"ValidateImageTags,omitempty"`
	WanDdns                              string                  `json:"WanDdns,omitempty"`
}
