// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostSystemConfigurationOperationResponse is the result of PostSystemConfiguration.
type PostSystemConfigurationOperationResponse struct {
	HttpResponse *http.Response
}

// PostSystemConfiguration calls POST /System/Configuration. Updates application configuration.
func (c Client) PostSystemConfiguration(ctx context.Context, input ServerConfiguration) (result PostSystemConfigurationOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod: http.MethodPost,
		Path:       "/System/Configuration",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
