// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// NotificationsNotificationLevel is the "Notifications.NotificationLevel" enum.
type NotificationsNotificationLevel string

// Values of NotificationsNotificationLevel.
const (
	NotificationsNotificationLevelNormal  NotificationsNotificationLevel = "Normal"
	NotificationsNotificationLevelWarning NotificationsNotificationLevel = "Warning"
	NotificationsNotificationLevelError   NotificationsNotificationLevel = "Error"
)

// PossibleValuesForNotificationsNotificationLevel returns every value of NotificationsNotificationLevel.
func PossibleValuesForNotificationsNotificationLevel() []string {
	return []string{
		string(NotificationsNotificationLevelNormal),
		string(NotificationsNotificationLevelWarning),
		string(NotificationsNotificationLevelError),
	}
}

// ScrollDirection is the "ScrollDirection" enum.
type ScrollDirection string

// Values of ScrollDirection.
const (
	ScrollDirectionHorizontal ScrollDirection = "Horizontal"
	ScrollDirectionVertical   ScrollDirection = "Vertical"
)

// PossibleValuesForScrollDirection returns every value of ScrollDirection.
func PossibleValuesForScrollDirection() []string {
	return []string{
		string(ScrollDirectionHorizontal),
		string(ScrollDirectionVertical),
	}
}
