// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// DevicesDeviceOptions is the "Devices.DeviceOptions" schema.
type DevicesDeviceOptions struct {
	CustomName string `json:"CustomName,omitempty"`
}
