// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// DlnaProfilesDeviceProfileType is the "Dlna.Profiles.DeviceProfileType" enum.
type DlnaProfilesDeviceProfileType string

// Values of DlnaProfilesDeviceProfileType.
const (
	DlnaProfilesDeviceProfileTypeSystem DlnaProfilesDeviceProfileType = "System"
	DlnaProfilesDeviceProfileTypeUser   DlnaProfilesDeviceProfileType = "User"
)

// PossibleValuesForDlnaProfilesDeviceProfileType returns every value of DlnaProfilesDeviceProfileType.
func PossibleValuesForDlnaProfilesDeviceProfileType() []string {
	return []string{
		string(DlnaProfilesDeviceProfileTypeSystem),
		string(DlnaProfilesDeviceProfileTypeUser),
	}
}

// DlnaProfilesHeaderMatchType is the "Dlna.Profiles.HeaderMatchType" enum.
type DlnaProfilesHeaderMatchType string

// Values of DlnaProfilesHeaderMatchType.
const (
	DlnaProfilesHeaderMatchTypeEquals    DlnaProfilesHeaderMatchType = "Equals"
	DlnaProfilesHeaderMatchTypeRegex     DlnaProfilesHeaderMatchType = "Regex"
	DlnaProfilesHeaderMatchTypeSubstring DlnaProfilesHeaderMatchType = "Substring"
)

// PossibleValuesForDlnaProfilesHeaderMatchType returns every value of DlnaProfilesHeaderMatchType.
func PossibleValuesForDlnaProfilesHeaderMatchType() []string {
	return []string{
		string(DlnaProfilesHeaderMatchTypeEquals),
		string(DlnaProfilesHeaderMatchTypeRegex),
		string(DlnaProfilesHeaderMatchTypeSubstring),
	}
}
