// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetDlnaProfileInfosOperationResponse is the result of GetDlnaProfileInfos.
type GetDlnaProfileInfosOperationResponse struct {
	HttpResponse *http.Response
	Model        []DlnaProfilesDlnaProfile
}

// GetDlnaProfileInfos calls GET /Dlna/ProfileInfos. Gets a list of profiles.
func (c Client) GetDlnaProfileInfos(ctx context.Context) (result GetDlnaProfileInfosOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodGet,
		Path:       "/Dlna/ProfileInfos",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
