// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostDlnaByUuIdConnectionmanagerControlOperationResponse is the result of PostDlnaByUuIdConnectionmanagerControl.
type PostDlnaByUuIdConnectionmanagerControlOperationResponse struct {
	HttpResponse *http.Response
}

// PostDlnaByUuIdConnectionmanagerControl calls POST /Dlna/{UuId}/connectionmanager/control. Processes a control request.
//
// input is sent as contentType, or as application/octet-stream when that is empty.
func (c Client) PostDlnaByUuIdConnectionmanagerControl(ctx context.Context, uuId string, input io.Reader, contentType string) (result PostDlnaByUuIdConnectionmanagerControlOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/octet-stream",
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodPost,
		Path:       fmt.Sprintf("/Dlna/%s/connectionmanager/control", url.PathEscape(uuId)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.SetBody(input, contentType); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
