// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetDlnaByUuIdDescriptionXmlOperationResponse is the result of GetDlnaByUuIdDescriptionXml.
//
// The operation answers text/xml, left unread in HttpResponse.Body, which
// the caller must close.
type GetDlnaByUuIdDescriptionXmlOperationResponse struct {
	HttpResponse *http.Response
}

// GetDlnaByUuIdDescriptionXml calls GET /Dlna/{UuId}/description.xml. Gets dlna server info.
func (c Client) GetDlnaByUuIdDescriptionXml(ctx context.Context, uuId string) (result GetDlnaByUuIdDescriptionXmlOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:     http.MethodGet,
		Path:           fmt.Sprintf("/Dlna/%s/description.xml", url.PathEscape(uuId)),
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
