// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetDlnaProfilesByIdOperationResponse is the result of GetDlnaProfilesById.
type GetDlnaProfilesByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *DlnaProfilesDlnaProfile
}

// GetDlnaProfilesById calls GET /Dlna/Profiles/{Id}. Gets a single profile.
func (c Client) GetDlnaProfilesById(ctx context.Context, id string) (result GetDlnaProfilesByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodGet,
		Path:       fmt.Sprintf("/Dlna/Profiles/%s", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model DlnaProfilesDlnaProfile
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
