// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetAudioByIdMainM3u8OperationResponse is the result of GetAudioByIdMainM3u8.
//
// The operation answers application/x-mpegURL, left unread in HttpResponse.Body, which
// the caller must close.
type GetAudioByIdMainM3u8OperationResponse struct {
	HttpResponse *http.Response
}

// GetAudioByIdMainM3u8OperationOptions holds the query and header parameters of GetAudioByIdMainM3u8.
type GetAudioByIdMainM3u8OperationOptions struct {
	// Optional. The dlna device profile id to utilize.
	DeviceProfileId string

	// The device id of the client requesting. Used to stop encoding processes when needed.
	DeviceId string

	// Container
	Container string

	// Optional. Specify a audio codec to encode to, e.g. mp3. If omitted the server will auto-select using the url's extension. Options: aac, mp3, vorbis, wma.
	AudioCodec string

	// Whether or not to allow automatic stream copy if requested values match the original source. Defaults to true.
	EnableAutoStreamCopy *bool

	// Optional. Specify a specific audio sample rate, e.g. 44100
	AudioSampleRate *int

	// Optional. Specify an audio bitrate to encode to, e.g. 128000. If omitted this will be left to encoder defaults.
	AudioBitRate *int

	// Optional. Specify a specific number of audio channels to encode to, e.g. 2
	AudioChannels *int

	// Optional. Specify a maximum number of audio channels to encode to, e.g. 2
	MaxAudioChannels *int

	// Optional. If true, the original file will be streamed statically without any encoding. Use either no url extension or the original file extension. true/false
	Static *bool

	// Whether or not to copy timestamps when transcoding with an offset. Defaults to false.
	CopyTimestamps *bool

	// Optional. Specify a starting offset, in ticks. 1ms = 10000 ticks.
	StartTimeTicks *int64

	// Optional. The fixed horizontal resolution of the encoded video.
	Width *int

	// Optional. The fixed vertical resolution of the encoded video.
	Height *int

	// Optional. The maximum horizontal resolution of the encoded video.
	MaxWidth *int

	// Optional. The maximum vertical resolution of the encoded video.
	MaxHeight *int

	// Optional. Specify a video bitrate to encode to, e.g. 500000. If omitted this will be left to encoder defaults.
	VideoBitRate *int

	// Optional. The index of the subtitle stream to use. If omitted no subtitles will be used.
	SubtitleStreamIndex *int

	// Optional. Specify the subtitle delivery method.
	SubtitleMethod SubtitleDeliveryMethod

	// Optional.
	MaxVideoBitDepth *int

	// Optional. Specify a video codec to encode to, e.g. h264. If omitted the server will auto-select using the url's extension. Options: h264, mpeg4, theora, vpx, wmv.
	VideoCodec string

	// Optional. The index of the audio stream to use. If omitted the first audio stream will be used.
	AudioStreamIndex *int

	// Optional. The index of the video stream to use. If omitted the first video stream will be used.
	VideoStreamIndex *int
}

// ToHeaders returns the header parameters the options set.
func (o GetAudioByIdMainM3u8OperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetAudioByIdMainM3u8OperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.DeviceProfileId != "" {
		out.Append("DeviceProfileId", o.DeviceProfileId)
	}
	if o.DeviceId != "" {
		out.Append("DeviceId", o.DeviceId)
	}
	if o.Container != "" {
		out.Append("Container", o.Container)
	}
	if o.AudioCodec != "" {
		out.Append("AudioCodec", o.AudioCodec)
	}
	if o.EnableAutoStreamCopy != nil {
		out.Append("EnableAutoStreamCopy", strconv.FormatBool(*o.EnableAutoStreamCopy))
	}
	if o.AudioSampleRate != nil {
		out.Append("AudioSampleRate", strconv.Itoa(*o.AudioSampleRate))
	}
	if o.AudioBitRate != nil {
		out.Append("AudioBitRate", strconv.Itoa(*o.AudioBitRate))
	}
	if o.AudioChannels != nil {
		out.Append("AudioChannels", strconv.Itoa(*o.AudioChannels))
	}
	if o.MaxAudioChannels != nil {
		out.Append("MaxAudioChannels", strconv.Itoa(*o.MaxAudioChannels))
	}
	if o.Static != nil {
		out.Append("Static", strconv.FormatBool(*o.Static))
	}
	if o.CopyTimestamps != nil {
		out.Append("CopyTimestamps", strconv.FormatBool(*o.CopyTimestamps))
	}
	if o.StartTimeTicks != nil {
		out.Append("StartTimeTicks", strconv.FormatInt(*o.StartTimeTicks, 10))
	}
	if o.Width != nil {
		out.Append("Width", strconv.Itoa(*o.Width))
	}
	if o.Height != nil {
		out.Append("Height", strconv.Itoa(*o.Height))
	}
	if o.MaxWidth != nil {
		out.Append("MaxWidth", strconv.Itoa(*o.MaxWidth))
	}
	if o.MaxHeight != nil {
		out.Append("MaxHeight", strconv.Itoa(*o.MaxHeight))
	}
	if o.VideoBitRate != nil {
		out.Append("VideoBitRate", strconv.Itoa(*o.VideoBitRate))
	}
	if o.SubtitleStreamIndex != nil {
		out.Append("SubtitleStreamIndex", strconv.Itoa(*o.SubtitleStreamIndex))
	}
	if o.SubtitleMethod != "" {
		out.Append("SubtitleMethod", string(o.SubtitleMethod))
	}
	if o.MaxVideoBitDepth != nil {
		out.Append("MaxVideoBitDepth", strconv.Itoa(*o.MaxVideoBitDepth))
	}
	if o.VideoCodec != "" {
		out.Append("VideoCodec", o.VideoCodec)
	}
	if o.AudioStreamIndex != nil {
		out.Append("AudioStreamIndex", strconv.Itoa(*o.AudioStreamIndex))
	}
	if o.VideoStreamIndex != nil {
		out.Append("VideoStreamIndex", strconv.Itoa(*o.VideoStreamIndex))
	}
	return &out
}

// GetAudioByIdMainM3u8 calls GET /Audio/{Id}/main.m3u8. Gets an audio stream using HTTP live streaming.
func (c Client) GetAudioByIdMainM3u8(ctx context.Context, id string, options GetAudioByIdMainM3u8OperationOptions) (result GetAudioByIdMainM3u8OperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod:     http.MethodGet,
		OptionsObject:  options,
		Path:           fmt.Sprintf("/Audio/%s/main.m3u8", url.PathEscape(id)),
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
