// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// CodecConfiguration is the "CodecConfiguration" schema.
type CodecConfiguration struct {
	CodecId   string `json:"CodecId,omitempty"`
	IsEnabled *bool  `json:"IsEnabled,omitempty"`
	Priority  int    `json:"Priority,omitempty"`
}
