// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetEncodingCodecConfigurationDefaultsOperationResponse is the result of GetEncodingCodecConfigurationDefaults.
type GetEncodingCodecConfigurationDefaultsOperationResponse struct {
	HttpResponse *http.Response
	Model        []CodecConfiguration
}

// GetEncodingCodecConfigurationDefaults calls GET /Encoding/CodecConfiguration/Defaults. Gets default codec configurations.
func (c Client) GetEncodingCodecConfigurationDefaults(ctx context.Context) (result GetEncodingCodecConfigurationDefaultsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodGet,
		Path:       "/Encoding/CodecConfiguration/Defaults",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
