// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// ProfileInformation is the "ProfileInformation" schema.
type ProfileInformation struct {
	BitDepths   []int  `json:"BitDepths,omitzero"`
	Description string `json:"Description,omitempty"`
	Details     string `json:"Details,omitempty"`
	Id          string `json:"Id,omitempty"`
	ShortName   string `json:"ShortName,omitempty"`
}
