// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostEnvironmentDirectoryContentsOperationResponse is the result of PostEnvironmentDirectoryContents.
type PostEnvironmentDirectoryContentsOperationResponse struct {
	HttpResponse *http.Response
	Model        []IOFileSystemEntryInfo
}

// PostEnvironmentDirectoryContentsOperationOptions holds the query and header parameters of PostEnvironmentDirectoryContents.
type PostEnvironmentDirectoryContentsOperationOptions struct {
	Path string

	// An optional filter to include or exclude files from the results. true/false
	IncludeFiles *bool

	// An optional filter to include or exclude folders from the results. true/false
	IncludeDirectories *bool
}

// ToHeaders returns the header parameters the options set.
func (o PostEnvironmentDirectoryContentsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PostEnvironmentDirectoryContentsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Path != "" {
		out.Append("Path", o.Path)
	}
	if o.IncludeFiles != nil {
		out.Append("IncludeFiles", strconv.FormatBool(*o.IncludeFiles))
	}
	if o.IncludeDirectories != nil {
		out.Append("IncludeDirectories", strconv.FormatBool(*o.IncludeDirectories))
	}
	return &out
}

// PostEnvironmentDirectoryContents calls POST /Environment/DirectoryContents. Gets the contents of a given directory in the file system.
func (c Client) PostEnvironmentDirectoryContents(ctx context.Context, input GetDirectoryContents, options PostEnvironmentDirectoryContentsOperationOptions) (result PostEnvironmentDirectoryContentsOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          "/Environment/DirectoryContents",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
