// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// RunUICommand is the "RunUICommand" schema.
type RunUICommand struct {
	ClientLocale string `json:"ClientLocale,omitempty"`
	CommandId    string `json:"CommandId,omitempty"`
	Data         string `json:"Data,omitempty"`
	ItemId       string `json:"ItemId,omitempty"`
	PageId       string `json:"PageId,omitempty"`
}
