// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetArtistsByNameImagesByTypeOperationResponse is the result of GetArtistsByNameImagesByType.
//
// The operation answers image/*, left unread in HttpResponse.Body, which
// the caller must close.
type GetArtistsByNameImagesByTypeOperationResponse struct {
	HttpResponse *http.Response
}

// GetArtistsByNameImagesByTypeOperationOptions holds the query and header parameters of GetArtistsByNameImagesByType.
type GetArtistsByNameImagesByTypeOperationOptions struct {
	// The maximum image width to return.
	MaxWidth *int

	// The maximum image height to return.
	MaxHeight *int

	// The fixed image width to return.
	Width *int

	// The fixed image height to return.
	Height *int

	// Optional quality setting, from 0-100. Defaults to 90 and should suffice in most cases.
	Quality *int

	// Optional. Supply the cache tag from the item object to receive strong caching headers.
	Tag string

	// Specify if whitespace should be cropped out of the image. True/False. If unspecified, whitespace will be cropped from logos and clear art.
	CropWhitespace *bool

	// Enable or disable image enhancers such as cover art.
	EnableImageEnhancers *bool

	// Determines the output foramt of the image - original,gif,jpg,png
	Format string

	// Optional. Apply a background color for transparent images.
	BackgroundColor string

	// Optional. Apply a foreground layer on top of the image.
	ForegroundLayer string

	// Set to true to force normalization of orientation in the event the renderer does not support it.
	AutoOrient *bool

	// Set to true to retain image animation (when supported).
	KeepAnimation *bool

	// Image Index
	Index *int
}

// ToHeaders returns the header parameters the options set.
func (o GetArtistsByNameImagesByTypeOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetArtistsByNameImagesByTypeOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.MaxWidth != nil {
		out.Append("MaxWidth", strconv.Itoa(*o.MaxWidth))
	}
	if o.MaxHeight != nil {
		out.Append("MaxHeight", strconv.Itoa(*o.MaxHeight))
	}
	if o.Width != nil {
		out.Append("Width", strconv.Itoa(*o.Width))
	}
	if o.Height != nil {
		out.Append("Height", strconv.Itoa(*o.Height))
	}
	if o.Quality != nil {
		out.Append("Quality", strconv.Itoa(*o.Quality))
	}
	if o.Tag != "" {
		out.Append("Tag", o.Tag)
	}
	if o.CropWhitespace != nil {
		out.Append("CropWhitespace", strconv.FormatBool(*o.CropWhitespace))
	}
	if o.EnableImageEnhancers != nil {
		out.Append("EnableImageEnhancers", strconv.FormatBool(*o.EnableImageEnhancers))
	}
	if o.Format != "" {
		out.Append("Format", o.Format)
	}
	if o.BackgroundColor != "" {
		out.Append("BackgroundColor", o.BackgroundColor)
	}
	if o.ForegroundLayer != "" {
		out.Append("ForegroundLayer", o.ForegroundLayer)
	}
	if o.AutoOrient != nil {
		out.Append("AutoOrient", strconv.FormatBool(*o.AutoOrient))
	}
	if o.KeepAnimation != nil {
		out.Append("KeepAnimation", strconv.FormatBool(*o.KeepAnimation))
	}
	if o.Index != nil {
		out.Append("Index", strconv.Itoa(*o.Index))
	}
	return &out
}

// GetArtistsByNameImagesByType calls GET /Artists/{Name}/Images/{Type}. Requires authentication as user.
func (c Client) GetArtistsByNameImagesByType(ctx context.Context, name string, typeParam ImageType, options GetArtistsByNameImagesByTypeOperationOptions) (result GetArtistsByNameImagesByTypeOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod:     http.MethodGet,
		OptionsObject:  options,
		Path:           fmt.Sprintf("/Artists/%s/Images/%s", url.PathEscape(name), url.PathEscape(string(typeParam))),
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
