// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostItemsByIdImagesByTypeOperationResponse is the result of PostItemsByIdImagesByType.
type PostItemsByIdImagesByTypeOperationResponse struct {
	HttpResponse *http.Response
}

// PostItemsByIdImagesByTypeOperationOptions holds the query and header parameters of PostItemsByIdImagesByType.
type PostItemsByIdImagesByTypeOperationOptions struct {
	// Image Index
	Index *int
}

// ToHeaders returns the header parameters the options set.
func (o PostItemsByIdImagesByTypeOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PostItemsByIdImagesByTypeOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Index != nil {
		out.Append("Index", strconv.Itoa(*o.Index))
	}
	return &out
}

// PostItemsByIdImagesByType calls POST /Items/{Id}/Images/{Type}. Uploads an image for an item, must be base64 encoded.
//
// input is sent as contentType, or as application/octet-stream when that is empty.
func (c Client) PostItemsByIdImagesByType(ctx context.Context, id string, typeParam ImageType, input io.Reader, contentType string, options PostItemsByIdImagesByTypeOperationOptions) (result PostItemsByIdImagesByTypeOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/octet-stream",
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          fmt.Sprintf("/Items/%s/Images/%s", url.PathEscape(id), url.PathEscape(string(typeParam))),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.SetBody(input, contentType); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
