// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// DeleteItemsByIdImagesByTypeByIndexOperationResponse is the result of DeleteItemsByIdImagesByTypeByIndex.
type DeleteItemsByIdImagesByTypeByIndexOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteItemsByIdImagesByTypeByIndex calls DELETE /Items/{Id}/Images/{Type}/{Index}. Requires authentication as administrator.
func (c Client) DeleteItemsByIdImagesByTypeByIndex(ctx context.Context, id string, typeParam ImageType, index int) (result DeleteItemsByIdImagesByTypeByIndexOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodDelete,
		Path:       fmt.Sprintf("/Items/%s/Images/%s/%d", url.PathEscape(id), url.PathEscape(string(typeParam)), index),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
