// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetItemsRemoteSearchImageOperationResponse is the result of GetItemsRemoteSearchImage.
//
// The operation answers image/*, left unread in HttpResponse.Body, which
// the caller must close.
type GetItemsRemoteSearchImageOperationResponse struct {
	HttpResponse *http.Response
}

// GetItemsRemoteSearchImageOperationOptions holds the query and header parameters of GetItemsRemoteSearchImage.
type GetItemsRemoteSearchImageOperationOptions struct {
	// The image url
	ImageUrl     string
	ProviderName string
}

// ToHeaders returns the header parameters the options set.
func (o GetItemsRemoteSearchImageOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetItemsRemoteSearchImageOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.ImageUrl != "" {
		out.Append("ImageUrl", o.ImageUrl)
	}
	if o.ProviderName != "" {
		out.Append("ProviderName", o.ProviderName)
	}
	return &out
}

// GetItemsRemoteSearchImage calls GET /Items/RemoteSearch/Image. Gets a remote image.
func (c Client) GetItemsRemoteSearchImage(ctx context.Context, options GetItemsRemoteSearchImageOperationOptions) (result GetItemsRemoteSearchImageOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod:     http.MethodGet,
		OptionsObject:  options,
		Path:           "/Items/RemoteSearch/Image",
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
