// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// SeriesInfo is the "SeriesInfo" schema.
type SeriesInfo struct {
	DisplayOrder        SeriesDisplayOrder        `json:"DisplayOrder,omitempty"`
	EnableAdultMetadata *bool                     `json:"EnableAdultMetadata,omitempty"`
	EpisodeAirDate      string                    `json:"EpisodeAirDate,omitempty"`
	IndexNumber         int                       `json:"IndexNumber,omitempty"`
	IsAutomated         *bool                     `json:"IsAutomated,omitempty"`
	MetadataCountryCode string                    `json:"MetadataCountryCode,omitempty"`
	MetadataLanguage    string                    `json:"MetadataLanguage,omitempty"`
	MetadataLanguages   []GlobalizationCultureDto `json:"MetadataLanguages,omitzero"`
	Name                string                    `json:"Name,omitempty"`
	ParentIndexNumber   int                       `json:"ParentIndexNumber,omitempty"`
	Path                string                    `json:"Path,omitempty"`
	PremiereDate        string                    `json:"PremiereDate,omitempty"`
	ProviderIds         map[string]string         `json:"ProviderIds,omitzero"`
	Year                int                       `json:"Year,omitempty"`
}
