// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// MetadataRefreshMode is the "MetadataRefreshMode" enum.
type MetadataRefreshMode string

// Values of MetadataRefreshMode.
const (
	MetadataRefreshModeValidationOnly MetadataRefreshMode = "ValidationOnly"
	MetadataRefreshModeDefault        MetadataRefreshMode = "Default"
	MetadataRefreshModeFullRefresh    MetadataRefreshMode = "FullRefresh"
)

// PossibleValuesForMetadataRefreshMode returns every value of MetadataRefreshMode.
func PossibleValuesForMetadataRefreshMode() []string {
	return []string{
		string(MetadataRefreshModeValidationOnly),
		string(MetadataRefreshModeDefault),
		string(MetadataRefreshModeFullRefresh),
	}
}
