// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// SongInfo is the "SongInfo" schema.
type SongInfo struct {
	Album               string                    `json:"Album,omitempty"`
	AlbumArtists        []string                  `json:"AlbumArtists,omitzero"`
	Artists             []string                  `json:"Artists,omitzero"`
	Composers           []string                  `json:"Composers,omitzero"`
	EnableAdultMetadata *bool                     `json:"EnableAdultMetadata,omitempty"`
	IndexNumber         int                       `json:"IndexNumber,omitempty"`
	IsAutomated         *bool                     `json:"IsAutomated,omitempty"`
	MetadataCountryCode string                    `json:"MetadataCountryCode,omitempty"`
	MetadataLanguage    string                    `json:"MetadataLanguage,omitempty"`
	MetadataLanguages   []GlobalizationCultureDto `json:"MetadataLanguages,omitzero"`
	Name                string                    `json:"Name,omitempty"`
	ParentIndexNumber   int                       `json:"ParentIndexNumber,omitempty"`
	Path                string                    `json:"Path,omitempty"`
	PremiereDate        string                    `json:"PremiereDate,omitempty"`
	ProviderIds         map[string]string         `json:"ProviderIds,omitzero"`
	Year                int                       `json:"Year,omitempty"`
}
