// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostLibraryMoviesUpdatedOperationResponse is the result of PostLibraryMoviesUpdated.
type PostLibraryMoviesUpdatedOperationResponse struct {
	HttpResponse *http.Response
}

// PostLibraryMoviesUpdated calls POST /Library/Movies/Updated. Deprecated.
func (c Client) PostLibraryMoviesUpdated(ctx context.Context) (result PostLibraryMoviesUpdatedOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod: http.MethodPost,
		Path:       "/Library/Movies/Updated",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
