// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostLibraryVirtualFoldersPathsOperationResponse is the result of PostLibraryVirtualFoldersPaths.
type PostLibraryVirtualFoldersPathsOperationResponse struct {
	HttpResponse *http.Response
}

// PostLibraryVirtualFoldersPaths calls POST /Library/VirtualFolders/Paths. Requires authentication as administrator.
func (c Client) PostLibraryVirtualFoldersPaths(ctx context.Context, input LibraryAddMediaPath) (result PostLibraryVirtualFoldersPathsOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod: http.MethodPost,
		Path:       "/Library/VirtualFolders/Paths",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
