// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// LibraryOptionsResult is the "LibraryOptionsResult" schema.
type LibraryOptionsResult struct {
	DefaultLibraryOptions *LibraryOptions      `json:"DefaultLibraryOptions,omitempty"`
	LyricsFetchers        []LibraryOptionInfo  `json:"LyricsFetchers,omitzero"`
	MetadataReaders       []LibraryOptionInfo  `json:"MetadataReaders,omitzero"`
	MetadataSavers        []LibraryOptionInfo  `json:"MetadataSavers,omitzero"`
	SubtitleFetchers      []LibraryOptionInfo  `json:"SubtitleFetchers,omitzero"`
	TypeOptions           []LibraryTypeOptions `json:"TypeOptions,omitzero"`
}
