// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// LibraryRemoveVirtualFolder is the "Library.RemoveVirtualFolder" schema.
type LibraryRemoveVirtualFolder struct {
	Id string `json:"Id,omitempty"`
}
