// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetItemsByIdAncestorsOperationResponse is the result of GetItemsByIdAncestors.
type GetItemsByIdAncestorsOperationResponse struct {
	HttpResponse *http.Response
	Model        []BaseItemDto
}

// GetItemsByIdAncestorsOperationOptions holds the query and header parameters of GetItemsByIdAncestors.
type GetItemsByIdAncestorsOperationOptions struct {
	// Optional. Filter by user id, and attach user data
	UserId string
}

// ToHeaders returns the header parameters the options set.
func (o GetItemsByIdAncestorsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetItemsByIdAncestorsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.UserId != "" {
		out.Append("UserId", o.UserId)
	}
	return &out
}

// GetItemsByIdAncestors calls GET /Items/{Id}/Ancestors. Gets all parents of an item.
func (c Client) GetItemsByIdAncestors(ctx context.Context, id string, options GetItemsByIdAncestorsOperationOptions) (result GetItemsByIdAncestorsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          fmt.Sprintf("/Items/%s/Ancestors", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
