// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetLibraryVirtualFoldersQueryOperationResponse is the result of GetLibraryVirtualFoldersQuery.
type GetLibraryVirtualFoldersQueryOperationResponse struct {
	HttpResponse *http.Response
	Model        *QueryResultVirtualFolderInfo
}

// GetLibraryVirtualFoldersQueryOperationOptions holds the query and header parameters of GetLibraryVirtualFoldersQuery.
type GetLibraryVirtualFoldersQueryOperationOptions struct {
	// Optional. The record index to start at. All items with a lower index will be dropped from the results.
	StartIndex int

	// Optional. The maximum number of records to return
	Limit int
}

// ToHeaders returns the header parameters the options set.
func (o GetLibraryVirtualFoldersQueryOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetLibraryVirtualFoldersQueryOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.StartIndex != 0 {
		out.Append("StartIndex", strconv.Itoa(o.StartIndex))
	}
	if o.Limit != 0 {
		out.Append("Limit", strconv.Itoa(o.Limit))
	}
	return &out
}

// GetLibraryVirtualFoldersQuery calls GET /Library/VirtualFolders/Query. Requires authentication as user.
func (c Client) GetLibraryVirtualFoldersQuery(ctx context.Context, options GetLibraryVirtualFoldersQueryOperationOptions) (result GetLibraryVirtualFoldersQueryOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/Library/VirtualFolders/Query",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model QueryResultVirtualFolderInfo
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}

// GetLibraryVirtualFoldersQueryCompleteResult is every result GetLibraryVirtualFoldersQueryComplete loaded.
type GetLibraryVirtualFoldersQueryCompleteResult struct {
	LatestHttpResponse *http.Response
	Items              []VirtualFolderInfo
}

// GetLibraryVirtualFoldersQueryComplete calls GetLibraryVirtualFoldersQuery page by page from options.StartIndex until every
// result is loaded. options.Limit is the page size, client.DefaultPageSize when
// unset.
func (c Client) GetLibraryVirtualFoldersQueryComplete(ctx context.Context, options GetLibraryVirtualFoldersQueryOperationOptions) (result GetLibraryVirtualFoldersQueryCompleteResult, err error) {
	if options.Limit <= 0 {
		options.Limit = client.DefaultPageSize
	}
	for {
		var page GetLibraryVirtualFoldersQueryOperationResponse
		page, err = c.GetLibraryVirtualFoldersQuery(ctx, options)
		result.LatestHttpResponse = page.HttpResponse
		if err != nil {
			err = fmt.Errorf("loading results: %w", err)
			return
		}
		if page.Model == nil || len(page.Model.Items) == 0 {
			return
		}
		result.Items = append(result.Items, page.Model.Items...)
		options.StartIndex += len(page.Model.Items)
		// a short page is the last; so is reaching the total, when the server
		// reports one (some Emby lists report 0 whatever they hold)
		if len(page.Model.Items) < options.Limit || page.Model.TotalRecordCount > 0 && options.StartIndex >= page.Model.TotalRecordCount {
			return
		}
	}
}
