// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostLibraryRefreshOperationResponse is the result of PostLibraryRefresh.
type PostLibraryRefreshOperationResponse struct {
	HttpResponse *http.Response
}

// PostLibraryRefresh calls POST /Library/Refresh. Starts a library scan.
func (c Client) PostLibraryRefresh(ctx context.Context) (result PostLibraryRefreshOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodPost,
		Path:       "/Library/Refresh",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
