// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetLibrariesAvailableOptionsOperationResponse is the result of GetLibrariesAvailableOptions.
type GetLibrariesAvailableOptionsOperationResponse struct {
	HttpResponse *http.Response
	Model        *LibraryOptionsResult
}

// GetLibrariesAvailableOptionsOperationOptions holds the query and header parameters of GetLibrariesAvailableOptions.
type GetLibrariesAvailableOptionsOperationOptions struct {
	// The collection type of the library (movies, tvshows, music, ...)
	LibraryContentType string

	// Whether the options are for a library being created, which is when the defaults are enabled
	IsNewLibrary *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetLibrariesAvailableOptionsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetLibrariesAvailableOptionsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.LibraryContentType != "" {
		out.Append("LibraryContentType", o.LibraryContentType)
	}
	if o.IsNewLibrary != nil {
		out.Append("IsNewLibrary", strconv.FormatBool(*o.IsNewLibrary))
	}
	return &out
}

// GetLibrariesAvailableOptions calls GET /Libraries/AvailableOptions. Requires authentication as user.
func (c Client) GetLibrariesAvailableOptions(ctx context.Context, options GetLibrariesAvailableOptionsOperationOptions) (result GetLibrariesAvailableOptionsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/Libraries/AvailableOptions",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model LibraryOptionsResult
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
