// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// LibraryRenameVirtualFolder is the "Library.RenameVirtualFolder" schema.
type LibraryRenameVirtualFolder struct {
	Id      string `json:"Id,omitempty"`
	NewName string `json:"NewName,omitempty"`
}
