// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// AllThemeMediaResult is the "AllThemeMediaResult" schema.
type AllThemeMediaResult struct {
	SoundtrackSongsResult *ThemeMediaResult `json:"SoundtrackSongsResult,omitempty"`
	ThemeSongsResult      *ThemeMediaResult `json:"ThemeSongsResult,omitempty"`
	ThemeVideosResult     *ThemeMediaResult `json:"ThemeVideosResult,omitempty"`
}
