// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostLibrarySeriesUpdatedOperationResponse is the result of PostLibrarySeriesUpdated.
type PostLibrarySeriesUpdatedOperationResponse struct {
	HttpResponse *http.Response
}

// PostLibrarySeriesUpdated calls POST /Library/Series/Updated. Deprecated.
func (c Client) PostLibrarySeriesUpdated(ctx context.Context) (result PostLibrarySeriesUpdatedOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodPost,
		Path:       "/Library/Series/Updated",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
