// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// ThemeMediaResult is the "ThemeMediaResult" schema.
type ThemeMediaResult struct {
	Items            []BaseItemDto `json:"Items,omitzero"`
	OwnerId          int64         `json:"OwnerId,omitempty"`
	TotalRecordCount int           `json:"TotalRecordCount,omitempty"`
}
