// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// LibraryUpdateMediaPath is the "Library.UpdateMediaPath" schema.
type LibraryUpdateMediaPath struct {
	Id       string         `json:"Id,omitempty"`
	PathInfo *MediaPathInfo `json:"PathInfo,omitempty"`
}
