// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetItemsByIdCriticReviewsOperationResponse is the result of GetItemsByIdCriticReviews.
type GetItemsByIdCriticReviewsOperationResponse struct {
	HttpResponse *http.Response
	Model        *QueryResultBaseItemDto
}

// GetItemsByIdCriticReviewsOperationOptions holds the query and header parameters of GetItemsByIdCriticReviews.
type GetItemsByIdCriticReviewsOperationOptions struct {
	// Optional. The record index to start at. All items with a lower index will be dropped from the results.
	StartIndex int

	// Optional. The maximum number of records to return
	Limit int
}

// ToHeaders returns the header parameters the options set.
func (o GetItemsByIdCriticReviewsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetItemsByIdCriticReviewsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.StartIndex != 0 {
		out.Append("StartIndex", strconv.Itoa(o.StartIndex))
	}
	if o.Limit != 0 {
		out.Append("Limit", strconv.Itoa(o.Limit))
	}
	return &out
}

// GetItemsByIdCriticReviews calls GET /Items/{Id}/CriticReviews. Gets critic reviews for an item.
func (c Client) GetItemsByIdCriticReviews(ctx context.Context, id string, options GetItemsByIdCriticReviewsOperationOptions) (result GetItemsByIdCriticReviewsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          fmt.Sprintf("/Items/%s/CriticReviews", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model QueryResultBaseItemDto
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}

// GetItemsByIdCriticReviewsCompleteResult is every result GetItemsByIdCriticReviewsComplete loaded.
type GetItemsByIdCriticReviewsCompleteResult struct {
	LatestHttpResponse *http.Response
	Items              []BaseItemDto
}

// GetItemsByIdCriticReviewsComplete calls GetItemsByIdCriticReviews page by page from options.StartIndex until every
// result is loaded. options.Limit is the page size, client.DefaultPageSize when
// unset.
func (c Client) GetItemsByIdCriticReviewsComplete(ctx context.Context, id string, options GetItemsByIdCriticReviewsOperationOptions) (result GetItemsByIdCriticReviewsCompleteResult, err error) {
	if options.Limit <= 0 {
		options.Limit = client.DefaultPageSize
	}
	for {
		var page GetItemsByIdCriticReviewsOperationResponse
		page, err = c.GetItemsByIdCriticReviews(ctx, id, options)
		result.LatestHttpResponse = page.HttpResponse
		if err != nil {
			err = fmt.Errorf("loading results: %w", err)
			return
		}
		if page.Model == nil || len(page.Model.Items) == 0 {
			return
		}
		result.Items = append(result.Items, page.Model.Items...)
		options.StartIndex += len(page.Model.Items)
		// a short page is the last; so is reaching the total, when the server
		// reports one (some Emby lists report 0 whatever they hold)
		if len(page.Model.Items) < options.Limit || page.Model.TotalRecordCount > 0 && options.StartIndex >= page.Model.TotalRecordCount {
			return
		}
	}
}
