// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetLiveTvLiveRecordingsByIdStreamOperationResponse is the result of GetLiveTvLiveRecordingsByIdStream.
//
// The operation answers video/*, left unread in HttpResponse.Body, which
// the caller must close.
type GetLiveTvLiveRecordingsByIdStreamOperationResponse struct {
	HttpResponse *http.Response
}

// GetLiveTvLiveRecordingsByIdStream calls GET /LiveTv/LiveRecordings/{Id}/stream. Gets a live tv channel.
func (c Client) GetLiveTvLiveRecordingsByIdStream(ctx context.Context, id string) (result GetLiveTvLiveRecordingsByIdStreamOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod:     http.MethodGet,
		Path:           fmt.Sprintf("/LiveTv/LiveRecordings/%s/stream", url.PathEscape(id)),
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
