// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// DeleteLiveTvChannelMappingsOperationResponse is the result of DeleteLiveTvChannelMappings.
type DeleteLiveTvChannelMappingsOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteLiveTvChannelMappingsOperationOptions holds the query and header parameters of DeleteLiveTvChannelMappings.
type DeleteLiveTvChannelMappingsOperationOptions struct {
	// Provider id
	ProviderId string
}

// ToHeaders returns the header parameters the options set.
func (o DeleteLiveTvChannelMappingsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o DeleteLiveTvChannelMappingsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.ProviderId != "" {
		out.Append("ProviderId", o.ProviderId)
	}
	return &out
}

// DeleteLiveTvChannelMappings calls DELETE /LiveTv/ChannelMappings. Requires authentication as administrator.
func (c Client) DeleteLiveTvChannelMappings(ctx context.Context, options DeleteLiveTvChannelMappingsOperationOptions) (result DeleteLiveTvChannelMappingsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod:    http.MethodDelete,
		OptionsObject: options,
		Path:          "/LiveTv/ChannelMappings",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
