// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetLiveTvLiveRecordingsByIdHlsBySegmentOperationResponse is the result of GetLiveTvLiveRecordingsByIdHlsBySegment.
//
// The operation answers application/octet-stream, left unread in HttpResponse.Body, which
// the caller must close.
type GetLiveTvLiveRecordingsByIdHlsBySegmentOperationResponse struct {
	HttpResponse *http.Response
}

// GetLiveTvLiveRecordingsByIdHlsBySegment calls GET /LiveTv/LiveRecordings/{Id}/hls/{Segment}. Gets a live recording.
func (c Client) GetLiveTvLiveRecordingsByIdHlsBySegment(ctx context.Context, id string, segment string) (result GetLiveTvLiveRecordingsByIdHlsBySegmentOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod:     http.MethodGet,
		Path:           fmt.Sprintf("/LiveTv/LiveRecordings/%s/hls/%s", url.PathEscape(id), url.PathEscape(segment)),
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
