// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// QueryResultLiveTvSeriesTimerInfoDto is the "QueryResult_LiveTv.SeriesTimerInfoDto" schema.
type QueryResultLiveTvSeriesTimerInfoDto struct {
	Items            []LiveTvSeriesTimerInfoDto `json:"Items,omitzero"`
	TotalRecordCount int                        `json:"TotalRecordCount,omitempty"`
}
