// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// ApiNameIdDescriptionPair is the "Api.NameIdDescriptionPair" schema.
type ApiNameIdDescriptionPair struct {
	Id            string `json:"Id,omitempty"`
	Name          string `json:"Name,omitempty"`
	ShortOverview string `json:"ShortOverview,omitempty"`
}
