// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostLiveTvTimersByIdDeleteOperationResponse is the result of PostLiveTvTimersByIdDelete.
type PostLiveTvTimersByIdDeleteOperationResponse struct {
	HttpResponse *http.Response
}

// PostLiveTvTimersByIdDelete calls POST /LiveTv/Timers/{Id}/Delete. Cancels a live tv timer.
func (c Client) PostLiveTvTimersByIdDelete(ctx context.Context, id string) (result PostLiveTvTimersByIdDeleteOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodPost,
		Path:       fmt.Sprintf("/LiveTv/Timers/%s/Delete", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
