// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// ApiListingProviderTypeInfo is the "Api.ListingProviderTypeInfo" schema.
type ApiListingProviderTypeInfo struct {
	Id       string `json:"Id,omitempty"`
	Name     string `json:"Name,omitempty"`
	SetupUrl string `json:"SetupUrl,omitempty"`
}
