// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetLiveTvRecordingsSeriesOperationResponse is the result of GetLiveTvRecordingsSeries.
type GetLiveTvRecordingsSeriesOperationResponse struct {
	HttpResponse *http.Response
	Model        *QueryResultBaseItemDto
}

// GetLiveTvRecordingsSeries calls GET /LiveTv/Recordings/Series. Gets live tv recordings.
func (c Client) GetLiveTvRecordingsSeries(ctx context.Context) (result GetLiveTvRecordingsSeriesOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod: http.MethodGet,
		Path:       "/LiveTv/Recordings/Series",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model QueryResultBaseItemDto
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
