// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetLiveTvTimersDefaultsOperationResponse is the result of GetLiveTvTimersDefaults.
type GetLiveTvTimersDefaultsOperationResponse struct {
	HttpResponse *http.Response
	Model        *LiveTvSeriesTimerInfoDto
}

// GetLiveTvTimersDefaultsOperationOptions holds the query and header parameters of GetLiveTvTimersDefaults.
type GetLiveTvTimersDefaultsOperationOptions struct {
	// Optional, to attach default values based on a program.
	ProgramId string
}

// ToHeaders returns the header parameters the options set.
func (o GetLiveTvTimersDefaultsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetLiveTvTimersDefaultsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.ProgramId != "" {
		out.Append("ProgramId", o.ProgramId)
	}
	return &out
}

// GetLiveTvTimersDefaults calls GET /LiveTv/Timers/Defaults. Gets default values for a new timer.
func (c Client) GetLiveTvTimersDefaults(ctx context.Context, options GetLiveTvTimersDefaultsOperationOptions) (result GetLiveTvTimersDefaultsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/LiveTv/Timers/Defaults",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model LiveTvSeriesTimerInfoDto
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
