// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// LibraryItemLinkType is the "Library.ItemLinkType" enum.
type LibraryItemLinkType string

// Values of LibraryItemLinkType.
const (
	LibraryItemLinkTypeArtists           LibraryItemLinkType = "Artists"
	LibraryItemLinkTypeAlbumArtists      LibraryItemLinkType = "AlbumArtists"
	LibraryItemLinkTypeGenres            LibraryItemLinkType = "Genres"
	LibraryItemLinkTypeStudios           LibraryItemLinkType = "Studios"
	LibraryItemLinkTypeTags              LibraryItemLinkType = "Tags"
	LibraryItemLinkTypeComposers         LibraryItemLinkType = "Composers"
	LibraryItemLinkTypeCollections       LibraryItemLinkType = "Collections"
	LibraryItemLinkTypeAlbums            LibraryItemLinkType = "Albums"
	LibraryItemLinkTypeCollectionFolders LibraryItemLinkType = "CollectionFolders"
	LibraryItemLinkTypeLiveTVSeries      LibraryItemLinkType = "LiveTVSeries"
	LibraryItemLinkTypeGameSystems       LibraryItemLinkType = "GameSystems"
)

// PossibleValuesForLibraryItemLinkType returns every value of LibraryItemLinkType.
func PossibleValuesForLibraryItemLinkType() []string {
	return []string{
		string(LibraryItemLinkTypeArtists),
		string(LibraryItemLinkTypeAlbumArtists),
		string(LibraryItemLinkTypeGenres),
		string(LibraryItemLinkTypeStudios),
		string(LibraryItemLinkTypeTags),
		string(LibraryItemLinkTypeComposers),
		string(LibraryItemLinkTypeCollections),
		string(LibraryItemLinkTypeAlbums),
		string(LibraryItemLinkTypeCollectionFolders),
		string(LibraryItemLinkTypeLiveTVSeries),
		string(LibraryItemLinkTypeGameSystems),
	}
}

// LiveTvChannelType is the "LiveTv.ChannelType" enum.
type LiveTvChannelType string

// Values of LiveTvChannelType.
const (
	LiveTvChannelTypeTV    LiveTvChannelType = "TV"
	LiveTvChannelTypeRadio LiveTvChannelType = "Radio"
)

// PossibleValuesForLiveTvChannelType returns every value of LiveTvChannelType.
func PossibleValuesForLiveTvChannelType() []string {
	return []string{
		string(LiveTvChannelTypeTV),
		string(LiveTvChannelTypeRadio),
	}
}

// LiveTvKeepUntil is the "LiveTv.KeepUntil" enum.
type LiveTvKeepUntil string

// Values of LiveTvKeepUntil.
const (
	LiveTvKeepUntilUntilDeleted     LiveTvKeepUntil = "UntilDeleted"
	LiveTvKeepUntilUntilSpaceNeeded LiveTvKeepUntil = "UntilSpaceNeeded"
	LiveTvKeepUntilUntilWatched     LiveTvKeepUntil = "UntilWatched"
	LiveTvKeepUntilUntilDate        LiveTvKeepUntil = "UntilDate"
)

// PossibleValuesForLiveTvKeepUntil returns every value of LiveTvKeepUntil.
func PossibleValuesForLiveTvKeepUntil() []string {
	return []string{
		string(LiveTvKeepUntilUntilDeleted),
		string(LiveTvKeepUntilUntilSpaceNeeded),
		string(LiveTvKeepUntilUntilWatched),
		string(LiveTvKeepUntilUntilDate),
	}
}

// LiveTvKeywordType is the "LiveTv.KeywordType" enum.
type LiveTvKeywordType string

// Values of LiveTvKeywordType.
const (
	LiveTvKeywordTypeName         LiveTvKeywordType = "Name"
	LiveTvKeywordTypeEpisodeTitle LiveTvKeywordType = "EpisodeTitle"
	LiveTvKeywordTypeOverview     LiveTvKeywordType = "Overview"
	LiveTvKeywordTypeActor        LiveTvKeywordType = "Actor"
	LiveTvKeywordTypeDirector     LiveTvKeywordType = "Director"
)

// PossibleValuesForLiveTvKeywordType returns every value of LiveTvKeywordType.
func PossibleValuesForLiveTvKeywordType() []string {
	return []string{
		string(LiveTvKeywordTypeName),
		string(LiveTvKeywordTypeEpisodeTitle),
		string(LiveTvKeywordTypeOverview),
		string(LiveTvKeywordTypeActor),
		string(LiveTvKeywordTypeDirector),
	}
}

// LiveTvRecordingStatus is the "LiveTv.RecordingStatus" enum.
type LiveTvRecordingStatus string

// Values of LiveTvRecordingStatus.
const (
	LiveTvRecordingStatusNew             LiveTvRecordingStatus = "New"
	LiveTvRecordingStatusInProgress      LiveTvRecordingStatus = "InProgress"
	LiveTvRecordingStatusCompleted       LiveTvRecordingStatus = "Completed"
	LiveTvRecordingStatusCancelled       LiveTvRecordingStatus = "Cancelled"
	LiveTvRecordingStatusConflictedOk    LiveTvRecordingStatus = "ConflictedOk"
	LiveTvRecordingStatusConflictedNotOk LiveTvRecordingStatus = "ConflictedNotOk"
	LiveTvRecordingStatusError           LiveTvRecordingStatus = "Error"
)

// PossibleValuesForLiveTvRecordingStatus returns every value of LiveTvRecordingStatus.
func PossibleValuesForLiveTvRecordingStatus() []string {
	return []string{
		string(LiveTvRecordingStatusNew),
		string(LiveTvRecordingStatusInProgress),
		string(LiveTvRecordingStatusCompleted),
		string(LiveTvRecordingStatusCancelled),
		string(LiveTvRecordingStatusConflictedOk),
		string(LiveTvRecordingStatusConflictedNotOk),
		string(LiveTvRecordingStatusError),
	}
}
