// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostLiveTvListingProvidersOperationResponse is the result of PostLiveTvListingProviders.
type PostLiveTvListingProvidersOperationResponse struct {
	HttpResponse *http.Response
	Model        *LiveTvListingsProviderInfo
}

// PostLiveTvListingProviders calls POST /LiveTv/ListingProviders. Adds a listing provider.
func (c Client) PostLiveTvListingProviders(ctx context.Context, input LiveTvListingsProviderInfo) (result PostLiveTvListingProvidersOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod: http.MethodPost,
		Path:       "/LiveTv/ListingProviders",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model LiveTvListingsProviderInfo
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
