// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// DeleteLiveTvSeriesTimersByIdOperationResponse is the result of DeleteLiveTvSeriesTimersById.
type DeleteLiveTvSeriesTimersByIdOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteLiveTvSeriesTimersById calls DELETE /LiveTv/SeriesTimers/{Id}. Cancels a live tv series timer.
func (c Client) DeleteLiveTvSeriesTimersById(ctx context.Context, id string) (result DeleteLiveTvSeriesTimersByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodDelete,
		Path:       fmt.Sprintf("/LiveTv/SeriesTimers/%s", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
