// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetLiveTvChannelMappingOptionsOperationResponse is the result of GetLiveTvChannelMappingOptions.
type GetLiveTvChannelMappingOptionsOperationResponse struct {
	HttpResponse *http.Response
	Model        json.RawMessage
}

// GetLiveTvChannelMappingOptionsOperationOptions holds the query and header parameters of GetLiveTvChannelMappingOptions.
type GetLiveTvChannelMappingOptionsOperationOptions struct {
	// Provider id
	ProviderId string
}

// ToHeaders returns the header parameters the options set.
func (o GetLiveTvChannelMappingOptionsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetLiveTvChannelMappingOptionsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.ProviderId != "" {
		out.Append("ProviderId", o.ProviderId)
	}
	return &out
}

// GetLiveTvChannelMappingOptions calls GET /LiveTv/ChannelMappingOptions. Requires authentication as administrator.
func (c Client) GetLiveTvChannelMappingOptions(ctx context.Context, options GetLiveTvChannelMappingOptionsOperationOptions) (result GetLiveTvChannelMappingOptionsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/LiveTv/ChannelMappingOptions",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
