// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetLocalizationCulturesOperationResponse is the result of GetLocalizationCultures.
type GetLocalizationCulturesOperationResponse struct {
	HttpResponse *http.Response
	Model        []GlobalizationCultureDto
}

// GetLocalizationCultures calls GET /Localization/Cultures. Gets known cultures.
func (c Client) GetLocalizationCultures(ctx context.Context) (result GetLocalizationCulturesOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodGet,
		Path:       "/Localization/Cultures",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
