// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetMusicGenresByNameOperationResponse is the result of GetMusicGenresByName.
type GetMusicGenresByNameOperationResponse struct {
	HttpResponse *http.Response
	Model        *BaseItemDto
}

// GetMusicGenresByNameOperationOptions holds the query and header parameters of GetMusicGenresByName.
type GetMusicGenresByNameOperationOptions struct {
	// Optional. Filter by user id, and attach user data
	UserId string
}

// ToHeaders returns the header parameters the options set.
func (o GetMusicGenresByNameOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetMusicGenresByNameOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.UserId != "" {
		out.Append("UserId", o.UserId)
	}
	return &out
}

// GetMusicGenresByName calls GET /MusicGenres/{Name}. Gets a music genre, by name.
func (c Client) GetMusicGenresByName(ctx context.Context, name string, options GetMusicGenresByNameOperationOptions) (result GetMusicGenresByNameOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          fmt.Sprintf("/MusicGenres/%s", url.PathEscape(name)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model BaseItemDto
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
