// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// PackageInfo is the "PackageInfo" schema.
type PackageInfo struct {
	Adult            *bool                `json:"adult,omitempty"`
	Category         string               `json:"category,omitempty"`
	EnableInAppStore *bool                `json:"enableInAppStore,omitempty"`
	ExpDate          string               `json:"expDate,omitempty"`
	FeatureId        string               `json:"featureId,omitempty"`
	Guid             string               `json:"guid,omitempty"`
	Id               string               `json:"id,omitempty"`
	Installs         int                  `json:"installs,omitempty"`
	IsPremium        *bool                `json:"isPremium,omitempty"`
	IsRegistered     *bool                `json:"isRegistered,omitempty"`
	Name             string               `json:"name,omitempty"`
	Overview         string               `json:"overview,omitempty"`
	Owner            string               `json:"owner,omitempty"`
	PreviewImage     string               `json:"previewImage,omitempty"`
	Price            float32              `json:"price,omitempty"`
	RichDescUrl      string               `json:"richDescUrl,omitempty"`
	ShortDescription string               `json:"shortDescription,omitempty"`
	TargetFilename   string               `json:"targetFilename,omitempty"`
	TargetSystem     PackageTargetSystem  `json:"targetSystem,omitempty"`
	ThumbImage       string               `json:"thumbImage,omitempty"`
	TileColor        string               `json:"tileColor,omitempty"`
	Type             string               `json:"type,omitempty"`
	Versions         []PackageVersionInfo `json:"versions,omitzero"`
}
