// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// DeletePackagesInstallingByIdOperationResponse is the result of DeletePackagesInstallingById.
type DeletePackagesInstallingByIdOperationResponse struct {
	HttpResponse *http.Response
}

// DeletePackagesInstallingById calls DELETE /Packages/Installing/{Id}. Cancels a package installation.
func (c Client) DeletePackagesInstallingById(ctx context.Context, id string) (result DeletePackagesInstallingByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodDelete,
		Path:       fmt.Sprintf("/Packages/Installing/%s", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
