// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetPackagesByNameOperationResponse is the result of GetPackagesByName.
type GetPackagesByNameOperationResponse struct {
	HttpResponse *http.Response
	Model        *PackageInfo
}

// GetPackagesByNameOperationOptions holds the query and header parameters of GetPackagesByName.
type GetPackagesByNameOperationOptions struct {
	// The guid of the associated assembly
	AssemblyGuid string
}

// ToHeaders returns the header parameters the options set.
func (o GetPackagesByNameOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetPackagesByNameOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.AssemblyGuid != "" {
		out.Append("AssemblyGuid", o.AssemblyGuid)
	}
	return &out
}

// GetPackagesByName calls GET /Packages/{Name}. Gets a package, by name or assembly guid.
func (c Client) GetPackagesByName(ctx context.Context, name string, options GetPackagesByNameOperationOptions) (result GetPackagesByNameOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          fmt.Sprintf("/Packages/%s", url.PathEscape(name)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model PackageInfo
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
