// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// SessionPartyInfo is the "Session.PartyInfo" schema.
type SessionPartyInfo struct {
	Id            string                `json:"Id,omitempty"`
	IsPlaying     *bool                 `json:"IsPlaying,omitempty"`
	MasterSession *SessionSessionInfo   `json:"MasterSession,omitempty"`
	Messages      []SessionPartyMessage `json:"Messages,omitzero"`
	Name          string                `json:"Name,omitempty"`
	Sessions      []SessionSessionInfo  `json:"Sessions,omitzero"`
}
