// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetPersonsByIdCreditsOperationResponse is the result of GetPersonsByIdCredits.
type GetPersonsByIdCreditsOperationResponse struct {
	HttpResponse *http.Response
	Model        []UserLibraryCreditsList
}

// GetPersonsByIdCredits calls GET /Persons/{Id}/Credits. Gets credits for a person.
func (c Client) GetPersonsByIdCredits(ctx context.Context, id string) (result GetPersonsByIdCreditsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodGet,
		Path:       fmt.Sprintf("/Persons/%s/Credits", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
