// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostPlaylistsByIdItemsOperationResponse is the result of PostPlaylistsByIdItems.
type PostPlaylistsByIdItemsOperationResponse struct {
	HttpResponse *http.Response
	Model        *PlaylistsAddToPlaylistResult
}

// PostPlaylistsByIdItemsOperationOptions holds the query and header parameters of PostPlaylistsByIdItems.
type PostPlaylistsByIdItemsOperationOptions struct {
	// User Id
	UserId string

	// Item id, comma delimited
	Ids string
}

// ToHeaders returns the header parameters the options set.
func (o PostPlaylistsByIdItemsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PostPlaylistsByIdItemsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.UserId != "" {
		out.Append("UserId", o.UserId)
	}
	if o.Ids != "" {
		out.Append("Ids", o.Ids)
	}
	return &out
}

// PostPlaylistsByIdItems calls POST /Playlists/{Id}/Items. Adds items to a playlist.
func (c Client) PostPlaylistsByIdItems(ctx context.Context, id string, options PostPlaylistsByIdItemsOperationOptions) (result PostPlaylistsByIdItemsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          fmt.Sprintf("/Playlists/%s/Items", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model PlaylistsAddToPlaylistResult
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
