// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// DeleteUsersByUserIdPlayingItemsByIdOperationResponse is the result of DeleteUsersByUserIdPlayingItemsById.
type DeleteUsersByUserIdPlayingItemsByIdOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteUsersByUserIdPlayingItemsByIdOperationOptions holds the query and header parameters of DeleteUsersByUserIdPlayingItemsById.
type DeleteUsersByUserIdPlayingItemsByIdOperationOptions struct {
	// The id of the MediaSource
	MediaSourceId string

	// The next media type that will play
	NextMediaType string

	// Optional. The position, in ticks, where playback stopped. 1ms = 10000 ticks.
	PositionTicks *int64
	LiveStreamId  string
	PlaySessionId string
}

// ToHeaders returns the header parameters the options set.
func (o DeleteUsersByUserIdPlayingItemsByIdOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o DeleteUsersByUserIdPlayingItemsByIdOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.MediaSourceId != "" {
		out.Append("MediaSourceId", o.MediaSourceId)
	}
	if o.NextMediaType != "" {
		out.Append("NextMediaType", o.NextMediaType)
	}
	if o.PositionTicks != nil {
		out.Append("PositionTicks", strconv.FormatInt(*o.PositionTicks, 10))
	}
	if o.LiveStreamId != "" {
		out.Append("LiveStreamId", o.LiveStreamId)
	}
	if o.PlaySessionId != "" {
		out.Append("PlaySessionId", o.PlaySessionId)
	}
	return &out
}

// DeleteUsersByUserIdPlayingItemsById calls DELETE /Users/{UserId}/PlayingItems/{Id}. Reports that a user has stopped playing an item.
func (c Client) DeleteUsersByUserIdPlayingItemsById(ctx context.Context, userId string, id string, options DeleteUsersByUserIdPlayingItemsByIdOperationOptions) (result DeleteUsersByUserIdPlayingItemsByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod:    http.MethodDelete,
		OptionsObject: options,
		Path:          fmt.Sprintf("/Users/%s/PlayingItems/%s", url.PathEscape(userId), url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
