// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"encoding/json"
	"net/http"
	"testing"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

func TestOperationPostUsersByUserIdPlayingItemsByIdProgress(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "", "")
	result, err := c.PostUsersByUserIdPlayingItemsByIdProgress(t.Context(), "p/userId", "p/id", ApiOnPlaybackProgress{}, PostUsersByUserIdPlayingItemsByIdProgressOperationOptions{
		MediaSourceId:       "v-MediaSourceId",
		PositionTicks:       new(int64(7)),
		IsPaused:            new(true),
		IsMuted:             new(true),
		AudioStreamIndex:    new(7),
		SubtitleStreamIndex: new(7),
		VolumeLevel:         new(7),
		PlayMethod:          PlayMethodTranscode,
		LiveStreamId:        "v-LiveStreamId",
		PlaySessionId:       "v-PlaySessionId",
		RepeatMode:          RepeatModeRepeatNone,
		SubtitleOffset:      new(7),
		PlaybackRate:        new(1.5),
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	expectRequest(t, r, http.MethodPost, "/Users/p%2FuserId/PlayingItems/p%2Fid/Progress")
	expectQuery(t, r, "MediaSourceId", "v-MediaSourceId")
	expectQuery(t, r, "PositionTicks", "7")
	expectQuery(t, r, "IsPaused", "true")
	expectQuery(t, r, "IsMuted", "true")
	expectQuery(t, r, "AudioStreamIndex", "7")
	expectQuery(t, r, "SubtitleStreamIndex", "7")
	expectQuery(t, r, "VolumeLevel", "7")
	expectQuery(t, r, "PlayMethod", "Transcode")
	expectQuery(t, r, "LiveStreamId", "v-LiveStreamId")
	expectQuery(t, r, "PlaySessionId", "v-PlaySessionId")
	expectQuery(t, r, "RepeatMode", "RepeatNone")
	expectQuery(t, r, "SubtitleOffset", "7")
	expectQuery(t, r, "PlaybackRate", "1.5")
	if got := r.Header.Get("Content-Type"); got != "application/json" {
		t.Errorf("Content-Type = %q, want %q", got, "application/json")
	}
	if !json.Valid([]byte(body)) {
		t.Errorf("body = %q, want JSON", body)
	}
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.PostUsersByUserIdPlayingItemsByIdProgress(t.Context(), "p/userId", "p/id", ApiOnPlaybackProgress{}, PostUsersByUserIdPlayingItemsByIdProgressOperationOptions{
		MediaSourceId:       "v-MediaSourceId",
		PositionTicks:       new(int64(7)),
		IsPaused:            new(true),
		IsMuted:             new(true),
		AudioStreamIndex:    new(7),
		SubtitleStreamIndex: new(7),
		VolumeLevel:         new(7),
		PlayMethod:          PlayMethodTranscode,
		LiveStreamId:        "v-LiveStreamId",
		PlaySessionId:       "v-PlaySessionId",
		RepeatMode:          RepeatModeRepeatNone,
		SubtitleOffset:      new(7),
		PlaybackRate:        new(1.5),
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
