// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// PlaybackStopInfo is the "PlaybackStopInfo" schema.
type PlaybackStopInfo struct {
	Failed          *bool        `json:"Failed,omitempty"`
	IsAutomated     *bool        `json:"IsAutomated,omitempty"`
	Item            *BaseItemDto `json:"Item,omitempty"`
	ItemId          string       `json:"ItemId,omitempty"`
	LiveStreamId    string       `json:"LiveStreamId,omitempty"`
	MediaSourceId   string       `json:"MediaSourceId,omitempty"`
	NextMediaType   string       `json:"NextMediaType,omitempty"`
	NowPlayingQueue []QueueItem  `json:"NowPlayingQueue,omitzero"`
	PlaySessionId   string       `json:"PlaySessionId,omitempty"`
	PlaylistIndex   int          `json:"PlaylistIndex,omitempty"`
	PlaylistItemId  string       `json:"PlaylistItemId,omitempty"`
	PlaylistLength  int          `json:"PlaylistLength,omitempty"`
	PositionTicks   int64        `json:"PositionTicks,omitempty"`
	SessionId       string       `json:"SessionId,omitempty"`
}
