// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostPlaylistsByIdItemsDeleteOperationResponse is the result of PostPlaylistsByIdItemsDelete.
type PostPlaylistsByIdItemsDeleteOperationResponse struct {
	HttpResponse *http.Response
}

// PostPlaylistsByIdItemsDeleteOperationOptions holds the query and header parameters of PostPlaylistsByIdItemsDelete.
type PostPlaylistsByIdItemsDeleteOperationOptions struct {
	EntryIds string
}

// ToHeaders returns the header parameters the options set.
func (o PostPlaylistsByIdItemsDeleteOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PostPlaylistsByIdItemsDeleteOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.EntryIds != "" {
		out.Append("EntryIds", o.EntryIds)
	}
	return &out
}

// PostPlaylistsByIdItemsDelete calls POST /Playlists/{Id}/Items/Delete. Removes items from a playlist.
func (c Client) PostPlaylistsByIdItemsDelete(ctx context.Context, id string, options PostPlaylistsByIdItemsDeleteOperationOptions) (result PostPlaylistsByIdItemsDeleteOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          fmt.Sprintf("/Playlists/%s/Items/Delete", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
