// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// RemoteImageResult is the "RemoteImageResult" schema.
type RemoteImageResult struct {
	Images           []RemoteImageInfo `json:"Images,omitzero"`
	Providers        []string          `json:"Providers,omitzero"`
	TotalRecordCount int               `json:"TotalRecordCount,omitempty"`
}
