// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetScheduledTasksByIdOperationResponse is the result of GetScheduledTasksById.
type GetScheduledTasksByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *TaskInfo
}

// GetScheduledTasksById calls GET /ScheduledTasks/{Id}. Gets a scheduled task, by Id.
func (c Client) GetScheduledTasksById(ctx context.Context, id string) (result GetScheduledTasksByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodGet,
		Path:       fmt.Sprintf("/ScheduledTasks/%s", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model TaskInfo
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
