// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// TaskInfo is the "TaskInfo" schema.
type TaskInfo struct {
	Category                  string            `json:"Category,omitempty"`
	CurrentProgressPercentage float64           `json:"CurrentProgressPercentage,omitempty"`
	Description               string            `json:"Description,omitempty"`
	Id                        string            `json:"Id,omitempty"`
	IsHidden                  *bool             `json:"IsHidden,omitempty"`
	Key                       string            `json:"Key,omitempty"`
	LastExecutionResult       *TaskResult       `json:"LastExecutionResult,omitempty"`
	Name                      string            `json:"Name,omitempty"`
	State                     TaskState         `json:"State,omitempty"`
	Triggers                  []TaskTriggerInfo `json:"Triggers,omitzero"`
}
