// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostSessionsByIdCommandByCommandOperationResponse is the result of PostSessionsByIdCommandByCommand.
type PostSessionsByIdCommandByCommandOperationResponse struct {
	HttpResponse *http.Response
}

// PostSessionsByIdCommandByCommand calls POST /Sessions/{Id}/Command/{Command}. Issues a system command to a client.
func (c Client) PostSessionsByIdCommandByCommand(ctx context.Context, id string, command string) (result PostSessionsByIdCommandByCommandOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodPost,
		Path:       fmt.Sprintf("/Sessions/%s/Command/%s", url.PathEscape(id), url.PathEscape(command)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
