// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostSessionsByIdPlayingByCommandOperationResponse is the result of PostSessionsByIdPlayingByCommand.
type PostSessionsByIdPlayingByCommandOperationResponse struct {
	HttpResponse *http.Response
}

// PostSessionsByIdPlayingByCommandOperationOptions holds the query and header parameters of PostSessionsByIdPlayingByCommand.
type PostSessionsByIdPlayingByCommandOperationOptions struct {
	// The position to seek to, in ticks
	SeekPositionTicks *int64
}

// ToHeaders returns the header parameters the options set.
func (o PostSessionsByIdPlayingByCommandOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PostSessionsByIdPlayingByCommandOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.SeekPositionTicks != nil {
		out.Append("SeekPositionTicks", strconv.FormatInt(*o.SeekPositionTicks, 10))
	}
	return &out
}

// PostSessionsByIdPlayingByCommand calls POST /Sessions/{Id}/Playing/{Command}. Issues a playstate command to a client.
func (c Client) PostSessionsByIdPlayingByCommand(ctx context.Context, id string, command PlaystateCommand, input PlaystateRequest, options PostSessionsByIdPlayingByCommandOperationOptions) (result PostSessionsByIdPlayingByCommandOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          fmt.Sprintf("/Sessions/%s/Playing/%s", url.PathEscape(id), url.PathEscape(string(command))),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
