// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostSessionsByIdViewingOperationResponse is the result of PostSessionsByIdViewing.
type PostSessionsByIdViewingOperationResponse struct {
	HttpResponse *http.Response
}

// PostSessionsByIdViewingOperationOptions holds the query and header parameters of PostSessionsByIdViewing.
type PostSessionsByIdViewingOperationOptions struct {
	// The type of item to browse to.
	ItemType string

	// The Id of the item.
	ItemId string

	// The name of the item.
	ItemName string
}

// ToHeaders returns the header parameters the options set.
func (o PostSessionsByIdViewingOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PostSessionsByIdViewingOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.ItemType != "" {
		out.Append("ItemType", o.ItemType)
	}
	if o.ItemId != "" {
		out.Append("ItemId", o.ItemId)
	}
	if o.ItemName != "" {
		out.Append("ItemName", o.ItemName)
	}
	return &out
}

// PostSessionsByIdViewing calls POST /Sessions/{Id}/Viewing. Instructs a session to browse to an item or view.
func (c Client) PostSessionsByIdViewing(ctx context.Context, id string, options PostSessionsByIdViewingOperationOptions) (result PostSessionsByIdViewingOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          fmt.Sprintf("/Sessions/%s/Viewing", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
