// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"io"
	"net/http"
	"testing"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

func TestOperationGetVideosByIdByMediaSourceIdAttachmentsByIndexStream(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "application/octet-stream", "file bytes")
	result, err := c.GetVideosByIdByMediaSourceIdAttachmentsByIndexStream(t.Context(), "p/id", "p/mediaSourceId", 7)
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/Videos/p%2Fid/p%2FmediaSourceId/Attachments/7/Stream")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	streamed, _ := io.ReadAll(result.HttpResponse.Body)
	_ = result.HttpResponse.Body.Close()
	if string(streamed) != "file bytes" {
		t.Errorf("streamed body = %q", streamed)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.GetVideosByIdByMediaSourceIdAttachmentsByIndexStream(t.Context(), "p/id", "p/mediaSourceId", 7)
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
