// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetVideosByIdByMediaSourceIdSubtitlesByIndexStreamByFormatOperationResponse is the result of GetVideosByIdByMediaSourceIdSubtitlesByIndexStreamByFormat.
//
// The operation answers text/*, left unread in HttpResponse.Body, which
// the caller must close.
type GetVideosByIdByMediaSourceIdSubtitlesByIndexStreamByFormatOperationResponse struct {
	HttpResponse *http.Response
}

// GetVideosByIdByMediaSourceIdSubtitlesByIndexStreamByFormatOperationOptions holds the query and header parameters of GetVideosByIdByMediaSourceIdSubtitlesByIndexStreamByFormat.
type GetVideosByIdByMediaSourceIdSubtitlesByIndexStreamByFormatOperationOptions struct {
	// StartPositionTicks
	StartPositionTicks int64

	// EndPositionTicks
	EndPositionTicks int64

	// CopyTimestamps
	CopyTimestamps *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetVideosByIdByMediaSourceIdSubtitlesByIndexStreamByFormatOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetVideosByIdByMediaSourceIdSubtitlesByIndexStreamByFormatOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.StartPositionTicks != 0 {
		out.Append("StartPositionTicks", strconv.FormatInt(o.StartPositionTicks, 10))
	}
	if o.EndPositionTicks != 0 {
		out.Append("EndPositionTicks", strconv.FormatInt(o.EndPositionTicks, 10))
	}
	if o.CopyTimestamps != nil {
		out.Append("CopyTimestamps", strconv.FormatBool(*o.CopyTimestamps))
	}
	return &out
}

// GetVideosByIdByMediaSourceIdSubtitlesByIndexStreamByFormat calls GET /Videos/{Id}/{MediaSourceId}/Subtitles/{Index}/Stream.{Format}. Gets subtitles in a specified format.
func (c Client) GetVideosByIdByMediaSourceIdSubtitlesByIndexStreamByFormat(ctx context.Context, id string, mediaSourceId string, index int, format string, options GetVideosByIdByMediaSourceIdSubtitlesByIndexStreamByFormatOperationOptions) (result GetVideosByIdByMediaSourceIdSubtitlesByIndexStreamByFormatOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:     http.MethodGet,
		OptionsObject:  options,
		Path:           fmt.Sprintf("/Videos/%s/%s/Subtitles/%d/Stream.%s", url.PathEscape(id), url.PathEscape(mediaSourceId), index, url.PathEscape(format)),
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
