// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostSyncJobItemsByIdTransferredOperationResponse is the result of PostSyncJobItemsByIdTransferred.
type PostSyncJobItemsByIdTransferredOperationResponse struct {
	HttpResponse *http.Response
}

// PostSyncJobItemsByIdTransferred calls POST /Sync/JobItems/{Id}/Transferred. Reports that a sync job item has successfully been transferred.
func (c Client) PostSyncJobItemsByIdTransferred(ctx context.Context, id string) (result PostSyncJobItemsByIdTransferredOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodPost,
		Path:       fmt.Sprintf("/Sync/JobItems/%s/Transferred", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
