// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetSyncJobsByIdOperationResponse is the result of GetSyncJobsById.
type GetSyncJobsByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *SyncJob
}

// GetSyncJobsById calls GET /Sync/Jobs/{Id}. Gets a sync job.
func (c Client) GetSyncJobsById(ctx context.Context, id string) (result GetSyncJobsByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/Sync/Jobs/%s", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model SyncJob
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
