// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetSyncJobItemsByIdFileOperationResponse is the result of GetSyncJobItemsByIdFile.
//
// The operation answers application/octet-stream, left unread in HttpResponse.Body, which
// the caller must close.
type GetSyncJobItemsByIdFileOperationResponse struct {
	HttpResponse *http.Response
}

// GetSyncJobItemsByIdFile calls GET /Sync/JobItems/{Id}/File. Gets a sync job item file.
func (c Client) GetSyncJobItemsByIdFile(ctx context.Context, id string) (result GetSyncJobItemsByIdFileOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:     http.MethodGet,
		Path:           fmt.Sprintf("/Sync/JobItems/%s/File", url.PathEscape(id)),
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
