// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// DeleteSyncJobItemsByIdOperationResponse is the result of DeleteSyncJobItemsById.
type DeleteSyncJobItemsByIdOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteSyncJobItemsById calls DELETE /Sync/JobItems/{Id}. Cancels a sync job item.
func (c Client) DeleteSyncJobItemsById(ctx context.Context, id string) (result DeleteSyncJobItemsByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodDelete,
		Path:       fmt.Sprintf("/Sync/JobItems/%s", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
