// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// SyncedItem is the "SyncedItem" schema.
type SyncedItem struct {
	AdditionalFiles    []ItemFileInfo `json:"AdditionalFiles,omitzero"`
	Item               *BaseItemDto   `json:"Item,omitempty"`
	OriginalFileName   string         `json:"OriginalFileName,omitempty"`
	ServerId           string         `json:"ServerId,omitempty"`
	SyncJobDateCreated string         `json:"SyncJobDateCreated,omitempty"`
	SyncJobId          int64          `json:"SyncJobId,omitempty"`
	SyncJobItemId      int64          `json:"SyncJobItemId,omitempty"`
	SyncJobName        string         `json:"SyncJobName,omitempty"`
	UserId             string         `json:"UserId,omitempty"`
}
