// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetSyncTargetsOperationResponse is the result of GetSyncTargets.
type GetSyncTargetsOperationResponse struct {
	HttpResponse *http.Response
	Model        []SyncTarget
}

// GetSyncTargetsOperationOptions holds the query and header parameters of GetSyncTargets.
type GetSyncTargetsOperationOptions struct {
	// UserId
	UserId string
}

// ToHeaders returns the header parameters the options set.
func (o GetSyncTargetsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetSyncTargetsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.UserId != "" {
		out.Append("UserId", o.UserId)
	}
	return &out
}

// GetSyncTargets calls GET /Sync/Targets. Gets a list of available sync targets.
func (c Client) GetSyncTargets(ctx context.Context, options GetSyncTargetsOperationOptions) (result GetSyncTargetsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/Sync/Targets",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
