// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// SyncDataRequest is the "SyncDataRequest" schema.
type SyncDataRequest struct {
	InternalTargetIds []int64  `json:"InternalTargetIds,omitzero"`
	LocalItemIds      []string `json:"LocalItemIds,omitzero"`
}
