// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetSyncOptionsOperationResponse is the result of GetSyncOptions.
type GetSyncOptionsOperationResponse struct {
	HttpResponse *http.Response
	Model        *SyncDialogOptions
}

// GetSyncOptionsOperationOptions holds the query and header parameters of GetSyncOptions.
type GetSyncOptionsOperationOptions struct {
	// UserId
	UserId string

	// ItemIds
	ItemIds string

	// ParentId
	ParentId string

	// TargetId
	TargetId string

	// Category
	Category SyncCategory
}

// ToHeaders returns the header parameters the options set.
func (o GetSyncOptionsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetSyncOptionsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.UserId != "" {
		out.Append("UserId", o.UserId)
	}
	if o.ItemIds != "" {
		out.Append("ItemIds", o.ItemIds)
	}
	if o.ParentId != "" {
		out.Append("ParentId", o.ParentId)
	}
	if o.TargetId != "" {
		out.Append("TargetId", o.TargetId)
	}
	if o.Category != "" {
		out.Append("Category", string(o.Category))
	}
	return &out
}

// GetSyncOptions calls GET /Sync/Options. Gets a list of available sync targets.
func (c Client) GetSyncOptions(ctx context.Context, options GetSyncOptionsOperationOptions) (result GetSyncOptionsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/Sync/Options",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model SyncDialogOptions
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
