// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetSystemLogsQueryOperationResponse is the result of GetSystemLogsQuery.
type GetSystemLogsQueryOperationResponse struct {
	HttpResponse *http.Response
	Model        *QueryResultLogFile
}

// GetSystemLogsQueryOperationOptions holds the query and header parameters of GetSystemLogsQuery.
type GetSystemLogsQueryOperationOptions struct {
	// Optional. The record index to start at. All items with a lower index will be dropped from the results.
	StartIndex *int

	// Optional. The maximum number of records to return
	Limit *int
}

// ToHeaders returns the header parameters the options set.
func (o GetSystemLogsQueryOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetSystemLogsQueryOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.StartIndex != nil {
		out.Append("StartIndex", strconv.Itoa(*o.StartIndex))
	}
	if o.Limit != nil {
		out.Append("Limit", strconv.Itoa(*o.Limit))
	}
	return &out
}

// GetSystemLogsQuery calls GET /System/Logs/Query. Gets a list of available server log files.
func (c Client) GetSystemLogsQuery(ctx context.Context, options GetSystemLogsQueryOperationOptions) (result GetSystemLogsQueryOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/System/Logs/Query",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model QueryResultLogFile
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}

// GetSystemLogsQueryCompleteResult is every result GetSystemLogsQueryComplete loaded.
type GetSystemLogsQueryCompleteResult struct {
	LatestHttpResponse *http.Response
	Items              []LogFile
}

// GetSystemLogsQueryComplete calls GetSystemLogsQuery page by page from options.StartIndex until every
// result is loaded. options.Limit is the page size, client.DefaultPageSize when
// unset.
func (c Client) GetSystemLogsQueryComplete(ctx context.Context, options GetSystemLogsQueryOperationOptions) (result GetSystemLogsQueryCompleteResult, err error) {
	limit := client.DefaultPageSize
	if options.Limit != nil && *options.Limit > 0 {
		limit = *options.Limit
	}
	options.Limit = &limit
	start := 0
	if options.StartIndex != nil {
		start = *options.StartIndex
	}
	for {
		var page GetSystemLogsQueryOperationResponse
		page, err = c.GetSystemLogsQuery(ctx, options)
		result.LatestHttpResponse = page.HttpResponse
		if err != nil {
			err = fmt.Errorf("loading results: %w", err)
			return
		}
		if page.Model == nil || len(page.Model.Items) == 0 {
			return
		}
		result.Items = append(result.Items, page.Model.Items...)
		start += len(page.Model.Items)
		options.StartIndex = &start
		// a short page is the last; so is reaching the total, when the server
		// reports one (some Emby lists report 0 whatever they hold)
		if len(page.Model.Items) < limit || page.Model.TotalRecordCount > 0 && start >= page.Model.TotalRecordCount {
			return
		}
	}
}
