// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// UserLibraryRemoveTags is the "UserLibrary.RemoveTags" schema.
type UserLibraryRemoveTags struct {
	Tags []NameIdPair `json:"Tags,omitzero"`
}
