// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"io"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostEncodingPublicToneMapOptionsOperationResponse is the result of PostEncodingPublicToneMapOptions.
type PostEncodingPublicToneMapOptionsOperationResponse struct {
	HttpResponse *http.Response
}

// PostEncodingPublicToneMapOptions calls POST /Encoding/PublicToneMapOptions. Updates the tone mapping options.
//
// input is sent as contentType, or as application/octet-stream when that is empty.
func (c Client) PostEncodingPublicToneMapOptions(ctx context.Context, input io.Reader, contentType string) (result PostEncodingPublicToneMapOptionsOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/octet-stream",
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod: http.MethodPost,
		Path:       "/Encoding/PublicToneMapOptions",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.SetBody(input, contentType); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
