// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"net/http"
	"slices"
	"testing"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

func TestOperationGetShowsNextUp(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "application/json", "{}")
	result, err := c.GetShowsNextUp(t.Context(), GetShowsNextUpOperationOptions{
		UserId:           "v-UserId",
		StartIndex:       7,
		Limit:            7,
		Fields:           "v-Fields",
		SeriesId:         "v-SeriesId",
		ParentId:         "v-ParentId",
		EnableImages:     new(true),
		ImageTypeLimit:   7,
		EnableImageTypes: "v-EnableImageTypes",
		EnableUserData:   new(true),
		LegacyNextUp:     new(true),
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/Shows/NextUp")
	expectQuery(t, r, "UserId", "v-UserId")
	expectQuery(t, r, "StartIndex", "7")
	expectQuery(t, r, "Limit", "7")
	expectQuery(t, r, "Fields", "v-Fields")
	expectQuery(t, r, "SeriesId", "v-SeriesId")
	expectQuery(t, r, "ParentId", "v-ParentId")
	expectQuery(t, r, "EnableImages", "true")
	expectQuery(t, r, "ImageTypeLimit", "7")
	expectQuery(t, r, "EnableImageTypes", "v-EnableImageTypes")
	expectQuery(t, r, "EnableUserData", "true")
	expectQuery(t, r, "LegacyNextUp", "true")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	if result.Model == nil {
		t.Error("the model was not decoded")
	}

	// a 204 is a null result, with no model
	c, _ = newOperationServer(t, http.StatusNoContent, "", "")
	result, err = c.GetShowsNextUp(t.Context(), GetShowsNextUpOperationOptions{
		UserId:           "v-UserId",
		StartIndex:       7,
		Limit:            7,
		Fields:           "v-Fields",
		SeriesId:         "v-SeriesId",
		ParentId:         "v-ParentId",
		EnableImages:     new(true),
		ImageTypeLimit:   7,
		EnableImageTypes: "v-EnableImageTypes",
		EnableUserData:   new(true),
		LegacyNextUp:     new(true),
	})
	if err != nil || result.Model != nil {
		t.Errorf("a 204 = %v, model %v", err, result.Model)
	}

	// an answer that does not decode is an error, with the response
	c, _ = newOperationServer(t, 200, "application/json", "<html>")
	result, err = c.GetShowsNextUp(t.Context(), GetShowsNextUpOperationOptions{
		UserId:           "v-UserId",
		StartIndex:       7,
		Limit:            7,
		Fields:           "v-Fields",
		SeriesId:         "v-SeriesId",
		ParentId:         "v-ParentId",
		EnableImages:     new(true),
		ImageTypeLimit:   7,
		EnableImageTypes: "v-EnableImageTypes",
		EnableUserData:   new(true),
		LegacyNextUp:     new(true),
	})
	if err == nil || client.StatusCode(err) != 0 || result.HttpResponse == nil {
		t.Errorf("an answer that does not decode = %v", err)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.GetShowsNextUp(t.Context(), GetShowsNextUpOperationOptions{
		UserId:           "v-UserId",
		StartIndex:       7,
		Limit:            7,
		Fields:           "v-Fields",
		SeriesId:         "v-SeriesId",
		ParentId:         "v-ParentId",
		EnableImages:     new(true),
		ImageTypeLimit:   7,
		EnableImageTypes: "v-EnableImageTypes",
		EnableUserData:   new(true),
		LegacyNextUp:     new(true),
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}

func TestOperationGetShowsNextUpComplete(t *testing.T) {
	t.Parallel()

	c, starts := pagedServer(t, "StartIndex", "{}", 2)
	result, err := c.GetShowsNextUpComplete(t.Context(), GetShowsNextUpOperationOptions{Limit: 1})
	if err != nil {
		t.Fatal(err)
	}
	// a page of one from the start, then from the first item, then the total is reached
	if len(result.Items) != 2 || !slices.Equal(*starts, []string{"", "1"}) || result.LatestHttpResponse == nil {
		t.Errorf("Complete = %d items over pages starting %q", len(result.Items), *starts)
	}
}
