// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostUsersByIdDeleteOperationResponse is the result of PostUsersByIdDelete.
type PostUsersByIdDeleteOperationResponse struct {
	HttpResponse *http.Response
}

// PostUsersByIdDelete calls POST /Users/{Id}/Delete. Deletes a user.
func (c Client) PostUsersByIdDelete(ctx context.Context, id string) (result PostUsersByIdDeleteOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodPost,
		Path:       fmt.Sprintf("/Users/%s/Delete", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
