// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetUsersItemAccessOperationResponse is the result of GetUsersItemAccess.
type GetUsersItemAccessOperationResponse struct {
	HttpResponse *http.Response
	Model        *QueryResultUserDto
}

// GetUsersItemAccessOperationOptions holds the query and header parameters of GetUsersItemAccess.
type GetUsersItemAccessOperationOptions struct {
	// Optional filter by IsHidden=true or false
	IsHidden *bool

	// Optional filter by IsDisabled=true or false
	IsDisabled *bool

	// Optional. The record index to start at. All items with a lower index will be dropped from the results.
	StartIndex *int

	// Optional. The maximum number of records to return
	Limit *int

	// Optional filter by items whose name is sorted equally or greater than a given input string.
	NameStartsWithOrGreater string

	// Sort Order - Ascending,Descending
	SortOrder string
}

// ToHeaders returns the header parameters the options set.
func (o GetUsersItemAccessOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetUsersItemAccessOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.IsHidden != nil {
		out.Append("IsHidden", strconv.FormatBool(*o.IsHidden))
	}
	if o.IsDisabled != nil {
		out.Append("IsDisabled", strconv.FormatBool(*o.IsDisabled))
	}
	if o.StartIndex != nil {
		out.Append("StartIndex", strconv.Itoa(*o.StartIndex))
	}
	if o.Limit != nil {
		out.Append("Limit", strconv.Itoa(*o.Limit))
	}
	if o.NameStartsWithOrGreater != "" {
		out.Append("NameStartsWithOrGreater", o.NameStartsWithOrGreater)
	}
	if o.SortOrder != "" {
		out.Append("SortOrder", o.SortOrder)
	}
	return &out
}

// GetUsersItemAccess calls GET /Users/ItemAccess. Gets a list of users.
func (c Client) GetUsersItemAccess(ctx context.Context, options GetUsersItemAccessOperationOptions) (result GetUsersItemAccessOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/Users/ItemAccess",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model QueryResultUserDto
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}

// GetUsersItemAccessCompleteResult is every result GetUsersItemAccessComplete loaded.
type GetUsersItemAccessCompleteResult struct {
	LatestHttpResponse *http.Response
	Items              []UserDto
}

// GetUsersItemAccessComplete calls GetUsersItemAccess page by page from options.StartIndex until every
// result is loaded. options.Limit is the page size, client.DefaultPageSize when
// unset.
func (c Client) GetUsersItemAccessComplete(ctx context.Context, options GetUsersItemAccessOperationOptions) (result GetUsersItemAccessCompleteResult, err error) {
	limit := client.DefaultPageSize
	if options.Limit != nil && *options.Limit > 0 {
		limit = *options.Limit
	}
	options.Limit = &limit
	start := 0
	if options.StartIndex != nil {
		start = *options.StartIndex
	}
	for {
		var page GetUsersItemAccessOperationResponse
		page, err = c.GetUsersItemAccess(ctx, options)
		result.LatestHttpResponse = page.HttpResponse
		if err != nil {
			err = fmt.Errorf("loading results: %w", err)
			return
		}
		if page.Model == nil || len(page.Model.Items) == 0 {
			return
		}
		result.Items = append(result.Items, page.Model.Items...)
		start += len(page.Model.Items)
		options.StartIndex = &start
		// a short page is the last; so is reaching the total, when the server
		// reports one (some Emby lists report 0 whatever they hold)
		if len(page.Model.Items) < limit || page.Model.TotalRecordCount > 0 && start >= page.Model.TotalRecordCount {
			return
		}
	}
}
