// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// UserNotificationInfo is the "UserNotificationInfo" schema.
type UserNotificationInfo struct {
	DeviceIds          []string          `json:"DeviceIds,omitzero"`
	Enabled            *bool             `json:"Enabled,omitempty"`
	EventIds           []string          `json:"EventIds,omitzero"`
	FriendlyName       string            `json:"FriendlyName,omitempty"`
	GroupItems         *bool             `json:"GroupItems,omitempty"`
	Id                 string            `json:"Id,omitempty"`
	IsSelfNotification *bool             `json:"IsSelfNotification,omitempty"`
	LibraryIds         []string          `json:"LibraryIds,omitzero"`
	NotifierKey        string            `json:"NotifierKey,omitempty"`
	Options            map[string]string `json:"Options,omitzero"`
	PluginId           string            `json:"PluginId,omitempty"`
	ServiceName        string            `json:"ServiceName,omitempty"`
	SetupModuleUrl     string            `json:"SetupModuleUrl,omitempty"`
	UserId             string            `json:"UserId,omitempty"`
	UserIds            []string          `json:"UserIds,omitzero"`
}
