// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetUsersCopyDataOptionsOperationResponse is the result of GetUsersCopyDataOptions.
type GetUsersCopyDataOptionsOperationResponse struct {
	HttpResponse *http.Response
	Model        *LibraryFullUserCopyDataOptions
}

// GetUsersCopyDataOptions calls GET /Users/CopyDataOptions. Gets copy data options.
func (c Client) GetUsersCopyDataOptions(ctx context.Context) (result GetUsersCopyDataOptionsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodGet,
		Path:       "/Users/CopyDataOptions",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model LibraryFullUserCopyDataOptions
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
