// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetNotificationsServicesDefaultsOperationResponse is the result of GetNotificationsServicesDefaults.
type GetNotificationsServicesDefaultsOperationResponse struct {
	HttpResponse *http.Response
	Model        *UserNotificationInfo
}

// GetNotificationsServicesDefaults calls GET /Notifications/Services/Defaults. Gets default notification info.
func (c Client) GetNotificationsServicesDefaults(ctx context.Context) (result GetNotificationsServicesDefaultsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod: http.MethodGet,
		Path:       "/Notifications/Services/Defaults",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model UserNotificationInfo
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
