// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostUsersNewOperationResponse is the result of PostUsersNew.
type PostUsersNewOperationResponse struct {
	HttpResponse *http.Response
	Model        *UserDto
}

// PostUsersNew calls POST /Users/New. Creates a user.
func (c Client) PostUsersNew(ctx context.Context, input CreateUserByName) (result PostUsersNewOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod: http.MethodPost,
		Path:       "/Users/New",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model UserDto
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
