// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// DeleteUsersByUserIdFavoriteItemsByIdOperationResponse is the result of DeleteUsersByUserIdFavoriteItemsById.
type DeleteUsersByUserIdFavoriteItemsByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *UserItemDataDto
}

// DeleteUsersByUserIdFavoriteItemsById calls DELETE /Users/{UserId}/FavoriteItems/{Id}. Unmarks an item as a favorite.
func (c Client) DeleteUsersByUserIdFavoriteItemsById(ctx context.Context, userId string, id string) (result DeleteUsersByUserIdFavoriteItemsByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodDelete,
		Path:       fmt.Sprintf("/Users/%s/FavoriteItems/%s", url.PathEscape(userId), url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model UserItemDataDto
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
