// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostUsersByUserIdSearchedItemsOperationResponse is the result of PostUsersByUserIdSearchedItems.
type PostUsersByUserIdSearchedItemsOperationResponse struct {
	HttpResponse *http.Response
}

// PostUsersByUserIdSearchedItems calls POST /Users/{UserId}/SearchedItems/. Marks an item as a favorite.
func (c Client) PostUsersByUserIdSearchedItems(ctx context.Context, userId string, input UserLibraryReportItemsSearched) (result PostUsersByUserIdSearchedItemsOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodPost,
		Path:       fmt.Sprintf("/Users/%s/SearchedItems/", url.PathEscape(userId)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
