// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostNotificationsServicesTestOperationResponse is the result of PostNotificationsServicesTest.
type PostNotificationsServicesTestOperationResponse struct {
	HttpResponse *http.Response
}

// PostNotificationsServicesTest calls POST /Notifications/Services/Test. Sends a test notification.
func (c Client) PostNotificationsServicesTest(ctx context.Context, input UserNotificationInfo) (result PostNotificationsServicesTestOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod: http.MethodPost,
		Path:       "/Notifications/Services/Test",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
