// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostUsersByIdAuthenticateOperationResponse is the result of PostUsersByIdAuthenticate.
type PostUsersByIdAuthenticateOperationResponse struct {
	HttpResponse *http.Response
	Model        *AuthenticationAuthenticationResult
}

// PostUsersByIdAuthenticate calls POST /Users/{Id}/Authenticate. Authenticates a user.
func (c Client) PostUsersByIdAuthenticate(ctx context.Context, id string, input AuthenticateUser) (result PostUsersByIdAuthenticateOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HttpMethod: http.MethodPost,
		Path:       fmt.Sprintf("/Users/%s/Authenticate", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model AuthenticationAuthenticationResult
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
