// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostUsersByUserIdItemsByIdHideFromResumeOperationResponse is the result of PostUsersByUserIdItemsByIdHideFromResume.
type PostUsersByUserIdItemsByIdHideFromResumeOperationResponse struct {
	HttpResponse *http.Response
	Model        *UserItemDataDto
}

// PostUsersByUserIdItemsByIdHideFromResumeOperationOptions holds the query and header parameters of PostUsersByUserIdItemsByIdHideFromResume.
type PostUsersByUserIdItemsByIdHideFromResumeOperationOptions struct {
	// Whether the item should be hidden from reusme or not. true/false
	Hide *bool
}

// ToHeaders returns the header parameters the options set.
func (o PostUsersByUserIdItemsByIdHideFromResumeOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PostUsersByUserIdItemsByIdHideFromResumeOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Hide != nil {
		out.Append("Hide", strconv.FormatBool(*o.Hide))
	}
	return &out
}

// PostUsersByUserIdItemsByIdHideFromResume calls POST /Users/{UserId}/Items/{Id}/HideFromResume. Updates a user's hide from resume for an item.
func (c Client) PostUsersByUserIdItemsByIdHideFromResume(ctx context.Context, userId string, id string, options PostUsersByUserIdItemsByIdHideFromResumeOperationOptions) (result PostUsersByUserIdItemsByIdHideFromResumeOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          fmt.Sprintf("/Users/%s/Items/%s/HideFromResume", url.PathEscape(userId), url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if resp.StatusCode == http.StatusNoContent {
		return
	}

	var model UserItemDataDto
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
