// Code generated by internal/pandorest; DO NOT EDIT.

package emby

// AuthenticateUserByName is the "AuthenticateUserByName" schema.
type AuthenticateUserByName struct {
	Pw       string `json:"Pw,omitempty"`
	Username string `json:"Username,omitempty"`
}
