// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"encoding/json"
	"net/http"
	"testing"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

func TestOperationPostItemsAccess(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "", "")
	result, err := c.PostItemsAccess(t.Context(), UserLibraryUpdateUserItemAccess{})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodPost, "/Items/Access")
	if got := r.Header.Get("Content-Type"); got != "application/json" {
		t.Errorf("Content-Type = %q, want %q", got, "application/json")
	}
	if !json.Valid([]byte(body)) {
		t.Errorf("body = %q, want JSON", body)
	}
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.PostItemsAccess(t.Context(), UserLibraryUpdateUserItemAccess{})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
