// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostVideosByIdAlternateSourcesDeleteOperationResponse is the result of PostVideosByIdAlternateSourcesDelete.
type PostVideosByIdAlternateSourcesDeleteOperationResponse struct {
	HttpResponse *http.Response
}

// PostVideosByIdAlternateSourcesDelete calls POST /Videos/{Id}/AlternateSources/Delete. Removes alternate video sources.
func (c Client) PostVideosByIdAlternateSourcesDelete(ctx context.Context, id string) (result PostVideosByIdAlternateSourcesDeleteOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodPost,
		Path:       fmt.Sprintf("/Videos/%s/AlternateSources/Delete", url.PathEscape(id)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
