// Code generated by internal/pandorest; DO NOT EDIT.

package emby

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetAudioByIdHlsByPlaylistIdBySegmentIdBySegmentContainerOperationResponse is the result of GetAudioByIdHlsByPlaylistIdBySegmentIdBySegmentContainer.
//
// The operation answers application/octet-stream, left unread in HttpResponse.Body, which
// the caller must close.
type GetAudioByIdHlsByPlaylistIdBySegmentIdBySegmentContainerOperationResponse struct {
	HttpResponse *http.Response
}

// GetAudioByIdHlsByPlaylistIdBySegmentIdBySegmentContainer calls GET /Audio/{Id}/hls/{PlaylistId}/{SegmentId}.{SegmentContainer}. Requires authentication as user.
func (c Client) GetAudioByIdHlsByPlaylistIdBySegmentIdBySegmentContainer(ctx context.Context, id string, playlistId string, segmentId string, segmentContainer string) (result GetAudioByIdHlsByPlaylistIdBySegmentIdBySegmentContainerOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:     http.MethodGet,
		Path:           fmt.Sprintf("/Audio/%s/hls/%s/%s.%s", url.PathEscape(id), url.PathEscape(playlistId), url.PathEscape(segmentId), url.PathEscape(segmentContainer)),
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
