// Code generated by sdk/pandorest; DO NOT EDIT.

package jf

// MetadataConfiguration is the "MetadataConfiguration" schema.
type MetadataConfiguration struct {
	UseFileCreationTimeForDateAdded *bool `json:"UseFileCreationTimeForDateAdded,omitempty"`
}
