// Code generated by sdk/pandorest; DO NOT EDIT.

package jf

// PlaylistCreationResult is the "PlaylistCreationResult" schema.
type PlaylistCreationResult struct {
	Id string `json:"Id,omitempty"`
}
