// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// AccountAddFavoriteResponse is an object the document declares inline.
type AccountAddFavoriteResponse struct {
	StatusCode    int    `json:"status_code,omitempty"`
	StatusMessage string `json:"status_message,omitempty"`
}
