// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// AccountDetailsResponse is an object the document declares inline.
type AccountDetailsResponse struct {
	Avatar       *AccountDetailsResponseAvatar `json:"avatar,omitempty"`
	Id           int                           `json:"id,omitempty"`
	IncludeAdult *bool                         `json:"include_adult,omitempty"`
	Iso31661     string                        `json:"iso_3166_1,omitempty"`
	Iso6391      string                        `json:"iso_639_1,omitempty"`
	Name         string                        `json:"name,omitempty"`
	Username     string                        `json:"username,omitempty"`
}
