// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// AccountAddToWatchlistRequest is an object the document declares inline.
type AccountAddToWatchlistRequest struct {
	MediaId   int    `json:"media_id,omitempty"`
	MediaType string `json:"media_type,omitempty"`
	Watchlist *bool  `json:"watchlist,omitempty"`
}
