// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// AuthenticationCreateSessionFromLoginOperationResponse is the result of AuthenticationCreateSessionFromLogin.
type AuthenticationCreateSessionFromLoginOperationResponse struct {
	HttpResponse *http.Response
	Model        *AuthenticationCreateSessionFromLoginResponse
}

// AuthenticationCreateSessionFromLogin calls POST /3/authentication/token/validate_with_login. Create Session (with login).
func (c Client) AuthenticationCreateSessionFromLogin(ctx context.Context, input AuthenticationCreateSessionFromLoginRequest) (result AuthenticationCreateSessionFromLoginOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodPost,
		Path:       "/3/authentication/token/validate_with_login",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model AuthenticationCreateSessionFromLoginResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
