// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// AuthenticationCreateSessionResponse is an object the document declares inline.
type AuthenticationCreateSessionResponse struct {
	SessionId string `json:"session_id,omitempty"`
	Success   *bool  `json:"success,omitempty"`
}
