// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// AuthenticationCreateSessionFromV4TokenResponse is an object the document declares inline.
type AuthenticationCreateSessionFromV4TokenResponse struct {
	SessionId string `json:"session_id,omitempty"`
	Success   *bool  `json:"success,omitempty"`
}
