// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// AuthenticationCreateSessionFromV4TokenRequest is an object the document declares inline.
type AuthenticationCreateSessionFromV4TokenRequest struct {
	AccessToken string `json:"access_token,omitempty"`
}
