// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// CertificationsTvListResponseCertificationsKR is an object the document declares inline.
type CertificationsTvListResponseCertificationsKR struct {
	Certification string `json:"certification,omitempty"`
	Meaning       string `json:"meaning,omitempty"`
	Order         int    `json:"order,omitempty"`
}
