// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// CertificationMovieListResponseCertificationsNL is an object the document declares inline.
type CertificationMovieListResponseCertificationsNL struct {
	Certification string `json:"certification,omitempty"`
	Meaning       string `json:"meaning,omitempty"`
	Order         int    `json:"order,omitempty"`
}
