// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// CollectionTranslationsOperationResponse is the result of CollectionTranslations.
type CollectionTranslationsOperationResponse struct {
	HttpResponse *http.Response
	Model        *CollectionTranslationsResponse
}

// CollectionTranslations calls GET /3/collection/{collection_id}/translations. Translations.
func (c Client) CollectionTranslations(ctx context.Context, collectionId int) (result CollectionTranslationsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod: http.MethodGet,
		Path:       fmt.Sprintf("/3/collection/%d/translations", collectionId),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model CollectionTranslationsResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
