// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// CompanyDetailsOperationResponse is the result of CompanyDetails.
type CompanyDetailsOperationResponse struct {
	HttpResponse *http.Response
	Model        *CompanyDetailsResponse
}

// CompanyDetails calls GET /3/company/{company_id}. Details.
func (c Client) CompanyDetails(ctx context.Context, companyId int) (result CompanyDetailsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/3/company/%d", companyId),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model CompanyDetailsResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
