// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// ConfigurationDetailsOperationResponse is the result of ConfigurationDetails.
type ConfigurationDetailsOperationResponse struct {
	HttpResponse *http.Response
	Model        *ConfigurationDetailsResponse
}

// ConfigurationDetails calls GET /3/configuration. Details.
func (c Client) ConfigurationDetails(ctx context.Context) (result ConfigurationDetailsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/3/configuration",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model ConfigurationDetailsResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
