// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// ConfigurationJobsOperationResponse is the result of ConfigurationJobs.
type ConfigurationJobsOperationResponse struct {
	HttpResponse *http.Response
	Model        []ConfigurationJobsResponse
}

// ConfigurationJobs calls GET /3/configuration/jobs. Jobs.
func (c Client) ConfigurationJobs(ctx context.Context) (result ConfigurationJobsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod: http.MethodGet,
		Path:       "/3/configuration/jobs",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
