// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"net/http"
	"testing"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

func TestOperationDiscoverTv(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "application/json", "{}")
	result, err := c.DiscoverTv(t.Context(), DiscoverTvOperationOptions{
		AirDateGte:                 "v-AirDateGte",
		AirDateLte:                 "v-AirDateLte",
		FirstAirDateYear:           new(7),
		FirstAirDateGte:            "v-FirstAirDateGte",
		FirstAirDateLte:            "v-FirstAirDateLte",
		IncludeAdult:               new(true),
		IncludeNullFirstAirDates:   new(true),
		Language:                   "v-Language",
		Page:                       new(7),
		ScreenedTheatrically:       new(true),
		SortBy:                     "v-SortBy",
		Timezone:                   "v-Timezone",
		VoteAverageGte:             new(1.5),
		VoteAverageLte:             new(1.5),
		VoteCountGte:               new(1.5),
		VoteCountLte:               new(1.5),
		WatchRegion:                "v-WatchRegion",
		WithCompanies:              "v-WithCompanies",
		WithGenres:                 "v-WithGenres",
		WithKeywords:               "v-WithKeywords",
		WithNetworks:               new(7),
		WithOriginCountry:          "v-WithOriginCountry",
		WithOriginalLanguage:       "v-WithOriginalLanguage",
		WithRuntimeGte:             new(7),
		WithRuntimeLte:             new(7),
		WithStatus:                 "v-WithStatus",
		WithWatchMonetizationTypes: "v-WithWatchMonetizationTypes",
		WithWatchProviders:         "v-WithWatchProviders",
		WithoutCompanies:           "v-WithoutCompanies",
		WithoutGenres:              "v-WithoutGenres",
		WithoutKeywords:            "v-WithoutKeywords",
		WithoutWatchProviders:      "v-WithoutWatchProviders",
		WithType:                   "v-WithType",
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/3/discover/tv")
	expectQuery(t, r, "air_date.gte", "v-AirDateGte")
	expectQuery(t, r, "air_date.lte", "v-AirDateLte")
	expectQuery(t, r, "first_air_date_year", "7")
	expectQuery(t, r, "first_air_date.gte", "v-FirstAirDateGte")
	expectQuery(t, r, "first_air_date.lte", "v-FirstAirDateLte")
	expectQuery(t, r, "include_adult", "true")
	expectQuery(t, r, "include_null_first_air_dates", "true")
	expectQuery(t, r, "language", "v-Language")
	expectQuery(t, r, "page", "7")
	expectQuery(t, r, "screened_theatrically", "true")
	expectQuery(t, r, "sort_by", "v-SortBy")
	expectQuery(t, r, "timezone", "v-Timezone")
	expectQuery(t, r, "vote_average.gte", "1.5")
	expectQuery(t, r, "vote_average.lte", "1.5")
	expectQuery(t, r, "vote_count.gte", "1.5")
	expectQuery(t, r, "vote_count.lte", "1.5")
	expectQuery(t, r, "watch_region", "v-WatchRegion")
	expectQuery(t, r, "with_companies", "v-WithCompanies")
	expectQuery(t, r, "with_genres", "v-WithGenres")
	expectQuery(t, r, "with_keywords", "v-WithKeywords")
	expectQuery(t, r, "with_networks", "7")
	expectQuery(t, r, "with_origin_country", "v-WithOriginCountry")
	expectQuery(t, r, "with_original_language", "v-WithOriginalLanguage")
	expectQuery(t, r, "with_runtime.gte", "7")
	expectQuery(t, r, "with_runtime.lte", "7")
	expectQuery(t, r, "with_status", "v-WithStatus")
	expectQuery(t, r, "with_watch_monetization_types", "v-WithWatchMonetizationTypes")
	expectQuery(t, r, "with_watch_providers", "v-WithWatchProviders")
	expectQuery(t, r, "without_companies", "v-WithoutCompanies")
	expectQuery(t, r, "without_genres", "v-WithoutGenres")
	expectQuery(t, r, "without_keywords", "v-WithoutKeywords")
	expectQuery(t, r, "without_watch_providers", "v-WithoutWatchProviders")
	expectQuery(t, r, "with_type", "v-WithType")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	if result.Model == nil {
		t.Error("the model was not decoded")
	}

	// an answer that does not decode is an error, with the response
	c, _ = newOperationServer(t, 200, "application/json", "<html>")
	result, err = c.DiscoverTv(t.Context(), DiscoverTvOperationOptions{
		AirDateGte:                 "v-AirDateGte",
		AirDateLte:                 "v-AirDateLte",
		FirstAirDateYear:           new(7),
		FirstAirDateGte:            "v-FirstAirDateGte",
		FirstAirDateLte:            "v-FirstAirDateLte",
		IncludeAdult:               new(true),
		IncludeNullFirstAirDates:   new(true),
		Language:                   "v-Language",
		Page:                       new(7),
		ScreenedTheatrically:       new(true),
		SortBy:                     "v-SortBy",
		Timezone:                   "v-Timezone",
		VoteAverageGte:             new(1.5),
		VoteAverageLte:             new(1.5),
		VoteCountGte:               new(1.5),
		VoteCountLte:               new(1.5),
		WatchRegion:                "v-WatchRegion",
		WithCompanies:              "v-WithCompanies",
		WithGenres:                 "v-WithGenres",
		WithKeywords:               "v-WithKeywords",
		WithNetworks:               new(7),
		WithOriginCountry:          "v-WithOriginCountry",
		WithOriginalLanguage:       "v-WithOriginalLanguage",
		WithRuntimeGte:             new(7),
		WithRuntimeLte:             new(7),
		WithStatus:                 "v-WithStatus",
		WithWatchMonetizationTypes: "v-WithWatchMonetizationTypes",
		WithWatchProviders:         "v-WithWatchProviders",
		WithoutCompanies:           "v-WithoutCompanies",
		WithoutGenres:              "v-WithoutGenres",
		WithoutKeywords:            "v-WithoutKeywords",
		WithoutWatchProviders:      "v-WithoutWatchProviders",
		WithType:                   "v-WithType",
	})
	if err == nil || client.StatusCode(err) != 0 || result.HttpResponse == nil {
		t.Errorf("an answer that does not decode = %v", err)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.DiscoverTv(t.Context(), DiscoverTvOperationOptions{
		AirDateGte:                 "v-AirDateGte",
		AirDateLte:                 "v-AirDateLte",
		FirstAirDateYear:           new(7),
		FirstAirDateGte:            "v-FirstAirDateGte",
		FirstAirDateLte:            "v-FirstAirDateLte",
		IncludeAdult:               new(true),
		IncludeNullFirstAirDates:   new(true),
		Language:                   "v-Language",
		Page:                       new(7),
		ScreenedTheatrically:       new(true),
		SortBy:                     "v-SortBy",
		Timezone:                   "v-Timezone",
		VoteAverageGte:             new(1.5),
		VoteAverageLte:             new(1.5),
		VoteCountGte:               new(1.5),
		VoteCountLte:               new(1.5),
		WatchRegion:                "v-WatchRegion",
		WithCompanies:              "v-WithCompanies",
		WithGenres:                 "v-WithGenres",
		WithKeywords:               "v-WithKeywords",
		WithNetworks:               new(7),
		WithOriginCountry:          "v-WithOriginCountry",
		WithOriginalLanguage:       "v-WithOriginalLanguage",
		WithRuntimeGte:             new(7),
		WithRuntimeLte:             new(7),
		WithStatus:                 "v-WithStatus",
		WithWatchMonetizationTypes: "v-WithWatchMonetizationTypes",
		WithWatchProviders:         "v-WithWatchProviders",
		WithoutCompanies:           "v-WithoutCompanies",
		WithoutGenres:              "v-WithoutGenres",
		WithoutKeywords:            "v-WithoutKeywords",
		WithoutWatchProviders:      "v-WithoutWatchProviders",
		WithType:                   "v-WithType",
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
