// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// FindByIdResponseTvSeasonResults is an object the document declares inline.
type FindByIdResponseTvSeasonResults struct {
	AirDate      string `json:"air_date,omitempty"`
	EpisodeCount int    `json:"episode_count,omitempty"`
	Id           int    `json:"id,omitempty"`
	Name         string `json:"name,omitempty"`
	Overview     string `json:"overview,omitempty"`
	PosterPath   string `json:"poster_path,omitempty"`
	SeasonNumber int    `json:"season_number,omitempty"`
	ShowId       int    `json:"show_id,omitempty"`
}
