// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// FindByIdResponse is an object the document declares inline.
type FindByIdResponse struct {
	MovieResults     []FindByIdResponseMovieResults     `json:"movie_results,omitzero"`
	PersonResults    []FindByIdResponsePersonResults    `json:"person_results,omitzero"`
	TvEpisodeResults []FindByIdResponseTvEpisodeResults `json:"tv_episode_results,omitzero"`
	TvResults        []FindByIdResponseTvResults        `json:"tv_results,omitzero"`
	TvSeasonResults  []FindByIdResponseTvSeasonResults  `json:"tv_season_results,omitzero"`
}
