// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// GenreTvListResponseGenres is an object the document declares inline.
type GenreTvListResponseGenres struct {
	Id   int    `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
