// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// GenreMovieListResponse is an object the document declares inline.
type GenreMovieListResponse struct {
	Genres []GenreMovieListResponseGenres `json:"genres,omitzero"`
}
