// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// GenreMovieListResponseGenres is an object the document declares inline.
type GenreMovieListResponseGenres struct {
	Id   int    `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
