// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GuestSessionRatedTvOperationResponse is the result of GuestSessionRatedTv.
type GuestSessionRatedTvOperationResponse struct {
	HttpResponse *http.Response
	Model        *GuestSessionRatedTvResponse
}

// GuestSessionRatedTvOperationOptions holds the query and header parameters of GuestSessionRatedTv.
type GuestSessionRatedTvOperationOptions struct {
	Language string
	Page     *int
	SortBy   string
}

// ToHeaders returns the header parameters the options set.
func (o GuestSessionRatedTvOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GuestSessionRatedTvOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Language != "" {
		out.Append("language", o.Language)
	}
	if o.Page != nil {
		out.Append("page", strconv.Itoa(*o.Page))
	}
	if o.SortBy != "" {
		out.Append("sort_by", o.SortBy)
	}
	return &out
}

// GuestSessionRatedTv calls GET /3/guest_session/{guest_session_id}/rated/tv. Rated TV.
func (c Client) GuestSessionRatedTv(ctx context.Context, guestSessionId string, options GuestSessionRatedTvOperationOptions) (result GuestSessionRatedTvOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          fmt.Sprintf("/3/guest_session/%s/rated/tv", url.PathEscape(guestSessionId)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model GuestSessionRatedTvResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
