// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// ListCheckItemStatusOperationResponse is the result of ListCheckItemStatus.
type ListCheckItemStatusOperationResponse struct {
	HttpResponse *http.Response
	Model        *ListCheckItemStatusResponse
}

// ListCheckItemStatusOperationOptions holds the query and header parameters of ListCheckItemStatus.
type ListCheckItemStatusOperationOptions struct {
	Language string
	MovieId  *int
}

// ToHeaders returns the header parameters the options set.
func (o ListCheckItemStatusOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o ListCheckItemStatusOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Language != "" {
		out.Append("language", o.Language)
	}
	if o.MovieId != nil {
		out.Append("movie_id", strconv.Itoa(*o.MovieId))
	}
	return &out
}

// ListCheckItemStatus calls GET /3/list/{list_id}/item_status. Check Item Status.
func (c Client) ListCheckItemStatus(ctx context.Context, listId int, options ListCheckItemStatusOperationOptions) (result ListCheckItemStatusOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          fmt.Sprintf("/3/list/%d/item_status", listId),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model ListCheckItemStatusResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
