// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// ListCreateRequest is an object the document declares inline.
type ListCreateRequest struct {
	Description string `json:"description,omitempty"`
	Language    string `json:"language,omitempty"`
	Name        string `json:"name,omitempty"`
}
