// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieWatchProvidersResponseResultsMZ is an object the document declares inline.
type MovieWatchProvidersResponseResultsMZ struct {
	Buy  []MovieWatchProvidersResponseResultsMZBuy  `json:"buy,omitzero"`
	Link string                                     `json:"link,omitempty"`
	Rent []MovieWatchProvidersResponseResultsMZRent `json:"rent,omitzero"`
}
