// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieWatchProvidersResponseResultsLI is an object the document declares inline.
type MovieWatchProvidersResponseResultsLI struct {
	Flatrate []MovieWatchProvidersResponseResultsLIFlatrate `json:"flatrate,omitzero"`
	Link     string                                         `json:"link,omitempty"`
}
