// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieChangesResponse is an object the document declares inline.
type MovieChangesResponse struct {
	Changes []MovieChangesResponseChanges `json:"changes,omitzero"`
}
