// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieWatchProvidersResponseResultsGF is an object the document declares inline.
type MovieWatchProvidersResponseResultsGF struct {
	Flatrate []MovieWatchProvidersResponseResultsGFFlatrate `json:"flatrate,omitzero"`
	Link     string                                         `json:"link,omitempty"`
}
