// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieWatchProvidersResponseResultsLT is an object the document declares inline.
type MovieWatchProvidersResponseResultsLT struct {
	Buy      []MovieWatchProvidersResponseResultsLTBuy      `json:"buy,omitzero"`
	Flatrate []MovieWatchProvidersResponseResultsLTFlatrate `json:"flatrate,omitzero"`
	Link     string                                         `json:"link,omitempty"`
	Rent     []MovieWatchProvidersResponseResultsLTRent     `json:"rent,omitzero"`
}
