// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieWatchProvidersResponseResultsNZ is an object the document declares inline.
type MovieWatchProvidersResponseResultsNZ struct {
	Buy      []MovieWatchProvidersResponseResultsNZBuy      `json:"buy,omitzero"`
	Flatrate []MovieWatchProvidersResponseResultsNZFlatrate `json:"flatrate,omitzero"`
	Link     string                                         `json:"link,omitempty"`
}
