// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieWatchProvidersResponseResultsSARent is an object the document declares inline.
type MovieWatchProvidersResponseResultsSARent struct {
	DisplayPriority int    `json:"display_priority,omitempty"`
	LogoPath        string `json:"logo_path,omitempty"`
	ProviderId      int    `json:"provider_id,omitempty"`
	ProviderName    string `json:"provider_name,omitempty"`
}
