// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieWatchProvidersResponseResultsKR is an object the document declares inline.
type MovieWatchProvidersResponseResultsKR struct {
	Buy      []MovieWatchProvidersResponseResultsKRBuy      `json:"buy,omitzero"`
	Flatrate []MovieWatchProvidersResponseResultsKRFlatrate `json:"flatrate,omitzero"`
	Link     string                                         `json:"link,omitempty"`
}
