// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieChangesResponseChangesItemsValue is an object the document declares inline.
type MovieChangesResponseChangesItemsValue struct {
	Poster *MovieChangesResponseChangesItemsValuePoster `json:"poster,omitempty"`
}
