// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieWatchProvidersResponseResultsPL is an object the document declares inline.
type MovieWatchProvidersResponseResultsPL struct {
	Buy      []MovieWatchProvidersResponseResultsPLBuy      `json:"buy,omitzero"`
	Flatrate []MovieWatchProvidersResponseResultsPLFlatrate `json:"flatrate,omitzero"`
	Link     string                                         `json:"link,omitempty"`
	Rent     []MovieWatchProvidersResponseResultsPLRent     `json:"rent,omitzero"`
}
