// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieWatchProvidersResponseResultsIQ is an object the document declares inline.
type MovieWatchProvidersResponseResultsIQ struct {
	Flatrate []MovieWatchProvidersResponseResultsIQFlatrate `json:"flatrate,omitzero"`
	Link     string                                         `json:"link,omitempty"`
}
