// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieWatchProvidersResponseResultsFR is an object the document declares inline.
type MovieWatchProvidersResponseResultsFR struct {
	Buy      []MovieWatchProvidersResponseResultsFRBuy      `json:"buy,omitzero"`
	Flatrate []MovieWatchProvidersResponseResultsFRFlatrate `json:"flatrate,omitzero"`
	Link     string                                         `json:"link,omitempty"`
	Rent     []MovieWatchProvidersResponseResultsFRRent     `json:"rent,omitzero"`
}
