// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieKeywordsResponse is an object the document declares inline.
type MovieKeywordsResponse struct {
	Id       int                             `json:"id,omitempty"`
	Keywords []MovieKeywordsResponseKeywords `json:"keywords,omitzero"`
}
