// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// MovieDeleteRatingOperationResponse is the result of MovieDeleteRating.
type MovieDeleteRatingOperationResponse struct {
	HttpResponse *http.Response
	Model        *MovieDeleteRatingResponse
}

// MovieDeleteRatingOperationOptions holds the query and header parameters of MovieDeleteRating.
type MovieDeleteRatingOperationOptions struct {
	GuestSessionId string
	SessionId      string
}

// ToHeaders returns the header parameters the options set.
func (o MovieDeleteRatingOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o MovieDeleteRatingOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.GuestSessionId != "" {
		out.Append("guest_session_id", o.GuestSessionId)
	}
	if o.SessionId != "" {
		out.Append("session_id", o.SessionId)
	}
	return &out
}

// MovieDeleteRating calls DELETE /3/movie/{movie_id}/rating. Delete Rating.
func (c Client) MovieDeleteRating(ctx context.Context, movieId int, options MovieDeleteRatingOperationOptions) (result MovieDeleteRatingOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod:    http.MethodDelete,
		OptionsObject: options,
		Path:          fmt.Sprintf("/3/movie/%d/rating", movieId),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model MovieDeleteRatingResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
