// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieWatchProvidersResponseResultsJO is an object the document declares inline.
type MovieWatchProvidersResponseResultsJO struct {
	Buy      []MovieWatchProvidersResponseResultsJOBuy      `json:"buy,omitzero"`
	Flatrate []MovieWatchProvidersResponseResultsJOFlatrate `json:"flatrate,omitzero"`
	Link     string                                         `json:"link,omitempty"`
}
