// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieWatchProvidersResponseResultsUG is an object the document declares inline.
type MovieWatchProvidersResponseResultsUG struct {
	Buy  []MovieWatchProvidersResponseResultsUGBuy  `json:"buy,omitzero"`
	Link string                                     `json:"link,omitempty"`
	Rent []MovieWatchProvidersResponseResultsUGRent `json:"rent,omitzero"`
}
