// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// MovieVideosOperationResponse is the result of MovieVideos.
type MovieVideosOperationResponse struct {
	HttpResponse *http.Response
	Model        *MovieVideosResponse
}

// MovieVideosOperationOptions holds the query and header parameters of MovieVideos.
type MovieVideosOperationOptions struct {
	Language string
}

// ToHeaders returns the header parameters the options set.
func (o MovieVideosOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o MovieVideosOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Language != "" {
		out.Append("language", o.Language)
	}
	return &out
}

// MovieVideos calls GET /3/movie/{movie_id}/videos. Videos.
func (c Client) MovieVideos(ctx context.Context, movieId int, options MovieVideosOperationOptions) (result MovieVideosOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          fmt.Sprintf("/3/movie/%d/videos", movieId),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model MovieVideosResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
