// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieWatchProvidersResponseResultsSV is an object the document declares inline.
type MovieWatchProvidersResponseResultsSV struct {
	Flatrate []MovieWatchProvidersResponseResultsSVFlatrate `json:"flatrate,omitzero"`
	Link     string                                         `json:"link,omitempty"`
}
