// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieKeywordsResponseKeywords is an object the document declares inline.
type MovieKeywordsResponseKeywords struct {
	Id   int    `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
