// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieWatchProvidersResponseResultsYE is an object the document declares inline.
type MovieWatchProvidersResponseResultsYE struct {
	Flatrate []MovieWatchProvidersResponseResultsYEFlatrate `json:"flatrate,omitzero"`
	Link     string                                         `json:"link,omitempty"`
}
