// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// MovieExternalIdsOperationResponse is the result of MovieExternalIds.
type MovieExternalIdsOperationResponse struct {
	HttpResponse *http.Response
	Model        *MovieExternalIdsResponse
}

// MovieExternalIds calls GET /3/movie/{movie_id}/external_ids. External IDs.
func (c Client) MovieExternalIds(ctx context.Context, movieId int) (result MovieExternalIdsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod: http.MethodGet,
		Path:       fmt.Sprintf("/3/movie/%d/external_ids", movieId),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model MovieExternalIdsResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
