// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieSimilarResponse is an object the document declares inline.
type MovieSimilarResponse struct {
	Page         int                           `json:"page,omitempty"`
	Results      []MovieSimilarResponseResults `json:"results,omitzero"`
	TotalPages   int                           `json:"total_pages,omitempty"`
	TotalResults int                           `json:"total_results,omitempty"`
}
