// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieWatchProvidersResponseResultsDO is an object the document declares inline.
type MovieWatchProvidersResponseResultsDO struct {
	Flatrate []MovieWatchProvidersResponseResultsDOFlatrate `json:"flatrate,omitzero"`
	Link     string                                         `json:"link,omitempty"`
}
