// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieWatchProvidersResponseResultsCR is an object the document declares inline.
type MovieWatchProvidersResponseResultsCR struct {
	Flatrate []MovieWatchProvidersResponseResultsCRFlatrate `json:"flatrate,omitzero"`
	Link     string                                         `json:"link,omitempty"`
}
