// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieChangesResponseChangesItemsValuePoster is an object the document declares inline.
type MovieChangesResponseChangesItemsValuePoster struct {
	FilePath string `json:"file_path,omitempty"`
}
