// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieWatchProvidersResponseResultsNL is an object the document declares inline.
type MovieWatchProvidersResponseResultsNL struct {
	Buy      []MovieWatchProvidersResponseResultsNLBuy      `json:"buy,omitzero"`
	Flatrate []MovieWatchProvidersResponseResultsNLFlatrate `json:"flatrate,omitzero"`
	Link     string                                         `json:"link,omitempty"`
	Rent     []MovieWatchProvidersResponseResultsNLRent     `json:"rent,omitzero"`
}
