// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// MovieListsOperationResponse is the result of MovieLists.
type MovieListsOperationResponse struct {
	HttpResponse *http.Response
	Model        *MovieListsResponse
}

// MovieListsOperationOptions holds the query and header parameters of MovieLists.
type MovieListsOperationOptions struct {
	Language string
	Page     *int
}

// ToHeaders returns the header parameters the options set.
func (o MovieListsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o MovieListsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Language != "" {
		out.Append("language", o.Language)
	}
	if o.Page != nil {
		out.Append("page", strconv.Itoa(*o.Page))
	}
	return &out
}

// MovieLists calls GET /3/movie/{movie_id}/lists. Lists.
func (c Client) MovieLists(ctx context.Context, movieId int, options MovieListsOperationOptions) (result MovieListsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          fmt.Sprintf("/3/movie/%d/lists", movieId),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model MovieListsResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
