// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// MovieExternalIdsResponse is an object the document declares inline.
type MovieExternalIdsResponse struct {
	FacebookId  string `json:"facebook_id,omitempty"`
	Id          int    `json:"id,omitempty"`
	ImdbId      string `json:"imdb_id,omitempty"`
	InstagramId string `json:"instagram_id,omitempty"`
	TwitterId   string `json:"twitter_id,omitempty"`
	WikidataId  string `json:"wikidata_id,omitempty"`
}
