// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// ChangesMovieListOperationResponse is the result of ChangesMovieList.
type ChangesMovieListOperationResponse struct {
	HttpResponse *http.Response
	Model        *ChangesMovieListResponse
}

// ChangesMovieListOperationOptions holds the query and header parameters of ChangesMovieList.
type ChangesMovieListOperationOptions struct {
	EndDate   string
	Page      int
	StartDate string
}

// ToHeaders returns the header parameters the options set.
func (o ChangesMovieListOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o ChangesMovieListOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.EndDate != "" {
		out.Append("end_date", o.EndDate)
	}
	if o.Page != 0 {
		out.Append("page", strconv.Itoa(o.Page))
	}
	if o.StartDate != "" {
		out.Append("start_date", o.StartDate)
	}
	return &out
}

// ChangesMovieList calls GET /3/movie/changes. Movie List.
func (c Client) ChangesMovieList(ctx context.Context, options ChangesMovieListOperationOptions) (result ChangesMovieListOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/3/movie/changes",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model ChangesMovieListResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
