// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PersonMovieCreditsOperationResponse is the result of PersonMovieCredits.
type PersonMovieCreditsOperationResponse struct {
	HttpResponse *http.Response
	Model        *PersonMovieCreditsResponse
}

// PersonMovieCreditsOperationOptions holds the query and header parameters of PersonMovieCredits.
type PersonMovieCreditsOperationOptions struct {
	Language string
}

// ToHeaders returns the header parameters the options set.
func (o PersonMovieCreditsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PersonMovieCreditsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Language != "" {
		out.Append("language", o.Language)
	}
	return &out
}

// PersonMovieCredits calls GET /3/person/{person_id}/movie_credits. Movie Credits.
func (c Client) PersonMovieCredits(ctx context.Context, personId int, options PersonMovieCreditsOperationOptions) (result PersonMovieCreditsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          fmt.Sprintf("/3/person/%d/movie_credits", personId),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model PersonMovieCreditsResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
