// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PersonTaggedImagesOperationResponse is the result of PersonTaggedImages.
type PersonTaggedImagesOperationResponse struct {
	HttpResponse *http.Response
	Model        *PersonTaggedImagesResponse
}

// PersonTaggedImagesOperationOptions holds the query and header parameters of PersonTaggedImages.
type PersonTaggedImagesOperationOptions struct {
	Page *int
}

// ToHeaders returns the header parameters the options set.
func (o PersonTaggedImagesOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PersonTaggedImagesOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Page != nil {
		out.Append("page", strconv.Itoa(*o.Page))
	}
	return &out
}

// PersonTaggedImages calls GET /3/person/{person_id}/tagged_images. Tagged Images.
func (c Client) PersonTaggedImages(ctx context.Context, personId int, options PersonTaggedImagesOperationOptions) (result PersonTaggedImagesOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          fmt.Sprintf("/3/person/%d/tagged_images", personId),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model PersonTaggedImagesResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
