// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// ChangesPeopleListResponseResults is an object the document declares inline.
type ChangesPeopleListResponseResults struct {
	Adult *bool `json:"adult,omitempty"`
	Id    int   `json:"id,omitempty"`
}
