// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// SearchTvResponse is an object the document declares inline.
type SearchTvResponse struct {
	Page         int                       `json:"page,omitempty"`
	Results      []SearchTvResponseResults `json:"results,omitzero"`
	TotalPages   int                       `json:"total_pages,omitempty"`
	TotalResults int                       `json:"total_results,omitempty"`
}
