// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// SearchKeywordResponse is an object the document declares inline.
type SearchKeywordResponse struct {
	Page         int                            `json:"page,omitempty"`
	Results      []SearchKeywordResponseResults `json:"results,omitzero"`
	TotalPages   int                            `json:"total_pages,omitempty"`
	TotalResults int                            `json:"total_results,omitempty"`
}
