// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// TvSeriesWatchProvidersOperationResponse is the result of TvSeriesWatchProviders.
type TvSeriesWatchProvidersOperationResponse struct {
	HttpResponse *http.Response
	Model        *TvSeriesWatchProvidersResponse
}

// TvSeriesWatchProviders calls GET /3/tv/{series_id}/watch/providers. Watch Providers.
func (c Client) TvSeriesWatchProviders(ctx context.Context, seriesId int) (result TvSeriesWatchProvidersOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod: http.MethodGet,
		Path:       fmt.Sprintf("/3/tv/%d/watch/providers", seriesId),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model TvSeriesWatchProvidersResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
