// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeasonExternalIdsResponse is an object the document declares inline.
type TvSeasonExternalIdsResponse struct {
	FreebaseId  string `json:"freebase_id,omitempty"`
	FreebaseMid string `json:"freebase_mid,omitempty"`
	Id          int    `json:"id,omitempty"`
	TvdbId      int    `json:"tvdb_id,omitempty"`
	TvrageId    int    `json:"tvrage_id,omitempty"`
	WikidataId  string `json:"wikidata_id,omitempty"`
}
