// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesWatchProvidersResponseResultsAR is an object the document declares inline.
type TvSeriesWatchProvidersResponseResultsAR struct {
	Flatrate []TvSeriesWatchProvidersResponseResultsARFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
