// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// TvEpisodeAccountStatesOperationResponse is the result of TvEpisodeAccountStates.
type TvEpisodeAccountStatesOperationResponse struct {
	HttpResponse *http.Response
	Model        *TvEpisodeAccountStatesResponse
}

// TvEpisodeAccountStatesOperationOptions holds the query and header parameters of TvEpisodeAccountStates.
type TvEpisodeAccountStatesOperationOptions struct {
	SessionId      string
	GuestSessionId string
}

// ToHeaders returns the header parameters the options set.
func (o TvEpisodeAccountStatesOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o TvEpisodeAccountStatesOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.SessionId != "" {
		out.Append("session_id", o.SessionId)
	}
	if o.GuestSessionId != "" {
		out.Append("guest_session_id", o.GuestSessionId)
	}
	return &out
}

// TvEpisodeAccountStates calls GET /3/tv/{series_id}/season/{season_number}/episode/{episode_number}/account_states. Account States.
func (c Client) TvEpisodeAccountStates(ctx context.Context, seriesId int, seasonNumber int, episodeNumber int, options TvEpisodeAccountStatesOperationOptions) (result TvEpisodeAccountStatesOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          fmt.Sprintf("/3/tv/%d/season/%d/episode/%d/account_states", seriesId, seasonNumber, episodeNumber),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model TvEpisodeAccountStatesResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
