// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeasonWatchProvidersResponseResultsCH is an object the document declares inline.
type TvSeasonWatchProvidersResponseResultsCH struct {
	Buy      []TvSeasonWatchProvidersResponseResultsCHBuy      `json:"buy,omitzero"`
	Flatrate []TvSeasonWatchProvidersResponseResultsCHFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
