// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvEpisodeDeleteRatingResponse is an object the document declares inline.
type TvEpisodeDeleteRatingResponse struct {
	StatusCode    int    `json:"status_code,omitempty"`
	StatusMessage string `json:"status_message,omitempty"`
}
