// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesWatchProvidersResponseResultsNZ is an object the document declares inline.
type TvSeriesWatchProvidersResponseResultsNZ struct {
	Flatrate []TvSeriesWatchProvidersResponseResultsNZFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
