// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeasonWatchProvidersResponseResultsTT is an object the document declares inline.
type TvSeasonWatchProvidersResponseResultsTT struct {
	Flatrate []TvSeasonWatchProvidersResponseResultsTTFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
