// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeasonWatchProvidersResponseResultsRS is an object the document declares inline.
type TvSeasonWatchProvidersResponseResultsRS struct {
	Flatrate []TvSeasonWatchProvidersResponseResultsRSFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
