// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesChangesResponse is an object the document declares inline.
type TvSeriesChangesResponse struct {
	Changes []TvSeriesChangesResponseChanges `json:"changes,omitzero"`
}
