// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeasonDetailsResponseNetworks is an object the document declares inline.
type TvSeasonDetailsResponseNetworks struct {
	Id            int    `json:"id,omitempty"`
	LogoPath      string `json:"logo_path,omitempty"`
	Name          string `json:"name,omitempty"`
	OriginCountry string `json:"origin_country,omitempty"`
}
