// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeasonWatchProvidersResponseResultsNO is an object the document declares inline.
type TvSeasonWatchProvidersResponseResultsNO struct {
	Flatrate []TvSeasonWatchProvidersResponseResultsNOFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
