// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesWatchProvidersResponseResultsCZ is an object the document declares inline.
type TvSeriesWatchProvidersResponseResultsCZ struct {
	Flatrate []TvSeriesWatchProvidersResponseResultsCZFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
