// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesWatchProvidersResponseResultsTW is an object the document declares inline.
type TvSeriesWatchProvidersResponseResultsTW struct {
	Flatrate []TvSeriesWatchProvidersResponseResultsTWFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
