// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesWatchProvidersResponseResultsAU is an object the document declares inline.
type TvSeriesWatchProvidersResponseResultsAU struct {
	Buy      []TvSeriesWatchProvidersResponseResultsAUBuy      `json:"buy,omitzero"`
	Flatrate []TvSeriesWatchProvidersResponseResultsAUFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
