// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// ListsCopyResponseResults is an object the document declares inline.
type ListsCopyResponseResults struct {
	Description   string `json:"description,omitempty"`
	FavoriteCount int    `json:"favorite_count,omitempty"`
	Id            int    `json:"id,omitempty"`
	Iso31661      string `json:"iso_3166_1,omitempty"`
	Iso6391       string `json:"iso_639_1,omitempty"`
	ItemCount     int    `json:"item_count,omitempty"`
	Name          string `json:"name,omitempty"`
	PosterPath    string `json:"poster_path,omitempty"`
}
