// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesLatestIdResponseProductionCompanies is an object the document declares inline.
type TvSeriesLatestIdResponseProductionCompanies struct {
	Id            int    `json:"id,omitempty"`
	LogoPath      string `json:"logo_path,omitempty"`
	Name          string `json:"name,omitempty"`
	OriginCountry string `json:"origin_country,omitempty"`
}
