// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeasonCreditsResponse is an object the document declares inline.
type TvSeasonCreditsResponse struct {
	Cast []TvSeasonCreditsResponseCast `json:"cast,omitzero"`
	Crew []TvSeasonCreditsResponseCrew `json:"crew,omitzero"`
	Id   int                           `json:"id,omitempty"`
}
