// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeasonWatchProvidersResponseResultsKE is an object the document declares inline.
type TvSeasonWatchProvidersResponseResultsKE struct {
	Flatrate []TvSeasonWatchProvidersResponseResultsKEFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
