// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesAccountStatesResponseRated is an object the document declares inline.
type TvSeriesAccountStatesResponseRated struct {
	Value int `json:"value,omitempty"`
}
