// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesRecommendationsResponse is an object the document declares inline.
type TvSeriesRecommendationsResponse struct {
	Page         int                                      `json:"page,omitempty"`
	Results      []TvSeriesRecommendationsResponseResults `json:"results,omitzero"`
	TotalPages   int                                      `json:"total_pages,omitempty"`
	TotalResults int                                      `json:"total_results,omitempty"`
}
