// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// TvSeriesAccountStatesOperationResponse is the result of TvSeriesAccountStates.
type TvSeriesAccountStatesOperationResponse struct {
	HttpResponse *http.Response
	Model        *TvSeriesAccountStatesResponse
}

// TvSeriesAccountStatesOperationOptions holds the query and header parameters of TvSeriesAccountStates.
type TvSeriesAccountStatesOperationOptions struct {
	SessionId      string
	GuestSessionId string
}

// ToHeaders returns the header parameters the options set.
func (o TvSeriesAccountStatesOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o TvSeriesAccountStatesOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.SessionId != "" {
		out.Append("session_id", o.SessionId)
	}
	if o.GuestSessionId != "" {
		out.Append("guest_session_id", o.GuestSessionId)
	}
	return &out
}

// TvSeriesAccountStates calls GET /3/tv/{series_id}/account_states. Account States.
func (c Client) TvSeriesAccountStates(ctx context.Context, seriesId int, options TvSeriesAccountStatesOperationOptions) (result TvSeriesAccountStatesOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          fmt.Sprintf("/3/tv/%d/account_states", seriesId),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model TvSeriesAccountStatesResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
