// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesChangesResponseChangesItemsOriginalValuePoster is an object the document declares inline.
type TvSeriesChangesResponseChangesItemsOriginalValuePoster struct {
	FilePath string `json:"file_path,omitempty"`
	Iso6391  string `json:"iso_639_1,omitempty"`
}
