// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// TvSeriesTranslationsOperationResponse is the result of TvSeriesTranslations.
type TvSeriesTranslationsOperationResponse struct {
	HttpResponse *http.Response
	Model        *TvSeriesTranslationsResponse
}

// TvSeriesTranslations calls GET /3/tv/{series_id}/translations. Translations.
func (c Client) TvSeriesTranslations(ctx context.Context, seriesId int) (result TvSeriesTranslationsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/3/tv/%d/translations", seriesId),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model TvSeriesTranslationsResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
