// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// TvEpisodeDetailsOperationResponse is the result of TvEpisodeDetails.
type TvEpisodeDetailsOperationResponse struct {
	HttpResponse *http.Response
	Model        *TvEpisodeDetailsResponse
}

// TvEpisodeDetailsOperationOptions holds the query and header parameters of TvEpisodeDetails.
type TvEpisodeDetailsOperationOptions struct {
	// comma separated list of endpoints within this namespace, 20 items max
	AppendToResponse string
	Language         string
}

// ToHeaders returns the header parameters the options set.
func (o TvEpisodeDetailsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o TvEpisodeDetailsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.AppendToResponse != "" {
		out.Append("append_to_response", o.AppendToResponse)
	}
	if o.Language != "" {
		out.Append("language", o.Language)
	}
	return &out
}

// TvEpisodeDetails calls GET /3/tv/{series_id}/season/{season_number}/episode/{episode_number}. Details.
func (c Client) TvEpisodeDetails(ctx context.Context, seriesId int, seasonNumber int, episodeNumber int, options TvEpisodeDetailsOperationOptions) (result TvEpisodeDetailsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          fmt.Sprintf("/3/tv/%d/season/%d/episode/%d", seriesId, seasonNumber, episodeNumber),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model TvEpisodeDetailsResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
