// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvEpisodeChangesByIdResponse is an object the document declares inline.
type TvEpisodeChangesByIdResponse struct {
	Changes []TvEpisodeChangesByIdResponseChanges `json:"changes,omitzero"`
}
