// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeasonWatchProvidersResponseResultsGG is an object the document declares inline.
type TvSeasonWatchProvidersResponseResultsGG struct {
	Buy  []TvSeasonWatchProvidersResponseResultsGGBuy `json:"buy,omitzero"`
	Link string                                       `json:"link,omitempty"`
}
