// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// TvSeriesVideosOperationResponse is the result of TvSeriesVideos.
type TvSeriesVideosOperationResponse struct {
	HttpResponse *http.Response
	Model        *TvSeriesVideosResponse
}

// TvSeriesVideosOperationOptions holds the query and header parameters of TvSeriesVideos.
type TvSeriesVideosOperationOptions struct {
	// filter the list results by language, supports more than one value by using a comma
	IncludeVideoLanguage string
	Language             string
}

// ToHeaders returns the header parameters the options set.
func (o TvSeriesVideosOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o TvSeriesVideosOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.IncludeVideoLanguage != "" {
		out.Append("include_video_language", o.IncludeVideoLanguage)
	}
	if o.Language != "" {
		out.Append("language", o.Language)
	}
	return &out
}

// TvSeriesVideos calls GET /3/tv/{series_id}/videos. Videos.
func (c Client) TvSeriesVideos(ctx context.Context, seriesId int, options TvSeriesVideosOperationOptions) (result TvSeriesVideosOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          fmt.Sprintf("/3/tv/%d/videos", seriesId),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model TvSeriesVideosResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
