// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeasonWatchProvidersResponseResultsBR is an object the document declares inline.
type TvSeasonWatchProvidersResponseResultsBR struct {
	Flatrate []TvSeasonWatchProvidersResponseResultsBRFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
