// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeasonDetailsResponse is an object the document declares inline.
type TvSeasonDetailsResponse struct {
	AirDate      string                            `json:"air_date,omitempty"`
	Episodes     []TvSeasonDetailsResponseEpisodes `json:"episodes,omitzero"`
	Id           int                               `json:"id,omitempty"`
	Name         string                            `json:"name,omitempty"`
	Networks     []TvSeasonDetailsResponseNetworks `json:"networks,omitzero"`
	Overview     string                            `json:"overview,omitempty"`
	PosterPath   string                            `json:"poster_path,omitempty"`
	SeasonNumber int                               `json:"season_number,omitempty"`
	VoteAverage  float64                           `json:"vote_average,omitempty"`
	UnderscoreId string                            `json:"_id,omitempty"`
}
