// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeasonWatchProvidersResponseResultsRU is an object the document declares inline.
type TvSeasonWatchProvidersResponseResultsRU struct {
	Flatrate []TvSeasonWatchProvidersResponseResultsRUFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
