// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// TvSeasonAggregateCreditsOperationResponse is the result of TvSeasonAggregateCredits.
type TvSeasonAggregateCreditsOperationResponse struct {
	HttpResponse *http.Response
	Model        *TvSeasonAggregateCreditsResponse
}

// TvSeasonAggregateCreditsOperationOptions holds the query and header parameters of TvSeasonAggregateCredits.
type TvSeasonAggregateCreditsOperationOptions struct {
	Language string
}

// ToHeaders returns the header parameters the options set.
func (o TvSeasonAggregateCreditsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o TvSeasonAggregateCreditsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Language != "" {
		out.Append("language", o.Language)
	}
	return &out
}

// TvSeasonAggregateCredits calls GET /3/tv/{series_id}/season/{season_number}/aggregate_credits. Aggregate Credits.
func (c Client) TvSeasonAggregateCredits(ctx context.Context, seriesId int, seasonNumber int, options TvSeasonAggregateCreditsOperationOptions) (result TvSeasonAggregateCreditsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          fmt.Sprintf("/3/tv/%d/season/%d/aggregate_credits", seriesId, seasonNumber),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model TvSeasonAggregateCreditsResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
