// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesContentRatingsResponseResults is an object the document declares inline.
type TvSeriesContentRatingsResponseResults struct {
	Descriptors []string `json:"descriptors,omitzero"`
	Iso31661    string   `json:"iso_3166_1,omitempty"`
	Rating      string   `json:"rating,omitempty"`
}
