// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesWatchProvidersResponseResultsBE is an object the document declares inline.
type TvSeriesWatchProvidersResponseResultsBE struct {
	Flatrate []TvSeriesWatchProvidersResponseResultsBEFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
