// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesWatchProvidersResponseResultsPY is an object the document declares inline.
type TvSeriesWatchProvidersResponseResultsPY struct {
	Flatrate []TvSeriesWatchProvidersResponseResultsPYFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
