// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeasonChangesByIdResponseChangesItemsValue is an object the document declares inline.
type TvSeasonChangesByIdResponseChangesItemsValue struct {
	EpisodeId     int `json:"episode_id,omitempty"`
	EpisodeNumber int `json:"episode_number,omitempty"`
}
