// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeasonWatchProvidersResponseResultsNL is an object the document declares inline.
type TvSeasonWatchProvidersResponseResultsNL struct {
	Buy      []TvSeasonWatchProvidersResponseResultsNLBuy      `json:"buy,omitzero"`
	Flatrate []TvSeasonWatchProvidersResponseResultsNLFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
