// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// TvSeriesAiringTodayListOperationResponse is the result of TvSeriesAiringTodayList.
type TvSeriesAiringTodayListOperationResponse struct {
	HttpResponse *http.Response
	Model        *TvSeriesAiringTodayListResponse
}

// TvSeriesAiringTodayListOperationOptions holds the query and header parameters of TvSeriesAiringTodayList.
type TvSeriesAiringTodayListOperationOptions struct {
	Language string
	Page     *int
	Timezone string
}

// ToHeaders returns the header parameters the options set.
func (o TvSeriesAiringTodayListOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o TvSeriesAiringTodayListOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Language != "" {
		out.Append("language", o.Language)
	}
	if o.Page != nil {
		out.Append("page", strconv.Itoa(*o.Page))
	}
	if o.Timezone != "" {
		out.Append("timezone", o.Timezone)
	}
	return &out
}

// TvSeriesAiringTodayList calls GET /3/tv/airing_today. Airing Today.
func (c Client) TvSeriesAiringTodayList(ctx context.Context, options TvSeriesAiringTodayListOperationOptions) (result TvSeriesAiringTodayListOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/3/tv/airing_today",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model TvSeriesAiringTodayListResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
