// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// TvSeasonImagesOperationResponse is the result of TvSeasonImages.
type TvSeasonImagesOperationResponse struct {
	HttpResponse *http.Response
	Model        *TvSeasonImagesResponse
}

// TvSeasonImagesOperationOptions holds the query and header parameters of TvSeasonImages.
type TvSeasonImagesOperationOptions struct {
	// specify a comma separated list of ISO-639-1 values to query, for example: `en-US,null`
	IncludeImageLanguage string
	Language             string
}

// ToHeaders returns the header parameters the options set.
func (o TvSeasonImagesOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o TvSeasonImagesOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.IncludeImageLanguage != "" {
		out.Append("include_image_language", o.IncludeImageLanguage)
	}
	if o.Language != "" {
		out.Append("language", o.Language)
	}
	return &out
}

// TvSeasonImages calls GET /3/tv/{series_id}/season/{season_number}/images. Images.
func (c Client) TvSeasonImages(ctx context.Context, seriesId int, seasonNumber int, options TvSeasonImagesOperationOptions) (result TvSeasonImagesOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          fmt.Sprintf("/3/tv/%d/season/%d/images", seriesId, seasonNumber),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model TvSeasonImagesResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
