// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesWatchProvidersResponseResultsVE is an object the document declares inline.
type TvSeriesWatchProvidersResponseResultsVE struct {
	Flatrate []TvSeriesWatchProvidersResponseResultsVEFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
