// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesWatchProvidersResponseResultsPL is an object the document declares inline.
type TvSeriesWatchProvidersResponseResultsPL struct {
	Flatrate []TvSeriesWatchProvidersResponseResultsPLFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
	Rent     []TvSeriesWatchProvidersResponseResultsPLRent     `json:"rent,omitzero"`
}
