// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesChangesResponseChangesItemsValue is an object the document declares inline.
type TvSeriesChangesResponseChangesItemsValue struct {
	Poster *TvSeriesChangesResponseChangesItemsValuePoster `json:"poster,omitempty"`
}
