// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeasonWatchProvidersResponseResultsHN is an object the document declares inline.
type TvSeasonWatchProvidersResponseResultsHN struct {
	Flatrate []TvSeasonWatchProvidersResponseResultsHNFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
