// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesWatchProvidersResponseResultsTZ is an object the document declares inline.
type TvSeriesWatchProvidersResponseResultsTZ struct {
	Flatrate []TvSeriesWatchProvidersResponseResultsTZFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
