// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesWatchProvidersResponseResultsSC is an object the document declares inline.
type TvSeriesWatchProvidersResponseResultsSC struct {
	Flatrate []TvSeriesWatchProvidersResponseResultsSCFlatrate `json:"flatrate,omitzero"`
	Link     string                                            `json:"link,omitempty"`
}
