// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// TvSeriesVideosResponseResults is an object the document declares inline.
type TvSeriesVideosResponseResults struct {
	Id          string `json:"id,omitempty"`
	Iso31661    string `json:"iso_3166_1,omitempty"`
	Iso6391     string `json:"iso_639_1,omitempty"`
	Key         string `json:"key,omitempty"`
	Name        string `json:"name,omitempty"`
	Official    *bool  `json:"official,omitempty"`
	PublishedAt string `json:"published_at,omitempty"`
	Site        string `json:"site,omitempty"`
	Size        int    `json:"size,omitempty"`
	Type        string `json:"type,omitempty"`
}
