// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

// WatchProvidersAvailableRegionsResponseResults is an object the document declares inline.
type WatchProvidersAvailableRegionsResponseResults struct {
	EnglishName string `json:"english_name,omitempty"`
	Iso31661    string `json:"iso_3166_1,omitempty"`
	NativeName  string `json:"native_name,omitempty"`
}
