// Code generated by internal/pandorest; DO NOT EDIT.

package tmdb

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// WatchProviderTvListOperationResponse is the result of WatchProviderTvList.
type WatchProviderTvListOperationResponse struct {
	HttpResponse *http.Response
	Model        *WatchProviderTvListResponse
}

// WatchProviderTvListOperationOptions holds the query and header parameters of WatchProviderTvList.
type WatchProviderTvListOperationOptions struct {
	Language    string
	WatchRegion string
}

// ToHeaders returns the header parameters the options set.
func (o WatchProviderTvListOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o WatchProviderTvListOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Language != "" {
		out.Append("language", o.Language)
	}
	if o.WatchRegion != "" {
		out.Append("watch_region", o.WatchRegion)
	}
	return &out
}

// WatchProviderTvList calls GET /3/watch/providers/tv. TV Providers.
func (c Client) WatchProviderTvList(ctx context.Context, options WatchProviderTvListOperationOptions) (result WatchProviderTvListOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/3/watch/providers/tv",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model WatchProviderTvListResponse
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
