// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"io"
	"net/http"
	"testing"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

func TestOperationGetUniversalAudioStream(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "audio/mpeg", "file bytes")
	result, err := c.GetUniversalAudioStream(t.Context(), "p/itemId", GetUniversalAudioStreamOperationOptions{
		Container:                []string{"a", "b"},
		MediaSourceId:            "v-MediaSourceId",
		DeviceId:                 "v-DeviceId",
		UserId:                   "v-UserId",
		AudioCodec:               "v-AudioCodec",
		MaxAudioChannels:         new(7),
		TranscodingAudioChannels: new(7),
		MaxStreamingBitrate:      new(7),
		AudioBitRate:             new(7),
		StartTimeTicks:           new(int64(7)),
		TranscodingContainer:     "v-TranscodingContainer",
		TranscodingProtocol:      MediaStreamProtocolHttp,
		MaxAudioSampleRate:       new(7),
		MaxAudioBitDepth:         new(7),
		EnableRemoteMedia:        new(true),
		EnableAudioVbrEncoding:   new(true),
		EnableRedirection:        new(true),
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/Audio/p%2FitemId/universal")
	expectQuery(t, r, "container", "a", "b")
	expectQuery(t, r, "mediaSourceId", "v-MediaSourceId")
	expectQuery(t, r, "deviceId", "v-DeviceId")
	expectQuery(t, r, "userId", "v-UserId")
	expectQuery(t, r, "audioCodec", "v-AudioCodec")
	expectQuery(t, r, "maxAudioChannels", "7")
	expectQuery(t, r, "transcodingAudioChannels", "7")
	expectQuery(t, r, "maxStreamingBitrate", "7")
	expectQuery(t, r, "audioBitRate", "7")
	expectQuery(t, r, "startTimeTicks", "7")
	expectQuery(t, r, "transcodingContainer", "v-TranscodingContainer")
	expectQuery(t, r, "transcodingProtocol", "http")
	expectQuery(t, r, "maxAudioSampleRate", "7")
	expectQuery(t, r, "maxAudioBitDepth", "7")
	expectQuery(t, r, "enableRemoteMedia", "true")
	expectQuery(t, r, "enableAudioVbrEncoding", "true")
	expectQuery(t, r, "enableRedirection", "true")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	streamed, _ := io.ReadAll(result.HttpResponse.Body)
	_ = result.HttpResponse.Body.Close()
	if string(streamed) != "file bytes" {
		t.Errorf("streamed body = %q", streamed)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.GetUniversalAudioStream(t.Context(), "p/itemId", GetUniversalAudioStreamOperationOptions{
		Container:                []string{"a", "b"},
		MediaSourceId:            "v-MediaSourceId",
		DeviceId:                 "v-DeviceId",
		UserId:                   "v-UserId",
		AudioCodec:               "v-AudioCodec",
		MaxAudioChannels:         new(7),
		TranscodingAudioChannels: new(7),
		MaxStreamingBitrate:      new(7),
		AudioBitRate:             new(7),
		StartTimeTicks:           new(int64(7)),
		TranscodingContainer:     "v-TranscodingContainer",
		TranscodingProtocol:      MediaStreamProtocolHttp,
		MaxAudioSampleRate:       new(7),
		MaxAudioBitDepth:         new(7),
		EnableRemoteMedia:        new(true),
		EnableAudioVbrEncoding:   new(true),
		EnableRedirection:        new(true),
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
