// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetQuickConnectEnabledOperationResponse is the result of GetQuickConnectEnabled.
type GetQuickConnectEnabledOperationResponse struct {
	HttpResponse *http.Response
	Model        *bool
}

// GetQuickConnectEnabled calls GET /QuickConnect/Enabled. Gets the current quick connect state.
func (c Client) GetQuickConnectEnabled(ctx context.Context) (result GetQuickConnectEnabledOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/QuickConnect/Enabled",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model bool
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
