// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetKeysOperationResponse is the result of GetKeys.
type GetKeysOperationResponse struct {
	HttpResponse *http.Response
	Model        *AuthenticationInfoQueryResult
}

// GetKeys calls GET /Auth/Keys. Get all keys.
func (c Client) GetKeys(ctx context.Context) (result GetKeysOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/Auth/Keys",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model AuthenticationInfoQueryResult
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
