// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// AuthorizeQuickConnectOperationResponse is the result of AuthorizeQuickConnect.
type AuthorizeQuickConnectOperationResponse struct {
	HttpResponse *http.Response
	Model        *bool
}

// AuthorizeQuickConnectOperationOptions holds the query and header parameters of AuthorizeQuickConnect.
type AuthorizeQuickConnectOperationOptions struct {
	// Quick connect code to authorize.
	Code string

	// The user the authorize. Access to the requested user is required.
	UserId string
}

// ToHeaders returns the header parameters the options set.
func (o AuthorizeQuickConnectOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o AuthorizeQuickConnectOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Code != "" {
		out.Append("code", o.Code)
	}
	if o.UserId != "" {
		out.Append("userId", o.UserId)
	}
	return &out
}

// AuthorizeQuickConnect calls POST /QuickConnect/Authorize. Authorizes a pending quick connect request.
func (c Client) AuthorizeQuickConnect(ctx context.Context, options AuthorizeQuickConnectOperationOptions) (result AuthorizeQuickConnectOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          "/QuickConnect/Authorize",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model bool
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
