// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetBrandingCss2OperationResponse is the result of GetBrandingCss2.
//
// The operation answers text/css, left unread in HttpResponse.Body, which
// the caller must close.
type GetBrandingCss2OperationResponse struct {
	HttpResponse *http.Response
}

// GetBrandingCss2 calls GET /Branding/Css.css. Gets branding css.
func (c Client) GetBrandingCss2(ctx context.Context) (result GetBrandingCss2OperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusNoContent,
		},
		HTTPMethod:     http.MethodGet,
		Path:           "/Branding/Css.css",
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
