// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// ChannelItemSortField is the "ChannelItemSortField" enum.
type ChannelItemSortField string

// Values of ChannelItemSortField.
const (
	ChannelItemSortFieldName               ChannelItemSortField = "Name"
	ChannelItemSortFieldCommunityRating    ChannelItemSortField = "CommunityRating"
	ChannelItemSortFieldPremiereDate       ChannelItemSortField = "PremiereDate"
	ChannelItemSortFieldDateCreated        ChannelItemSortField = "DateCreated"
	ChannelItemSortFieldRuntime            ChannelItemSortField = "Runtime"
	ChannelItemSortFieldPlayCount          ChannelItemSortField = "PlayCount"
	ChannelItemSortFieldCommunityPlayCount ChannelItemSortField = "CommunityPlayCount"
)

// PossibleValuesForChannelItemSortField returns every value of ChannelItemSortField.
func PossibleValuesForChannelItemSortField() []string {
	return []string{
		string(ChannelItemSortFieldName),
		string(ChannelItemSortFieldCommunityRating),
		string(ChannelItemSortFieldPremiereDate),
		string(ChannelItemSortFieldDateCreated),
		string(ChannelItemSortFieldRuntime),
		string(ChannelItemSortFieldPlayCount),
		string(ChannelItemSortFieldCommunityPlayCount),
	}
}

// ChannelMediaContentType is the "ChannelMediaContentType" enum.
type ChannelMediaContentType string

// Values of ChannelMediaContentType.
const (
	ChannelMediaContentTypeClip       ChannelMediaContentType = "Clip"
	ChannelMediaContentTypePodcast    ChannelMediaContentType = "Podcast"
	ChannelMediaContentTypeTrailer    ChannelMediaContentType = "Trailer"
	ChannelMediaContentTypeMovie      ChannelMediaContentType = "Movie"
	ChannelMediaContentTypeEpisode    ChannelMediaContentType = "Episode"
	ChannelMediaContentTypeSong       ChannelMediaContentType = "Song"
	ChannelMediaContentTypeMovieExtra ChannelMediaContentType = "MovieExtra"
	ChannelMediaContentTypeTvExtra    ChannelMediaContentType = "TvExtra"
)

// PossibleValuesForChannelMediaContentType returns every value of ChannelMediaContentType.
func PossibleValuesForChannelMediaContentType() []string {
	return []string{
		string(ChannelMediaContentTypeClip),
		string(ChannelMediaContentTypePodcast),
		string(ChannelMediaContentTypeTrailer),
		string(ChannelMediaContentTypeMovie),
		string(ChannelMediaContentTypeEpisode),
		string(ChannelMediaContentTypeSong),
		string(ChannelMediaContentTypeMovieExtra),
		string(ChannelMediaContentTypeTvExtra),
	}
}

// ChannelMediaType is the "ChannelMediaType" enum.
type ChannelMediaType string

// Values of ChannelMediaType.
const (
	ChannelMediaTypeAudio ChannelMediaType = "Audio"
	ChannelMediaTypeVideo ChannelMediaType = "Video"
	ChannelMediaTypePhoto ChannelMediaType = "Photo"
)

// PossibleValuesForChannelMediaType returns every value of ChannelMediaType.
func PossibleValuesForChannelMediaType() []string {
	return []string{
		string(ChannelMediaTypeAudio),
		string(ChannelMediaTypeVideo),
		string(ChannelMediaTypePhoto),
	}
}
