// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// CollectionCreationResult is the "CollectionCreationResult" schema.
type CollectionCreationResult struct {
	Id string `json:"Id,omitempty"`
}
