// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// AddToCollectionOperationResponse is the result of AddToCollection.
type AddToCollectionOperationResponse struct {
	HttpResponse *http.Response
}

// AddToCollectionOperationOptions holds the query and header parameters of AddToCollection.
type AddToCollectionOperationOptions struct {
	// Item ids, comma delimited.
	Ids []string
}

// ToHeaders returns the header parameters the options set.
func (o AddToCollectionOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o AddToCollectionOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	for _, v := range o.Ids {
		out.Append("ids", v)
	}
	return &out
}

// AddToCollection calls POST /Collections/{collectionId}/Items. Adds items to a collection.
func (c Client) AddToCollection(ctx context.Context, collectionId string, options AddToCollectionOperationOptions) (result AddToCollectionOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusNoContent,
		},
		HttpMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          fmt.Sprintf("/Collections/%s/Items", url.PathEscape(collectionId)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
