// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// MediaStream is the "MediaStream" schema.
//
// Class MediaStream.
type MediaStream struct {
	// Gets or sets the aspect ratio.
	AspectRatio string `json:"AspectRatio,omitempty"`

	// Gets the audio spatial format.
	AudioSpatialFormat AudioSpatialFormat `json:"AudioSpatialFormat,omitempty"`

	// Gets or sets the average frame rate.
	AverageFrameRate float32 `json:"AverageFrameRate,omitempty"`

	// Gets or sets the bit depth.
	BitDepth int `json:"BitDepth,omitempty"`

	// Gets or sets the bit rate.
	BitRate int `json:"BitRate,omitempty"`

	// Gets or sets the Dolby Vision bl present flag.
	BlPresentFlag int `json:"BlPresentFlag,omitempty"`

	// Gets or sets the channel layout.
	ChannelLayout string `json:"ChannelLayout,omitempty"`

	// Gets or sets the channels.
	Channels int `json:"Channels,omitempty"`

	// Gets or sets the codec.
	Codec string `json:"Codec,omitempty"`

	// Gets or sets the codec tag.
	CodecTag string `json:"CodecTag,omitempty"`

	// Gets or sets the codec time base.
	CodecTimeBase string `json:"CodecTimeBase,omitempty"`

	// Gets or sets the color primaries.
	ColorPrimaries string `json:"ColorPrimaries,omitempty"`

	// Gets or sets the color range.
	ColorRange string `json:"ColorRange,omitempty"`

	// Gets or sets the color space.
	ColorSpace string `json:"ColorSpace,omitempty"`

	// Gets or sets the color transfer.
	ColorTransfer string `json:"ColorTransfer,omitempty"`

	// Gets or sets the comment.
	Comment string `json:"Comment,omitempty"`

	// Gets or sets the method.
	DeliveryMethod SubtitleDeliveryMethod `json:"DeliveryMethod,omitempty"`

	// Gets or sets the delivery URL.
	DeliveryUrl  string `json:"DeliveryUrl,omitempty"`
	DisplayTitle string `json:"DisplayTitle,omitempty"`

	// Gets or sets the Dolby Vision bl signal compatibility id.
	DvBlSignalCompatibilityId int `json:"DvBlSignalCompatibilityId,omitempty"`

	// Gets or sets the Dolby Vision level.
	DvLevel int `json:"DvLevel,omitempty"`

	// Gets or sets the Dolby Vision profile.
	DvProfile int `json:"DvProfile,omitempty"`

	// Gets or sets the Dolby Vision version major.
	DvVersionMajor int `json:"DvVersionMajor,omitempty"`

	// Gets or sets the Dolby Vision version minor.
	DvVersionMinor int `json:"DvVersionMinor,omitempty"`

	// Gets or sets the Dolby Vision el present flag.
	ElPresentFlag        int   `json:"ElPresentFlag,omitempty"`
	Hdr10PlusPresentFlag *bool `json:"Hdr10PlusPresentFlag,omitempty"`

	// Gets or sets the height.
	Height int `json:"Height,omitempty"`

	// Gets or sets the index.
	Index int   `json:"Index,omitempty"`
	IsAVC *bool `json:"IsAVC,omitempty"`

	// Gets or sets whether this instance is anamorphic.
	IsAnamorphic *bool `json:"IsAnamorphic,omitempty"`

	// Gets or sets a value indicating whether this instance is default.
	IsDefault *bool `json:"IsDefault,omitempty"`

	// Gets or sets a value indicating whether this instance is external.
	IsExternal *bool `json:"IsExternal,omitempty"`

	// Gets or sets a value indicating whether this instance is external URL.
	IsExternalUrl *bool `json:"IsExternalUrl,omitempty"`

	// Gets or sets a value indicating whether this instance is forced.
	IsForced *bool `json:"IsForced,omitempty"`

	// Gets or sets a value indicating whether this instance is for the hearing impaired.
	IsHearingImpaired *bool `json:"IsHearingImpaired,omitempty"`

	// Gets or sets a value indicating whether this instance is interlaced.
	IsInterlaced *bool `json:"IsInterlaced,omitempty"`

	// Gets or sets a value indicating whether this instance is original.
	IsOriginal           *bool `json:"IsOriginal,omitempty"`
	IsTextSubtitleStream *bool `json:"IsTextSubtitleStream,omitempty"`

	// Gets or sets the language.
	Language string `json:"Language,omitempty"`

	// Gets or sets the level.
	Level                    float64 `json:"Level,omitempty"`
	LocalizedDefault         string  `json:"LocalizedDefault,omitempty"`
	LocalizedExternal        string  `json:"LocalizedExternal,omitempty"`
	LocalizedForced          string  `json:"LocalizedForced,omitempty"`
	LocalizedHearingImpaired string  `json:"LocalizedHearingImpaired,omitempty"`
	LocalizedLanguage        string  `json:"LocalizedLanguage,omitempty"`
	LocalizedOriginal        string  `json:"LocalizedOriginal,omitempty"`
	LocalizedUndefined       string  `json:"LocalizedUndefined,omitempty"`
	NalLengthSize            string  `json:"NalLengthSize,omitempty"`

	// Gets or sets the length of the packet.
	PacketLength int `json:"PacketLength,omitempty"`

	// Gets or sets the filename.
	Path string `json:"Path,omitempty"`

	// Gets or sets the pixel format.
	PixelFormat string `json:"PixelFormat,omitempty"`

	// Gets or sets the profile.
	Profile string `json:"Profile,omitempty"`

	// Gets or sets the real frame rate.
	RealFrameRate float32 `json:"RealFrameRate,omitempty"`

	// Gets or sets the reference frames.
	RefFrames int `json:"RefFrames,omitempty"`

	// Gets the framerate used as reference.
	// Prefer AverageFrameRate, if that is null or an unrealistic value
	// then fallback to RealFrameRate.
	ReferenceFrameRate float32 `json:"ReferenceFrameRate,omitempty"`

	// Gets or sets the Rotation in degrees.
	Rotation int `json:"Rotation,omitempty"`

	// Gets or sets the Dolby Vision rpu present flag.
	RpuPresentFlag int `json:"RpuPresentFlag,omitempty"`

	// Gets or sets the sample rate.
	SampleRate int `json:"SampleRate,omitempty"`

	// Gets or sets the score.
	Score int `json:"Score,omitempty"`

	// Gets or sets a value indicating whether [supports external stream].
	SupportsExternalStream *bool `json:"SupportsExternalStream,omitempty"`

	// Gets or sets the time base.
	TimeBase string `json:"TimeBase,omitempty"`

	// Gets or sets the title.
	Title string `json:"Title,omitempty"`

	// Gets or sets the type.
	Type MediaStreamType `json:"Type,omitempty"`

	// Gets the video dovi title.
	VideoDoViTitle string `json:"VideoDoViTitle,omitempty"`

	// Gets the video range.
	VideoRange VideoRange `json:"VideoRange,omitempty"`

	// Gets the video range type.
	VideoRangeType VideoRangeType `json:"VideoRangeType,omitempty"`

	// Gets or sets the width.
	Width int `json:"Width,omitempty"`
}
