// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// SyncPlayGroupJoinedUpdate is the "SyncPlayGroupJoinedUpdate" schema.
type SyncPlayGroupJoinedUpdate struct {
	// Gets the update data.
	Data *GroupInfoDto `json:"Data,omitempty"`

	// Gets the group identifier.
	GroupId string `json:"GroupId,omitempty"`

	// Enum GroupUpdateType.
	Type GroupUpdateType `json:"Type,omitempty"`
}
