// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// UserPolicy is the "UserPolicy" schema.
type UserPolicy struct {
	AccessSchedules                []AccessSchedule `json:"AccessSchedules,omitzero"`
	AllowedTags                    []string         `json:"AllowedTags,omitzero"`
	AuthenticationProviderId       string           `json:"AuthenticationProviderId,omitempty"`
	BlockUnratedItems              []UnratedItem    `json:"BlockUnratedItems,omitzero"`
	BlockedChannels                []string         `json:"BlockedChannels,omitzero"`
	BlockedMediaFolders            []string         `json:"BlockedMediaFolders,omitzero"`
	BlockedTags                    []string         `json:"BlockedTags,omitzero"`
	EnableAllChannels              *bool            `json:"EnableAllChannels,omitempty"`
	EnableAllDevices               *bool            `json:"EnableAllDevices,omitempty"`
	EnableAllFolders               *bool            `json:"EnableAllFolders,omitempty"`
	EnableAudioPlaybackTranscoding *bool            `json:"EnableAudioPlaybackTranscoding,omitempty"`

	// Gets or sets a value indicating whether this instance can manage collections.
	EnableCollectionManagement       *bool    `json:"EnableCollectionManagement,omitempty"`
	EnableContentDeletion            *bool    `json:"EnableContentDeletion,omitempty"`
	EnableContentDeletionFromFolders []string `json:"EnableContentDeletionFromFolders,omitzero"`
	EnableContentDownloading         *bool    `json:"EnableContentDownloading,omitempty"`
	EnableLiveTvAccess               *bool    `json:"EnableLiveTvAccess,omitempty"`
	EnableLiveTvManagement           *bool    `json:"EnableLiveTvManagement,omitempty"`

	// Gets or sets a value indicating whether this user can manage lyrics.
	EnableLyricManagement           *bool `json:"EnableLyricManagement,omitempty"`
	EnableMediaConversion           *bool `json:"EnableMediaConversion,omitempty"`
	EnableMediaPlayback             *bool `json:"EnableMediaPlayback,omitempty"`
	EnablePlaybackRemuxing          *bool `json:"EnablePlaybackRemuxing,omitempty"`
	EnablePublicSharing             *bool `json:"EnablePublicSharing,omitempty"`
	EnableRemoteAccess              *bool `json:"EnableRemoteAccess,omitempty"`
	EnableRemoteControlOfOtherUsers *bool `json:"EnableRemoteControlOfOtherUsers,omitempty"`
	EnableSharedDeviceControl       *bool `json:"EnableSharedDeviceControl,omitempty"`

	// Gets or sets a value indicating whether this instance can manage subtitles.
	EnableSubtitleManagement *bool `json:"EnableSubtitleManagement,omitempty"`

	// Gets or sets a value indicating whether [enable synchronize].
	EnableSyncTranscoding          *bool    `json:"EnableSyncTranscoding,omitempty"`
	EnableUserPreferenceAccess     *bool    `json:"EnableUserPreferenceAccess,omitempty"`
	EnableVideoPlaybackTranscoding *bool    `json:"EnableVideoPlaybackTranscoding,omitempty"`
	EnabledChannels                []string `json:"EnabledChannels,omitzero"`
	EnabledDevices                 []string `json:"EnabledDevices,omitzero"`
	EnabledFolders                 []string `json:"EnabledFolders,omitzero"`
	ForceRemoteSourceTranscoding   *bool    `json:"ForceRemoteSourceTranscoding,omitempty"`
	InvalidLoginAttemptCount       int      `json:"InvalidLoginAttemptCount,omitempty"`

	// Gets or sets a value indicating whether this instance is administrator.
	IsAdministrator *bool `json:"IsAdministrator,omitempty"`

	// Gets or sets a value indicating whether this instance is disabled.
	IsDisabled *bool `json:"IsDisabled,omitempty"`

	// Gets or sets a value indicating whether this instance is hidden.
	IsHidden                   *bool `json:"IsHidden,omitempty"`
	LoginAttemptsBeforeLockout int   `json:"LoginAttemptsBeforeLockout,omitempty"`
	MaxActiveSessions          int   `json:"MaxActiveSessions,omitempty"`

	// Gets or sets the max parental rating.
	MaxParentalRating        int    `json:"MaxParentalRating,omitempty"`
	MaxParentalSubRating     int    `json:"MaxParentalSubRating,omitempty"`
	PasswordResetProviderId  string `json:"PasswordResetProviderId,omitempty"`
	RemoteClientBitrateLimit int    `json:"RemoteClientBitrateLimit,omitempty"`

	// Gets or sets a value indicating what SyncPlay features the user can access.
	SyncPlayAccess SyncPlayUserAccessType `json:"SyncPlayAccess,omitempty"`
}
