// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import "encoding/json"

// OutboundWebSocketMessage is the "OutboundWebSocketMessage" schema, a oneOf/anyOf union kept as raw JSON;
// decode it into one of: ActivityLogEntryMessage, ForceKeepAliveMessage, GeneralCommandMessage, LibraryChangedMessage, OutboundKeepAliveMessage, PlayMessage, PlaystateMessage, PluginInstallationCancelledMessage, PluginInstallationCompletedMessage, PluginInstallationFailedMessage, PluginInstallingMessage, PluginUninstalledMessage, RefreshProgressMessage, RestartRequiredMessage, ScheduledTaskEndedMessage, ScheduledTasksInfoMessage, SeriesTimerCancelledMessage, SeriesTimerCreatedMessage, ServerRestartingMessage, ServerShuttingDownMessage, SessionsMessage, SyncPlayCommandMessage, TimerCancelledMessage, TimerCreatedMessage, UserDataChangedMessage, UserDeletedMessage, UserUpdatedMessage, SyncPlayGroupUpdateMessage.
//
// Represents the list of possible outbound websocket types
type OutboundWebSocketMessage = json.RawMessage
