// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// ImageOption is the "ImageOption" schema.
type ImageOption struct {
	// Gets or sets the limit.
	Limit int `json:"Limit,omitempty"`

	// Gets or sets the minimum width.
	MinWidth int `json:"MinWidth,omitempty"`

	// Gets or sets the type.
	Type ImageType `json:"Type,omitempty"`
}
