// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// SessionInfoDto is the "SessionInfoDto" schema.
//
// Session info DTO.
type SessionInfoDto struct {
	// Gets or sets the additional users.
	AdditionalUsers []SessionUserInfo `json:"AdditionalUsers,omitzero"`

	// Gets or sets the application version.
	ApplicationVersion string `json:"ApplicationVersion,omitempty"`

	// Gets or sets the client capabilities.
	Capabilities *ClientCapabilitiesDto `json:"Capabilities,omitempty"`

	// Gets or sets the type of the client.
	Client string `json:"Client,omitempty"`

	// Gets or sets the device id.
	DeviceId string `json:"DeviceId,omitempty"`

	// Gets or sets the name of the device.
	DeviceName string `json:"DeviceName,omitempty"`

	// Gets or sets the type of the device.
	DeviceType string `json:"DeviceType,omitempty"`

	// Gets or sets a value indicating whether this session has a custom device name.
	HasCustomDeviceName *bool `json:"HasCustomDeviceName,omitempty"`

	// Gets or sets the id.
	Id string `json:"Id,omitempty"`

	// Gets or sets a value indicating whether this session is active.
	IsActive *bool `json:"IsActive,omitempty"`

	// Gets or sets the last activity date.
	LastActivityDate string `json:"LastActivityDate,omitempty"`

	// Gets or sets the last paused date.
	LastPausedDate string `json:"LastPausedDate,omitempty"`

	// Gets or sets the last playback check in.
	LastPlaybackCheckIn string `json:"LastPlaybackCheckIn,omitempty"`

	// Gets or sets the now playing item.
	NowPlayingItem *BaseItemDto `json:"NowPlayingItem,omitempty"`

	// Gets or sets the now playing queue.
	NowPlayingQueue []QueueItem `json:"NowPlayingQueue,omitzero"`

	// Gets or sets the now viewing item.
	NowViewingItem *BaseItemDto `json:"NowViewingItem,omitempty"`

	// Gets or sets the play state.
	PlayState *PlayerStateInfo `json:"PlayState,omitempty"`

	// Gets or sets the playable media types.
	PlayableMediaTypes []MediaType `json:"PlayableMediaTypes,omitzero"`

	// Gets or sets the playlist item id.
	PlaylistItemId string `json:"PlaylistItemId,omitempty"`

	// Gets or sets the remote end point.
	RemoteEndPoint string `json:"RemoteEndPoint,omitempty"`

	// Gets or sets the server id.
	ServerId string `json:"ServerId,omitempty"`

	// Gets or sets the supported commands.
	SupportedCommands []GeneralCommandType `json:"SupportedCommands,omitzero"`

	// Gets or sets a value indicating whether the session supports media control.
	SupportsMediaControl *bool `json:"SupportsMediaControl,omitempty"`

	// Gets or sets a value indicating whether the session supports remote control.
	SupportsRemoteControl *bool `json:"SupportsRemoteControl,omitempty"`

	// Gets or sets the transcoding info.
	TranscodingInfo *TranscodingInfo `json:"TranscodingInfo,omitempty"`

	// Gets or sets the user id.
	UserId string `json:"UserId,omitempty"`

	// Gets or sets the username.
	UserName string `json:"UserName,omitempty"`

	// Gets or sets the user primary image tag.
	UserPrimaryImageTag string `json:"UserPrimaryImageTag,omitempty"`
}
