// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// ActivityLogEntryStopMessage is the "ActivityLogEntryStopMessage" schema.
//
// Activity log entry stop message.
type ActivityLogEntryStopMessage struct {
	// The different kinds of messages that are used in the WebSocket api.
	MessageType SessionMessageType `json:"MessageType,omitempty"`
}
