// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// PluginUninstalledMessage is the "PluginUninstalledMessage" schema.
//
// Plugin uninstalled message.
type PluginUninstalledMessage struct {
	// This is a serializable stub class that is used by the api to provide information about installed plugins.
	Data *PluginInfo `json:"Data,omitempty"`

	// Gets or sets the message id.
	MessageId string `json:"MessageId,omitempty"`

	// The different kinds of messages that are used in the WebSocket api.
	MessageType SessionMessageType `json:"MessageType,omitempty"`
}
