// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// MediaUrl is the "MediaUrl" schema.
type MediaUrl struct {
	Name string `json:"Name,omitempty"`
	Url  string `json:"Url,omitempty"`
}
