// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// TranscodingProfile is the "TranscodingProfile" schema.
//
// A class for transcoding profile information.
// Note for client developers: Conditions defined in MediaBrowser.Model.Dlna.CodecProfile has higher priority and can override values defined here.
type TranscodingProfile struct {
	// Gets or sets the audio codec.
	AudioCodec string `json:"AudioCodec,omitempty"`

	// Gets or sets a value indicating whether breaking the video stream on non-keyframes is supported.
	BreakOnNonKeyFrames *bool `json:"BreakOnNonKeyFrames,omitempty"`

	// Gets or sets the profile conditions.
	Conditions []ProfileCondition `json:"Conditions,omitzero"`

	// Gets or sets the container.
	Container string `json:"Container,omitempty"`

	// Gets or sets the encoding context.
	Context EncodingContext `json:"Context,omitempty"`

	// Gets or sets a value indicating whether timestamps should be copied.
	CopyTimestamps *bool `json:"CopyTimestamps,omitempty"`

	// Gets or sets a value indicating whether variable bitrate encoding is supported.
	EnableAudioVbrEncoding *bool `json:"EnableAudioVbrEncoding,omitempty"`

	// Gets or sets a value indicating whether M2TS mode is enabled.
	EnableMpegtsM2TsMode *bool `json:"EnableMpegtsM2TsMode,omitempty"`

	// Gets or sets a value indicating whether subtitles are allowed in the manifest.
	EnableSubtitlesInManifest *bool `json:"EnableSubtitlesInManifest,omitempty"`

	// Gets or sets a value indicating whether the content length should be estimated.
	EstimateContentLength *bool `json:"EstimateContentLength,omitempty"`

	// Gets or sets the maximum audio channels.
	MaxAudioChannels string `json:"MaxAudioChannels,omitempty"`

	// Gets or sets the minimum amount of segments.
	MinSegments int `json:"MinSegments,omitempty"`

	// Media streaming protocol.
	// Lowercase for backwards compatibility.
	Protocol MediaStreamProtocol `json:"Protocol,omitempty"`

	// Gets or sets the segment length.
	SegmentLength int `json:"SegmentLength,omitempty"`

	// Gets or sets the transcoding seek info mode.
	TranscodeSeekInfo TranscodeSeekInfo `json:"TranscodeSeekInfo,omitempty"`

	// Gets or sets the DLNA profile type.
	Type DlnaProfileType `json:"Type,omitempty"`

	// Gets or sets the video codec.
	VideoCodec string `json:"VideoCodec,omitempty"`
}
