// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// SyncPlayGroupLeftUpdate is the "SyncPlayGroupLeftUpdate" schema.
type SyncPlayGroupLeftUpdate struct {
	// Gets the update data.
	Data string `json:"Data,omitempty"`

	// Gets the group identifier.
	GroupId string `json:"GroupId,omitempty"`

	// Enum GroupUpdateType.
	Type GroupUpdateType `json:"Type,omitempty"`
}
