// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// LiveTvOptions is the "LiveTvOptions" schema.
type LiveTvOptions struct {
	EnableOriginalAudioWithEncodedRecordings *bool                  `json:"EnableOriginalAudioWithEncodedRecordings,omitempty"`
	EnableRecordingSubfolders                *bool                  `json:"EnableRecordingSubfolders,omitempty"`
	GuideDays                                int                    `json:"GuideDays,omitempty"`
	ListingProviders                         []ListingsProviderInfo `json:"ListingProviders,omitzero"`
	MediaLocationsCreated                    []string               `json:"MediaLocationsCreated,omitzero"`
	MovieRecordingPath                       string                 `json:"MovieRecordingPath,omitempty"`
	PostPaddingSeconds                       int                    `json:"PostPaddingSeconds,omitempty"`
	PrePaddingSeconds                        int                    `json:"PrePaddingSeconds,omitempty"`
	RecordingPath                            string                 `json:"RecordingPath,omitempty"`
	RecordingPostProcessor                   string                 `json:"RecordingPostProcessor,omitempty"`
	RecordingPostProcessorArguments          string                 `json:"RecordingPostProcessorArguments,omitempty"`
	SaveRecordingImages                      *bool                  `json:"SaveRecordingImages,omitempty"`
	SaveRecordingNFO                         *bool                  `json:"SaveRecordingNFO,omitempty"`
	SeriesRecordingPath                      string                 `json:"SeriesRecordingPath,omitempty"`
	TunerHosts                               []TunerHostInfo        `json:"TunerHosts,omitzero"`
}
