// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// CultureDto is the "CultureDto" schema.
//
// Class CultureDto.
type CultureDto struct {
	// Gets the display name.
	DisplayName string `json:"DisplayName,omitempty"`

	// Gets the name.
	Name string `json:"Name,omitempty"`

	// Gets the name of the three letter ISO language.
	ThreeLetterISOLanguageName  string   `json:"ThreeLetterISOLanguageName,omitempty"`
	ThreeLetterISOLanguageNames []string `json:"ThreeLetterISOLanguageNames,omitzero"`

	// Gets the name of the two letter ISO language.
	TwoLetterISOLanguageName string `json:"TwoLetterISOLanguageName,omitempty"`
}
