// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// ParentalRating is the "ParentalRating" schema.
//
// Class ParentalRating.
type ParentalRating struct {
	// Gets or sets the name.
	Name string `json:"Name,omitempty"`

	// Gets or sets the rating score.
	RatingScore *ParentalRatingScore `json:"RatingScore,omitempty"`

	// Gets or sets the value.
	Value int `json:"Value,omitempty"`
}
