// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// IPlugin is the "IPlugin" schema.
//
// Defines the MediaBrowser.Common.Plugins.IPlugin.
type IPlugin struct {
	// Gets the path to the assembly file.
	AssemblyFilePath string `json:"AssemblyFilePath,omitempty"`

	// Gets a value indicating whether the plugin can be uninstalled.
	CanUninstall *bool `json:"CanUninstall,omitempty"`

	// Gets the full path to the data folder, where the plugin can store any miscellaneous files needed.
	DataFolderPath string `json:"DataFolderPath,omitempty"`

	// Gets the Description.
	Description string `json:"Description,omitempty"`

	// Gets the unique id.
	Id string `json:"Id,omitempty"`

	// Gets the name of the plugin.
	Name string `json:"Name,omitempty"`

	// Gets the plugin version.
	Version string `json:"Version,omitempty"`
}
