// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// GeneralCommandMessage is the "GeneralCommandMessage" schema.
//
// General command websocket message.
type GeneralCommandMessage struct {
	// Gets or sets the data.
	Data *GeneralCommand `json:"Data,omitempty"`

	// Gets or sets the message id.
	MessageId string `json:"MessageId,omitempty"`

	// The different kinds of messages that are used in the WebSocket api.
	MessageType SessionMessageType `json:"MessageType,omitempty"`
}
