// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// BaseItemDtoQueryResult is the "BaseItemDtoQueryResult" schema.
//
// Query result container.
type BaseItemDtoQueryResult struct {
	// Gets or sets the items.
	Items []BaseItemDto `json:"Items,omitzero"`

	// Gets or sets the index of the first record in Items.
	StartIndex int `json:"StartIndex,omitempty"`

	// Gets or sets the total number of records available.
	TotalRecordCount int `json:"TotalRecordCount,omitempty"`
}
