// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// UserUpdatedMessage is the "UserUpdatedMessage" schema.
//
// User updated message.
type UserUpdatedMessage struct {
	// Class UserDto.
	Data *UserDto `json:"Data,omitempty"`

	// Gets or sets the message id.
	MessageId string `json:"MessageId,omitempty"`

	// The different kinds of messages that are used in the WebSocket api.
	MessageType SessionMessageType `json:"MessageType,omitempty"`
}
