// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// DeviceInfoDto is the "DeviceInfoDto" schema.
//
// A DTO representing device information.
type DeviceInfoDto struct {
	// Gets or sets the access token.
	AccessToken string `json:"AccessToken,omitempty"`

	// Gets or sets the name of the application.
	AppName string `json:"AppName,omitempty"`

	// Gets or sets the application version.
	AppVersion string `json:"AppVersion,omitempty"`

	// Gets or sets the capabilities.
	Capabilities *ClientCapabilitiesDto `json:"Capabilities,omitempty"`

	// Gets or sets the custom name.
	CustomName string `json:"CustomName,omitempty"`

	// Gets or sets the date last modified.
	DateLastActivity string `json:"DateLastActivity,omitempty"`

	// Gets or sets the icon URL.
	IconUrl string `json:"IconUrl,omitempty"`

	// Gets or sets the identifier.
	Id string `json:"Id,omitempty"`

	// Gets or sets the last user identifier.
	LastUserId string `json:"LastUserId,omitempty"`

	// Gets or sets the last name of the user.
	LastUserName string `json:"LastUserName,omitempty"`

	// Gets or sets the name.
	Name string `json:"Name,omitempty"`
}
