// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetDirectoryContentsOperationResponse is the result of GetDirectoryContents.
type GetDirectoryContentsOperationResponse struct {
	HttpResponse *http.Response
	Model        []FileSystemEntryInfo
}

// GetDirectoryContentsOperationOptions holds the query and header parameters of GetDirectoryContents.
type GetDirectoryContentsOperationOptions struct {
	// The path.
	Path string

	// An optional filter to include or exclude files from the results. true/false.
	IncludeFiles *bool

	// An optional filter to include or exclude folders from the results. true/false.
	IncludeDirectories *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetDirectoryContentsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetDirectoryContentsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Path != "" {
		out.Append("path", o.Path)
	}
	if o.IncludeFiles != nil {
		out.Append("includeFiles", strconv.FormatBool(*o.IncludeFiles))
	}
	if o.IncludeDirectories != nil {
		out.Append("includeDirectories", strconv.FormatBool(*o.IncludeDirectories))
	}
	return &out
}

// GetDirectoryContents calls GET /Environment/DirectoryContents. Gets the contents of a given directory in the file system.
func (c Client) GetDirectoryContents(ctx context.Context, options GetDirectoryContentsOperationOptions) (result GetDirectoryContentsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/Environment/DirectoryContents",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
