// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// FileSystemEntryType is the "FileSystemEntryType" enum.
//
// Enum FileSystemEntryType.
type FileSystemEntryType string

// Values of FileSystemEntryType.
const (
	FileSystemEntryTypeFile            FileSystemEntryType = "File"
	FileSystemEntryTypeDirectory       FileSystemEntryType = "Directory"
	FileSystemEntryTypeNetworkComputer FileSystemEntryType = "NetworkComputer"
	FileSystemEntryTypeNetworkShare    FileSystemEntryType = "NetworkShare"
)

// PossibleValuesForFileSystemEntryType returns every value of FileSystemEntryType.
func PossibleValuesForFileSystemEntryType() []string {
	return []string{
		string(FileSystemEntryTypeFile),
		string(FileSystemEntryTypeDirectory),
		string(FileSystemEntryTypeNetworkComputer),
		string(FileSystemEntryTypeNetworkShare),
	}
}
