// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetDrivesOperationResponse is the result of GetDrives.
type GetDrivesOperationResponse struct {
	HttpResponse *http.Response
	Model        []FileSystemEntryInfo
}

// GetDrives calls GET /Environment/Drives. Gets available drives from the server's file system.
func (c Client) GetDrives(ctx context.Context) (result GetDrivesOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod: http.MethodGet,
		Path:       "/Environment/Drives",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
