// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"net/http"
	"testing"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

func TestOperationGetQueryFiltersLegacy(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "application/json", "{}")
	result, err := c.GetQueryFiltersLegacy(t.Context(), GetQueryFiltersLegacyOperationOptions{
		UserId:           "v-UserId",
		ParentId:         "v-ParentId",
		IncludeItemTypes: []BaseItemKind{BaseItemKindAggregateFolder, BaseItemKindYear},
		MediaTypes:       []MediaType{MediaTypeUnknown, MediaTypeBook},
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/Items/Filters")
	expectQuery(t, r, "userId", "v-UserId")
	expectQuery(t, r, "parentId", "v-ParentId")
	expectQuery(t, r, "includeItemTypes", "AggregateFolder", "Year")
	expectQuery(t, r, "mediaTypes", "Unknown", "Book")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	if result.Model == nil {
		t.Error("the model was not decoded")
	}

	// an answer that does not decode is an error, with the response
	c, _ = newOperationServer(t, 200, "application/json", "<html>")
	result, err = c.GetQueryFiltersLegacy(t.Context(), GetQueryFiltersLegacyOperationOptions{
		UserId:           "v-UserId",
		ParentId:         "v-ParentId",
		IncludeItemTypes: []BaseItemKind{BaseItemKindAggregateFolder, BaseItemKindYear},
		MediaTypes:       []MediaType{MediaTypeUnknown, MediaTypeBook},
	})
	if err == nil || client.StatusCode(err) != 0 || result.HttpResponse == nil {
		t.Errorf("an answer that does not decode = %v", err)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.GetQueryFiltersLegacy(t.Context(), GetQueryFiltersLegacyOperationOptions{
		UserId:           "v-UserId",
		ParentId:         "v-ParentId",
		IncludeItemTypes: []BaseItemKind{BaseItemKindAggregateFolder, BaseItemKindYear},
		MediaTypes:       []MediaType{MediaTypeUnknown, MediaTypeBook},
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
