// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetGenresOperationResponse is the result of GetGenres.
type GetGenresOperationResponse struct {
	HttpResponse *http.Response
	Model        *BaseItemDtoQueryResult
}

// GetGenresOperationOptions holds the query and header parameters of GetGenres.
type GetGenresOperationOptions struct {
	// Optional. The record index to start at. All items with a lower index will be dropped from the results.
	StartIndex *int

	// Optional. The maximum number of records to return.
	Limit *int

	// The search term.
	SearchTerm string

	// Specify this to localize the search to a specific item or folder. Omit to use the root.
	ParentId string

	// Optional. Specify additional fields of information to return in the output.
	Fields []ItemFields

	// Optional. If specified, results will be filtered out based on item type. This allows multiple, comma delimited.
	ExcludeItemTypes []BaseItemKind

	// Optional. If specified, results will be filtered in based on item type. This allows multiple, comma delimited.
	IncludeItemTypes []BaseItemKind

	// Optional filter by items that are marked as favorite, or not.
	IsFavorite *bool

	// Optional, the max number of images to return, per image type.
	ImageTypeLimit *int

	// Optional. The image types to include in the output.
	EnableImageTypes []ImageType

	// User id.
	UserId string

	// Optional filter by items whose name is sorted equally or greater than a given input string.
	NameStartsWithOrGreater string

	// Optional filter by items whose name is sorted equally than a given input string.
	NameStartsWith string

	// Optional filter by items whose name is equally or lesser than a given input string.
	NameLessThan string

	// Optional. Specify one or more sort orders, comma delimited.
	SortBy []ItemSortBy

	// Sort Order - Ascending,Descending.
	SortOrder []SortOrder

	// Optional, include image information in output.
	EnableImages *bool

	// Optional. Include total record count.
	EnableTotalRecordCount *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetGenresOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetGenresOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.StartIndex != nil {
		out.Append("startIndex", strconv.Itoa(*o.StartIndex))
	}
	if o.Limit != nil {
		out.Append("limit", strconv.Itoa(*o.Limit))
	}
	if o.SearchTerm != "" {
		out.Append("searchTerm", o.SearchTerm)
	}
	if o.ParentId != "" {
		out.Append("parentId", o.ParentId)
	}
	for _, v := range o.Fields {
		out.Append("fields", string(v))
	}
	for _, v := range o.ExcludeItemTypes {
		out.Append("excludeItemTypes", string(v))
	}
	for _, v := range o.IncludeItemTypes {
		out.Append("includeItemTypes", string(v))
	}
	if o.IsFavorite != nil {
		out.Append("isFavorite", strconv.FormatBool(*o.IsFavorite))
	}
	if o.ImageTypeLimit != nil {
		out.Append("imageTypeLimit", strconv.Itoa(*o.ImageTypeLimit))
	}
	for _, v := range o.EnableImageTypes {
		out.Append("enableImageTypes", string(v))
	}
	if o.UserId != "" {
		out.Append("userId", o.UserId)
	}
	if o.NameStartsWithOrGreater != "" {
		out.Append("nameStartsWithOrGreater", o.NameStartsWithOrGreater)
	}
	if o.NameStartsWith != "" {
		out.Append("nameStartsWith", o.NameStartsWith)
	}
	if o.NameLessThan != "" {
		out.Append("nameLessThan", o.NameLessThan)
	}
	for _, v := range o.SortBy {
		out.Append("sortBy", string(v))
	}
	for _, v := range o.SortOrder {
		out.Append("sortOrder", string(v))
	}
	if o.EnableImages != nil {
		out.Append("enableImages", strconv.FormatBool(*o.EnableImages))
	}
	if o.EnableTotalRecordCount != nil {
		out.Append("enableTotalRecordCount", strconv.FormatBool(*o.EnableTotalRecordCount))
	}
	return &out
}

// GetGenres calls GET /Genres. Gets all genres from a given item, folder, or the entire library.
func (c Client) GetGenres(ctx context.Context, options GetGenresOperationOptions) (result GetGenresOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/Genres",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model BaseItemDtoQueryResult
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}

// GetGenresCompleteResult is every result GetGenresComplete loaded.
type GetGenresCompleteResult struct {
	LatestHttpResponse *http.Response
	Items              []BaseItemDto
}

// GetGenresComplete calls GetGenres page by page from options.StartIndex until every
// result is loaded. options.Limit is the page size, client.DefaultPageSize when
// unset.
func (c Client) GetGenresComplete(ctx context.Context, options GetGenresOperationOptions) (result GetGenresCompleteResult, err error) {
	limit := client.DefaultPageSize
	if options.Limit != nil && *options.Limit > 0 {
		limit = *options.Limit
	}
	options.Limit = &limit
	start := 0
	if options.StartIndex != nil {
		start = *options.StartIndex
	}
	for {
		var page GetGenresOperationResponse
		page, err = c.GetGenres(ctx, options)
		result.LatestHttpResponse = page.HttpResponse
		if err != nil {
			err = fmt.Errorf("loading results: %w", err)
			return
		}
		if page.Model == nil || len(page.Model.Items) == 0 {
			return
		}
		result.Items = append(result.Items, page.Model.Items...)
		start += len(page.Model.Items)
		options.StartIndex = &start
		// a short page is the last; so is reaching the total, when the server
		// reports one (some Emby lists report 0 whatever they hold)
		if len(page.Model.Items) < limit || page.Model.TotalRecordCount > 0 && start >= page.Model.TotalRecordCount {
			return
		}
	}
}
