// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"net/http"
	"testing"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

func TestOperationDeleteItemImageByIndex(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 204, "", "")
	result, err := c.DeleteItemImageByIndex(t.Context(), "p/itemId", ImageTypePrimary, 7)
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodDelete, "/Items/p%2FitemId/Images/Primary/7")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 204 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.DeleteItemImageByIndex(t.Context(), "p/itemId", ImageTypePrimary, 7)
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
