// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"net/http"
	"strings"
	"testing"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

func TestOperationSetItemImage(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 204, "", "")
	result, err := c.SetItemImage(t.Context(), "p/itemId", ImageTypePrimary, strings.NewReader("raw bytes"), "image/png")
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	expectRequest(t, r, http.MethodPost, "/Items/p%2FitemId/Images/Primary")
	if got := r.Header.Get("Content-Type"); got != "image/png" {
		t.Errorf("Content-Type = %q, want %q", got, "image/png")
	}
	if body != "raw bytes" {
		t.Errorf("body = %q, want the raw bytes", body)
	}
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 204 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.SetItemImage(t.Context(), "p/itemId", ImageTypePrimary, strings.NewReader("raw bytes"), "image/png")
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
