// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// ImageInfo is the "ImageInfo" schema.
//
// Class ImageInfo.
type ImageInfo struct {
	// Gets or sets the blurhash.
	BlurHash string `json:"BlurHash,omitempty"`

	// Gets or sets the height.
	Height int `json:"Height,omitempty"`

	// Gets or sets the index of the image.
	ImageIndex int `json:"ImageIndex,omitempty"`

	// Gets or sets the image tag.
	ImageTag string `json:"ImageTag,omitempty"`

	// Gets or sets the type of the image.
	ImageType ImageType `json:"ImageType,omitempty"`

	// Gets or sets the path.
	Path string `json:"Path,omitempty"`

	// Gets or sets the size.
	Size int64 `json:"Size,omitempty"`

	// Gets or sets the width.
	Width int `json:"Width,omitempty"`
}
