// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"net/http"
	"testing"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

func TestOperationGetInstantMixFromMusicGenreById(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "application/json", "{}")
	result, err := c.GetInstantMixFromMusicGenreById(t.Context(), GetInstantMixFromMusicGenreByIdOperationOptions{
		Id:               "v-Id",
		UserId:           "v-UserId",
		Limit:            7,
		Fields:           []ItemFields{ItemFieldsAirTime, ItemFieldsSpecialFeatureCount},
		EnableImages:     new(true),
		EnableUserData:   new(true),
		ImageTypeLimit:   7,
		EnableImageTypes: []ImageType{ImageTypePrimary, ImageTypeProfile},
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/MusicGenres/InstantMix")
	expectQuery(t, r, "id", "v-Id")
	expectQuery(t, r, "userId", "v-UserId")
	expectQuery(t, r, "limit", "7")
	expectQuery(t, r, "fields", "AirTime", "SpecialFeatureCount")
	expectQuery(t, r, "enableImages", "true")
	expectQuery(t, r, "enableUserData", "true")
	expectQuery(t, r, "imageTypeLimit", "7")
	expectQuery(t, r, "enableImageTypes", "Primary", "Profile")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	if result.Model == nil {
		t.Error("the model was not decoded")
	}

	// an answer that does not decode is an error, with the response
	c, _ = newOperationServer(t, 200, "application/json", "<html>")
	result, err = c.GetInstantMixFromMusicGenreById(t.Context(), GetInstantMixFromMusicGenreByIdOperationOptions{
		Id:               "v-Id",
		UserId:           "v-UserId",
		Limit:            7,
		Fields:           []ItemFields{ItemFieldsAirTime, ItemFieldsSpecialFeatureCount},
		EnableImages:     new(true),
		EnableUserData:   new(true),
		ImageTypeLimit:   7,
		EnableImageTypes: []ImageType{ImageTypePrimary, ImageTypeProfile},
	})
	if err == nil || client.StatusCode(err) != 0 || result.HttpResponse == nil {
		t.Errorf("an answer that does not decode = %v", err)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.GetInstantMixFromMusicGenreById(t.Context(), GetInstantMixFromMusicGenreByIdOperationOptions{
		Id:               "v-Id",
		UserId:           "v-UserId",
		Limit:            7,
		Fields:           []ItemFields{ItemFieldsAirTime, ItemFieldsSpecialFeatureCount},
		EnableImages:     new(true),
		EnableUserData:   new(true),
		ImageTypeLimit:   7,
		EnableImageTypes: []ImageType{ImageTypePrimary, ImageTypeProfile},
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
