// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// BookInfoRemoteSearchQuery is the "BookInfoRemoteSearchQuery" schema.
type BookInfoRemoteSearchQuery struct {
	// Gets or sets a value indicating whether disabled providers should be included.
	IncludeDisabledProviders *bool  `json:"IncludeDisabledProviders,omitempty"`
	ItemId                   string `json:"ItemId,omitempty"`

	// The lookup info for books.
	SearchInfo *BookInfo `json:"SearchInfo,omitempty"`

	// Gets or sets the provider name to search within if set.
	SearchProviderName string `json:"SearchProviderName,omitempty"`
}
