// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// RemoteSearchResult is the "RemoteSearchResult" schema.
type RemoteSearchResult struct {
	AlbumArtist    *RemoteSearchResult  `json:"AlbumArtist,omitempty"`
	Artists        []RemoteSearchResult `json:"Artists,omitzero"`
	ImageUrl       string               `json:"ImageUrl,omitempty"`
	IndexNumber    int                  `json:"IndexNumber,omitempty"`
	IndexNumberEnd int                  `json:"IndexNumberEnd,omitempty"`

	// Gets or sets the name.
	Name              string `json:"Name,omitempty"`
	Overview          string `json:"Overview,omitempty"`
	ParentIndexNumber int    `json:"ParentIndexNumber,omitempty"`
	PremiereDate      string `json:"PremiereDate,omitempty"`

	// Gets or sets the year.
	ProductionYear int `json:"ProductionYear,omitempty"`

	// Gets or sets the provider ids.
	ProviderIds        map[string]string `json:"ProviderIds,omitzero"`
	SearchProviderName string            `json:"SearchProviderName,omitempty"`
}
