// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetBoxSetRemoteSearchResultsOperationResponse is the result of GetBoxSetRemoteSearchResults.
type GetBoxSetRemoteSearchResultsOperationResponse struct {
	HttpResponse *http.Response
	Model        []RemoteSearchResult
}

// GetBoxSetRemoteSearchResults calls POST /Items/RemoteSearch/BoxSet. Get box set remote search.
func (c Client) GetBoxSetRemoteSearchResults(ctx context.Context, input BoxSetInfoRemoteSearchQuery) (result GetBoxSetRemoteSearchResultsOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodPost,
		Path:       "/Items/RemoteSearch/BoxSet",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
