// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// UpdateItemContentTypeOperationResponse is the result of UpdateItemContentType.
type UpdateItemContentTypeOperationResponse struct {
	HttpResponse *http.Response
}

// UpdateItemContentTypeOperationOptions holds the query and header parameters of UpdateItemContentType.
type UpdateItemContentTypeOperationOptions struct {
	// The content type of the item.
	ContentType string
}

// ToHeaders returns the header parameters the options set.
func (o UpdateItemContentTypeOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o UpdateItemContentTypeOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.ContentType != "" {
		out.Append("contentType", o.ContentType)
	}
	return &out
}

// UpdateItemContentType calls POST /Items/{itemId}/ContentType. Updates an item's content type.
func (c Client) UpdateItemContentType(ctx context.Context, itemId string, options UpdateItemContentTypeOperationOptions) (result UpdateItemContentTypeOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusNoContent,
		},
		HTTPMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          fmt.Sprintf("/Items/%s/ContentType", url.PathEscape(itemId)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
