// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetTrailerRemoteSearchResultsOperationResponse is the result of GetTrailerRemoteSearchResults.
type GetTrailerRemoteSearchResultsOperationResponse struct {
	HttpResponse *http.Response
	Model        []RemoteSearchResult
}

// GetTrailerRemoteSearchResults calls POST /Items/RemoteSearch/Trailer. Get trailer remote search.
func (c Client) GetTrailerRemoteSearchResults(ctx context.Context, input TrailerInfoRemoteSearchQuery) (result GetTrailerRemoteSearchResultsOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod: http.MethodPost,
		Path:       "/Items/RemoteSearch/Trailer",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
