// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// MusicVideoInfoRemoteSearchQuery is the "MusicVideoInfoRemoteSearchQuery" schema.
type MusicVideoInfoRemoteSearchQuery struct {
	// Gets or sets a value indicating whether disabled providers should be included.
	IncludeDisabledProviders *bool           `json:"IncludeDisabledProviders,omitempty"`
	ItemId                   string          `json:"ItemId,omitempty"`
	SearchInfo               *MusicVideoInfo `json:"SearchInfo,omitempty"`

	// Gets or sets the provider name to search within if set.
	SearchProviderName string `json:"SearchProviderName,omitempty"`
}
