// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// ApplySearchCriteriaOperationResponse is the result of ApplySearchCriteria.
type ApplySearchCriteriaOperationResponse struct {
	HttpResponse *http.Response
}

// ApplySearchCriteriaOperationOptions holds the query and header parameters of ApplySearchCriteria.
type ApplySearchCriteriaOperationOptions struct {
	// Optional. Whether or not to replace all images. Default: True.
	ReplaceAllImages *bool
}

// ToHeaders returns the header parameters the options set.
func (o ApplySearchCriteriaOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o ApplySearchCriteriaOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.ReplaceAllImages != nil {
		out.Append("replaceAllImages", strconv.FormatBool(*o.ReplaceAllImages))
	}
	return &out
}

// ApplySearchCriteria calls POST /Items/RemoteSearch/Apply/{itemId}. Applies search criteria to an item and refreshes metadata.
func (c Client) ApplySearchCriteria(ctx context.Context, itemId string, input RemoteSearchResult, options ApplySearchCriteriaOperationOptions) (result ApplySearchCriteriaOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusNoContent,
		},
		HTTPMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          fmt.Sprintf("/Items/RemoteSearch/Apply/%s", url.PathEscape(itemId)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
