// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// AddVirtualFolderDto is the "AddVirtualFolderDto" schema.
//
// Add virtual folder dto.
type AddVirtualFolderDto struct {
	// Gets or sets library options.
	LibraryOptions *LibraryOptions `json:"LibraryOptions,omitempty"`
}
