// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetSimilarShowsOperationResponse is the result of GetSimilarShows.
type GetSimilarShowsOperationResponse struct {
	HttpResponse *http.Response
	Model        *BaseItemDtoQueryResult
}

// GetSimilarShowsOperationOptions holds the query and header parameters of GetSimilarShows.
type GetSimilarShowsOperationOptions struct {
	// Exclude artist ids.
	ExcludeArtistIds []string

	// Optional. Filter by user id, and attach user data.
	UserId string

	// Optional. The maximum number of records to return.
	Limit *int

	// Optional. Specify additional fields of information to return in the output. This allows multiple, comma delimited. Options: Budget, Chapters, DateCreated, Genres, HomePageUrl, IndexOptions, MediaStreams, Overview, ParentId, Path, People, ProviderIds, PrimaryImageAspectRatio, Revenue, SortName, Studios, Taglines, TrailerUrls.
	Fields []ItemFields
}

// ToHeaders returns the header parameters the options set.
func (o GetSimilarShowsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetSimilarShowsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	for _, v := range o.ExcludeArtistIds {
		out.Append("excludeArtistIds", v)
	}
	if o.UserId != "" {
		out.Append("userId", o.UserId)
	}
	if o.Limit != nil {
		out.Append("limit", strconv.Itoa(*o.Limit))
	}
	for _, v := range o.Fields {
		out.Append("fields", string(v))
	}
	return &out
}

// GetSimilarShows calls GET /Shows/{itemId}/Similar. Gets similar items.
func (c Client) GetSimilarShows(ctx context.Context, itemId string, options GetSimilarShowsOperationOptions) (result GetSimilarShowsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          fmt.Sprintf("/Shows/%s/Similar", url.PathEscape(itemId)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model BaseItemDtoQueryResult
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
