// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// AddVirtualFolderOperationResponse is the result of AddVirtualFolder.
type AddVirtualFolderOperationResponse struct {
	HttpResponse *http.Response
}

// AddVirtualFolderOperationOptions holds the query and header parameters of AddVirtualFolder.
type AddVirtualFolderOperationOptions struct {
	// The name of the virtual folder.
	Name string

	// The type of the collection.
	CollectionType CollectionTypeOptions

	// The paths of the virtual folder.
	Paths []string

	// Whether to refresh the library.
	RefreshLibrary *bool
}

// ToHeaders returns the header parameters the options set.
func (o AddVirtualFolderOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o AddVirtualFolderOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Name != "" {
		out.Append("name", o.Name)
	}
	if o.CollectionType != "" {
		out.Append("collectionType", string(o.CollectionType))
	}
	for _, v := range o.Paths {
		out.Append("paths", v)
	}
	if o.RefreshLibrary != nil {
		out.Append("refreshLibrary", strconv.FormatBool(*o.RefreshLibrary))
	}
	return &out
}

// AddVirtualFolder calls POST /Library/VirtualFolders. Adds a virtual folder.
func (c Client) AddVirtualFolder(ctx context.Context, input AddVirtualFolderDto, options AddVirtualFolderOperationOptions) (result AddVirtualFolderOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusNoContent,
		},
		HttpMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          "/Library/VirtualFolders",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
