// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// RemoveVirtualFolderOperationResponse is the result of RemoveVirtualFolder.
type RemoveVirtualFolderOperationResponse struct {
	HttpResponse *http.Response
}

// RemoveVirtualFolderOperationOptions holds the query and header parameters of RemoveVirtualFolder.
type RemoveVirtualFolderOperationOptions struct {
	// The name of the folder.
	Name string

	// Whether to refresh the library.
	RefreshLibrary *bool
}

// ToHeaders returns the header parameters the options set.
func (o RemoveVirtualFolderOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o RemoveVirtualFolderOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Name != "" {
		out.Append("name", o.Name)
	}
	if o.RefreshLibrary != nil {
		out.Append("refreshLibrary", strconv.FormatBool(*o.RefreshLibrary))
	}
	return &out
}

// RemoveVirtualFolder calls DELETE /Library/VirtualFolders. Removes a virtual folder.
func (c Client) RemoveVirtualFolder(ctx context.Context, options RemoveVirtualFolderOperationOptions) (result RemoveVirtualFolderOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusNoContent,
		},
		HttpMethod:    http.MethodDelete,
		OptionsObject: options,
		Path:          "/Library/VirtualFolders",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
