// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"net/http"
	"testing"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

func TestOperationGetSimilarTrailers(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "application/json", "{}")
	result, err := c.GetSimilarTrailers(t.Context(), "p/itemId", GetSimilarTrailersOperationOptions{
		ExcludeArtistIds: []string{"a", "b"},
		UserId:           "v-UserId",
		Limit:            new(7),
		Fields:           []ItemFields{ItemFieldsAirTime, ItemFieldsSpecialFeatureCount},
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/Trailers/p%2FitemId/Similar")
	expectQuery(t, r, "excludeArtistIds", "a", "b")
	expectQuery(t, r, "userId", "v-UserId")
	expectQuery(t, r, "limit", "7")
	expectQuery(t, r, "fields", "AirTime", "SpecialFeatureCount")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	if result.Model == nil {
		t.Error("the model was not decoded")
	}

	// an answer that does not decode is an error, with the response
	c, _ = newOperationServer(t, 200, "application/json", "<html>")
	result, err = c.GetSimilarTrailers(t.Context(), "p/itemId", GetSimilarTrailersOperationOptions{
		ExcludeArtistIds: []string{"a", "b"},
		UserId:           "v-UserId",
		Limit:            new(7),
		Fields:           []ItemFields{ItemFieldsAirTime, ItemFieldsSpecialFeatureCount},
	})
	if err == nil || client.StatusCode(err) != 0 || result.HttpResponse == nil {
		t.Errorf("an answer that does not decode = %v", err)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.GetSimilarTrailers(t.Context(), "p/itemId", GetSimilarTrailersOperationOptions{
		ExcludeArtistIds: []string{"a", "b"},
		UserId:           "v-UserId",
		Limit:            new(7),
		Fields:           []ItemFields{ItemFieldsAirTime, ItemFieldsSpecialFeatureCount},
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
