// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetPhysicalPathsOperationResponse is the result of GetPhysicalPaths.
type GetPhysicalPathsOperationResponse struct {
	HttpResponse *http.Response
	Model        []string
}

// GetPhysicalPaths calls GET /Library/PhysicalPaths. Gets a list of physical paths from virtual folders.
func (c Client) GetPhysicalPaths(ctx context.Context) (result GetPhysicalPathsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/Library/PhysicalPaths",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
