// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"encoding/json"
	"net/http"
	"testing"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

func TestOperationAddVirtualFolder(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 204, "", "")
	result, err := c.AddVirtualFolder(t.Context(), AddVirtualFolderDto{}, AddVirtualFolderOperationOptions{
		Name:           "v-Name",
		CollectionType: CollectionTypeOptionsMovies,
		Paths:          []string{"a", "b"},
		RefreshLibrary: new(true),
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodPost, "/Library/VirtualFolders")
	expectQuery(t, r, "name", "v-Name")
	expectQuery(t, r, "collectionType", "movies")
	expectQuery(t, r, "paths", "a", "b")
	expectQuery(t, r, "refreshLibrary", "true")
	if got := r.Header.Get("Content-Type"); got != "application/json" {
		t.Errorf("Content-Type = %q, want %q", got, "application/json")
	}
	if !json.Valid([]byte(body)) {
		t.Errorf("body = %q, want JSON", body)
	}
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 204 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.AddVirtualFolder(t.Context(), AddVirtualFolderDto{}, AddVirtualFolderOperationOptions{
		Name:           "v-Name",
		CollectionType: CollectionTypeOptionsMovies,
		Paths:          []string{"a", "b"},
		RefreshLibrary: new(true),
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
