// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// UpdateSeriesTimerOperationResponse is the result of UpdateSeriesTimer.
type UpdateSeriesTimerOperationResponse struct {
	HttpResponse *http.Response
}

// UpdateSeriesTimer calls POST /LiveTv/SeriesTimers/{timerId}. Updates a live tv series timer.
func (c Client) UpdateSeriesTimer(ctx context.Context, timerId string, input SeriesTimerInfoDto) (result UpdateSeriesTimerOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusNoContent,
		},
		HttpMethod: http.MethodPost,
		Path:       fmt.Sprintf("/LiveTv/SeriesTimers/%s", url.PathEscape(timerId)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
