// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// CancelTimerOperationResponse is the result of CancelTimer.
type CancelTimerOperationResponse struct {
	HttpResponse *http.Response
}

// CancelTimer calls DELETE /LiveTv/Timers/{timerId}. Cancels a live tv timer.
func (c Client) CancelTimer(ctx context.Context, timerId string) (result CancelTimerOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusNoContent,
		},
		HttpMethod: http.MethodDelete,
		Path:       fmt.Sprintf("/LiveTv/Timers/%s", url.PathEscape(timerId)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
