// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// ListingsProviderInfo is the "ListingsProviderInfo" schema.
type ListingsProviderInfo struct {
	ChannelMappings   []NameValuePair `json:"ChannelMappings,omitzero"`
	Country           string          `json:"Country,omitempty"`
	EnableAllTuners   *bool           `json:"EnableAllTuners,omitempty"`
	EnabledTuners     []string        `json:"EnabledTuners,omitzero"`
	Id                string          `json:"Id,omitempty"`
	KidsCategories    []string        `json:"KidsCategories,omitzero"`
	ListingsId        string          `json:"ListingsId,omitempty"`
	MovieCategories   []string        `json:"MovieCategories,omitzero"`
	MoviePrefix       string          `json:"MoviePrefix,omitempty"`
	NewsCategories    []string        `json:"NewsCategories,omitzero"`
	Password          string          `json:"Password,omitempty"`
	Path              string          `json:"Path,omitempty"`
	PreferredLanguage string          `json:"PreferredLanguage,omitempty"`
	SportsCategories  []string        `json:"SportsCategories,omitzero"`
	Type              string          `json:"Type,omitempty"`
	UserAgent         string          `json:"UserAgent,omitempty"`
	Username          string          `json:"Username,omitempty"`
	ZipCode           string          `json:"ZipCode,omitempty"`
}
