// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// CreateSeriesTimerOperationResponse is the result of CreateSeriesTimer.
type CreateSeriesTimerOperationResponse struct {
	HttpResponse *http.Response
}

// CreateSeriesTimer calls POST /LiveTv/SeriesTimers. Creates a live tv series timer.
func (c Client) CreateSeriesTimer(ctx context.Context, input SeriesTimerInfoDto) (result CreateSeriesTimerOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodPost,
		Path:       "/LiveTv/SeriesTimers",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
