// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetRecordingsOperationResponse is the result of GetRecordings.
type GetRecordingsOperationResponse struct {
	HttpResponse *http.Response
	Model        *BaseItemDtoQueryResult
}

// GetRecordingsOperationOptions holds the query and header parameters of GetRecordings.
type GetRecordingsOperationOptions struct {
	// Optional. Filter by channel id.
	ChannelId string

	// Optional. Filter by user and attach user data.
	UserId string

	// Optional. The record index to start at. All items with a lower index will be dropped from the results.
	StartIndex *int

	// Optional. The maximum number of records to return.
	Limit *int

	// Optional. Filter by recording status.
	Status RecordingStatus

	// Optional. Filter by recordings that are in progress, or not.
	IsInProgress *bool

	// Optional. Filter by recordings belonging to a series timer.
	SeriesTimerId string

	// Optional. Include image information in output.
	EnableImages *bool

	// Optional. The max number of images to return, per image type.
	ImageTypeLimit *int

	// Optional. The image types to include in the output.
	EnableImageTypes []ImageType

	// Optional. Specify additional fields of information to return in the output.
	Fields []ItemFields

	// Optional. Include user data.
	EnableUserData *bool

	// Optional. Filter for movies.
	IsMovie *bool

	// Optional. Filter for series.
	IsSeries *bool

	// Optional. Filter for kids.
	IsKids *bool

	// Optional. Filter for sports.
	IsSports *bool

	// Optional. Filter for news.
	IsNews *bool

	// Optional. Filter for is library item.
	IsLibraryItem *bool

	// Optional. Return total record count.
	EnableTotalRecordCount *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetRecordingsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetRecordingsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.ChannelId != "" {
		out.Append("channelId", o.ChannelId)
	}
	if o.UserId != "" {
		out.Append("userId", o.UserId)
	}
	if o.StartIndex != nil {
		out.Append("startIndex", strconv.Itoa(*o.StartIndex))
	}
	if o.Limit != nil {
		out.Append("limit", strconv.Itoa(*o.Limit))
	}
	if o.Status != "" {
		out.Append("status", string(o.Status))
	}
	if o.IsInProgress != nil {
		out.Append("isInProgress", strconv.FormatBool(*o.IsInProgress))
	}
	if o.SeriesTimerId != "" {
		out.Append("seriesTimerId", o.SeriesTimerId)
	}
	if o.EnableImages != nil {
		out.Append("enableImages", strconv.FormatBool(*o.EnableImages))
	}
	if o.ImageTypeLimit != nil {
		out.Append("imageTypeLimit", strconv.Itoa(*o.ImageTypeLimit))
	}
	for _, v := range o.EnableImageTypes {
		out.Append("enableImageTypes", string(v))
	}
	for _, v := range o.Fields {
		out.Append("fields", string(v))
	}
	if o.EnableUserData != nil {
		out.Append("enableUserData", strconv.FormatBool(*o.EnableUserData))
	}
	if o.IsMovie != nil {
		out.Append("isMovie", strconv.FormatBool(*o.IsMovie))
	}
	if o.IsSeries != nil {
		out.Append("isSeries", strconv.FormatBool(*o.IsSeries))
	}
	if o.IsKids != nil {
		out.Append("isKids", strconv.FormatBool(*o.IsKids))
	}
	if o.IsSports != nil {
		out.Append("isSports", strconv.FormatBool(*o.IsSports))
	}
	if o.IsNews != nil {
		out.Append("isNews", strconv.FormatBool(*o.IsNews))
	}
	if o.IsLibraryItem != nil {
		out.Append("isLibraryItem", strconv.FormatBool(*o.IsLibraryItem))
	}
	if o.EnableTotalRecordCount != nil {
		out.Append("enableTotalRecordCount", strconv.FormatBool(*o.EnableTotalRecordCount))
	}
	return &out
}

// GetRecordings calls GET /LiveTv/Recordings. Gets live tv recordings.
func (c Client) GetRecordings(ctx context.Context, options GetRecordingsOperationOptions) (result GetRecordingsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/LiveTv/Recordings",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model BaseItemDtoQueryResult
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}

// GetRecordingsCompleteResult is every result GetRecordingsComplete loaded.
type GetRecordingsCompleteResult struct {
	LatestHttpResponse *http.Response
	Items              []BaseItemDto
}

// GetRecordingsComplete calls GetRecordings page by page from options.StartIndex until every
// result is loaded. options.Limit is the page size, client.DefaultPageSize when
// unset.
func (c Client) GetRecordingsComplete(ctx context.Context, options GetRecordingsOperationOptions) (result GetRecordingsCompleteResult, err error) {
	limit := client.DefaultPageSize
	if options.Limit != nil && *options.Limit > 0 {
		limit = *options.Limit
	}
	options.Limit = &limit
	start := 0
	if options.StartIndex != nil {
		start = *options.StartIndex
	}
	for {
		var page GetRecordingsOperationResponse
		page, err = c.GetRecordings(ctx, options)
		result.LatestHttpResponse = page.HttpResponse
		if err != nil {
			err = fmt.Errorf("loading results: %w", err)
			return
		}
		if page.Model == nil || len(page.Model.Items) == 0 {
			return
		}
		result.Items = append(result.Items, page.Model.Items...)
		start += len(page.Model.Items)
		options.StartIndex = &start
		// a short page is the last; so is reaching the total, when the server
		// reports one (some Emby lists report 0 whatever they hold)
		if len(page.Model.Items) < limit || page.Model.TotalRecordCount > 0 && start >= page.Model.TotalRecordCount {
			return
		}
	}
}
