// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetGuideInfoOperationResponse is the result of GetGuideInfo.
type GetGuideInfoOperationResponse struct {
	HttpResponse *http.Response
	Model        *GuideInfo
}

// GetGuideInfo calls GET /LiveTv/GuideInfo. Get guide info.
func (c Client) GetGuideInfo(ctx context.Context) (result GetGuideInfoOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/LiveTv/GuideInfo",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model GuideInfo
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
