// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// LyricDto is the "LyricDto" schema.
//
// LyricResponse model.
type LyricDto struct {
	// Gets or sets a collection of individual lyric lines.
	Lyrics []LyricLine `json:"Lyrics,omitzero"`

	// Gets or sets Metadata for the lyrics.
	Metadata *LyricMetadata `json:"Metadata,omitempty"`
}
