// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// UploadLyricsOperationResponse is the result of UploadLyrics.
type UploadLyricsOperationResponse struct {
	HttpResponse *http.Response
	Model        *LyricDto
}

// UploadLyricsOperationOptions holds the query and header parameters of UploadLyrics.
type UploadLyricsOperationOptions struct {
	// Name of the file being uploaded.
	FileName string
}

// ToHeaders returns the header parameters the options set.
func (o UploadLyricsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o UploadLyricsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.FileName != "" {
		out.Append("fileName", o.FileName)
	}
	return &out
}

// UploadLyrics calls POST /Audio/{itemId}/Lyrics. Upload an external lyric file.
//
// input is sent as contentType, or as text/plain when that is empty.
func (c Client) UploadLyrics(ctx context.Context, itemId string, input io.Reader, contentType string, options UploadLyricsOperationOptions) (result UploadLyricsOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "text/plain",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          fmt.Sprintf("/Audio/%s/Lyrics", url.PathEscape(itemId)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.SetBody(input, contentType); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model LyricDto
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
