// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetLyricsOperationResponse is the result of GetLyrics.
type GetLyricsOperationResponse struct {
	HttpResponse *http.Response
	Model        *LyricDto
}

// GetLyrics calls GET /Audio/{itemId}/Lyrics. Gets an item's lyrics.
func (c Client) GetLyrics(ctx context.Context, itemId string) (result GetLyricsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod: http.MethodGet,
		Path:       fmt.Sprintf("/Audio/%s/Lyrics", url.PathEscape(itemId)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model LyricDto
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
