// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// CloseLiveStreamOperationResponse is the result of CloseLiveStream.
type CloseLiveStreamOperationResponse struct {
	HttpResponse *http.Response
}

// CloseLiveStreamOperationOptions holds the query and header parameters of CloseLiveStream.
type CloseLiveStreamOperationOptions struct {
	// The livestream id.
	LiveStreamId string
}

// ToHeaders returns the header parameters the options set.
func (o CloseLiveStreamOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o CloseLiveStreamOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.LiveStreamId != "" {
		out.Append("liveStreamId", o.LiveStreamId)
	}
	return &out
}

// CloseLiveStream calls POST /LiveStreams/Close. Closes a media source.
func (c Client) CloseLiveStream(ctx context.Context, options CloseLiveStreamOperationOptions) (result CloseLiveStreamOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusNoContent,
		},
		HttpMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          "/LiveStreams/Close",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
