// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// PlaybackInfoResponse is the "PlaybackInfoResponse" schema.
//
// Class PlaybackInfoResponse.
type PlaybackInfoResponse struct {
	// Gets or sets the error code.
	ErrorCode PlaybackErrorCode `json:"ErrorCode,omitempty"`

	// Gets or sets the media sources.
	MediaSources []MediaSourceInfo `json:"MediaSources,omitzero"`

	// Gets or sets the play session identifier.
	PlaySessionId string `json:"PlaySessionId,omitempty"`
}
