// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// PlaybackInfoDto is the "PlaybackInfoDto" schema.
//
// Playback info dto.
type PlaybackInfoDto struct {
	// Gets or sets a value indicating whether to allow audio stream copy.
	AllowAudioStreamCopy *bool `json:"AllowAudioStreamCopy,omitempty"`

	// Gets or sets a value indicating whether to enable video stream copy.
	AllowVideoStreamCopy *bool `json:"AllowVideoStreamCopy,omitempty"`

	// Gets or sets a value indicating whether always burn in subtitles when transcoding.
	AlwaysBurnInSubtitleWhenTranscoding *bool `json:"AlwaysBurnInSubtitleWhenTranscoding,omitempty"`

	// Gets or sets the audio stream index.
	AudioStreamIndex int `json:"AudioStreamIndex,omitempty"`

	// Gets or sets a value indicating whether to auto open the live stream.
	AutoOpenLiveStream *bool `json:"AutoOpenLiveStream,omitempty"`

	// Gets or sets the device profile.
	DeviceProfile *DeviceProfile `json:"DeviceProfile,omitempty"`

	// Gets or sets a value indicating whether to enable direct play.
	EnableDirectPlay *bool `json:"EnableDirectPlay,omitempty"`

	// Gets or sets a value indicating whether to enable direct stream.
	EnableDirectStream *bool `json:"EnableDirectStream,omitempty"`

	// Gets or sets a value indicating whether to enable transcoding.
	EnableTranscoding *bool `json:"EnableTranscoding,omitempty"`

	// Gets or sets the live stream id.
	LiveStreamId string `json:"LiveStreamId,omitempty"`

	// Gets or sets the max audio channels.
	MaxAudioChannels int `json:"MaxAudioChannels,omitempty"`

	// Gets or sets the max streaming bitrate.
	MaxStreamingBitrate int `json:"MaxStreamingBitrate,omitempty"`

	// Gets or sets the media source id.
	MediaSourceId string `json:"MediaSourceId,omitempty"`

	// Gets or sets the start time in ticks.
	StartTimeTicks int64 `json:"StartTimeTicks,omitempty"`

	// Gets or sets the subtitle stream index.
	SubtitleStreamIndex int `json:"SubtitleStreamIndex,omitempty"`

	// Gets or sets the playback userId.
	UserId string `json:"UserId,omitempty"`
}
