// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetItemSegmentsOperationResponse is the result of GetItemSegments.
type GetItemSegmentsOperationResponse struct {
	HttpResponse *http.Response
	Model        *MediaSegmentDtoQueryResult
}

// GetItemSegmentsOperationOptions holds the query and header parameters of GetItemSegments.
type GetItemSegmentsOperationOptions struct {
	// Optional filter of requested segment types.
	IncludeSegmentTypes []MediaSegmentType
}

// ToHeaders returns the header parameters the options set.
func (o GetItemSegmentsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetItemSegmentsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	for _, v := range o.IncludeSegmentTypes {
		out.Append("includeSegmentTypes", string(v))
	}
	return &out
}

// GetItemSegments calls GET /MediaSegments/{itemId}. Gets all media segments based on an itemId.
func (c Client) GetItemSegments(ctx context.Context, itemId string, options GetItemSegmentsOperationOptions) (result GetItemSegmentsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          fmt.Sprintf("/MediaSegments/%s", url.PathEscape(itemId)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model MediaSegmentDtoQueryResult
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
