// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// OpenLiveStreamDto is the "OpenLiveStreamDto" schema.
//
// Open live stream dto.
type OpenLiveStreamDto struct {
	// Gets or sets a value indicating whether always burn in subtitles when transcoding.
	AlwaysBurnInSubtitleWhenTranscoding *bool `json:"AlwaysBurnInSubtitleWhenTranscoding,omitempty"`

	// Gets or sets the audio stream index.
	AudioStreamIndex int `json:"AudioStreamIndex,omitempty"`

	// A MediaBrowser.Model.Dlna.DeviceProfile represents a set of metadata which determines which content a certain device is able to play.
	//
	//
	// Specifically, it defines the supported <see cref="P:MediaBrowser.Model.Dlna.DeviceProfile.ContainerProfiles">containers</see> and
	// <see cref="P:MediaBrowser.Model.Dlna.DeviceProfile.CodecProfiles">codecs</see> (video and/or audio, including codec profiles and levels)
	// the device is able to direct play (without transcoding or remuxing),
	// as well as which <see cref="P:MediaBrowser.Model.Dlna.DeviceProfile.TranscodingProfiles">containers/codecs to transcode to</see> in case it isn't.
	DeviceProfile *DeviceProfile `json:"DeviceProfile,omitempty"`

	// Gets or sets the device play protocols.
	DirectPlayProtocols []MediaProtocol `json:"DirectPlayProtocols,omitzero"`

	// Gets or sets a value indicating whether to enable direct play.
	EnableDirectPlay *bool `json:"EnableDirectPlay,omitempty"`

	// Gets or sets a value indicating whether to enable direct stream.
	EnableDirectStream *bool `json:"EnableDirectStream,omitempty"`

	// Gets or sets the item id.
	ItemId string `json:"ItemId,omitempty"`

	// Gets or sets the max audio channels.
	MaxAudioChannels int `json:"MaxAudioChannels,omitempty"`

	// Gets or sets the max streaming bitrate.
	MaxStreamingBitrate int `json:"MaxStreamingBitrate,omitempty"`

	// Gets or sets the open token.
	OpenToken string `json:"OpenToken,omitempty"`

	// Gets or sets the play session id.
	PlaySessionId string `json:"PlaySessionId,omitempty"`

	// Gets or sets the start time in ticks.
	StartTimeTicks int64 `json:"StartTimeTicks,omitempty"`

	// Gets or sets the subtitle stream index.
	SubtitleStreamIndex int `json:"SubtitleStreamIndex,omitempty"`

	// Gets or sets the user id.
	UserId string `json:"UserId,omitempty"`
}
