// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetPersonsOperationResponse is the result of GetPersons.
type GetPersonsOperationResponse struct {
	HttpResponse *http.Response
	Model        *BaseItemDtoQueryResult
}

// GetPersonsOperationOptions holds the query and header parameters of GetPersons.
type GetPersonsOperationOptions struct {
	// Optional. All items with a lower index will be dropped from the response.
	StartIndex *int

	// Optional. The maximum number of records to return.
	Limit *int

	// The search term.
	SearchTerm string

	// Optional. Filter by items whose name starts with the given input string.
	NameStartsWith string

	// Optional. Filter by items whose name will appear before this value when sorted alphabetically.
	NameLessThan string

	// Optional. Filter by items whose name will appear after this value when sorted alphabetically.
	NameStartsWithOrGreater string

	// Optional. Specify additional fields of information to return in the output.
	Fields []ItemFields

	// Optional. Specify additional filters to apply.
	Filters []ItemFilter

	// Optional filter by items that are marked as favorite, or not. userId is required.
	IsFavorite *bool

	// Optional, include user data.
	EnableUserData *bool

	// Optional, the max number of images to return, per image type.
	ImageTypeLimit *int

	// Optional. The image types to include in the output.
	EnableImageTypes []ImageType

	// Optional. If specified results will be filtered to exclude those containing the specified PersonType. Allows multiple, comma-delimited.
	ExcludePersonTypes []string

	// Optional. If specified results will be filtered to include only those containing the specified PersonType. Allows multiple, comma-delimited.
	PersonTypes []string

	// Optional. Specify this to localize the search to a specific library. Omit to use the root.
	ParentId string

	// Optional. If specified, person results will be filtered on items related to said persons.
	AppearsInItemId string

	// User id.
	UserId string

	// Optional, include image information in output.
	EnableImages *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetPersonsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetPersonsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.StartIndex != nil {
		out.Append("startIndex", strconv.Itoa(*o.StartIndex))
	}
	if o.Limit != nil {
		out.Append("limit", strconv.Itoa(*o.Limit))
	}
	if o.SearchTerm != "" {
		out.Append("searchTerm", o.SearchTerm)
	}
	if o.NameStartsWith != "" {
		out.Append("nameStartsWith", o.NameStartsWith)
	}
	if o.NameLessThan != "" {
		out.Append("nameLessThan", o.NameLessThan)
	}
	if o.NameStartsWithOrGreater != "" {
		out.Append("nameStartsWithOrGreater", o.NameStartsWithOrGreater)
	}
	for _, v := range o.Fields {
		out.Append("fields", string(v))
	}
	for _, v := range o.Filters {
		out.Append("filters", string(v))
	}
	if o.IsFavorite != nil {
		out.Append("isFavorite", strconv.FormatBool(*o.IsFavorite))
	}
	if o.EnableUserData != nil {
		out.Append("enableUserData", strconv.FormatBool(*o.EnableUserData))
	}
	if o.ImageTypeLimit != nil {
		out.Append("imageTypeLimit", strconv.Itoa(*o.ImageTypeLimit))
	}
	for _, v := range o.EnableImageTypes {
		out.Append("enableImageTypes", string(v))
	}
	for _, v := range o.ExcludePersonTypes {
		out.Append("excludePersonTypes", v)
	}
	for _, v := range o.PersonTypes {
		out.Append("personTypes", v)
	}
	if o.ParentId != "" {
		out.Append("parentId", o.ParentId)
	}
	if o.AppearsInItemId != "" {
		out.Append("appearsInItemId", o.AppearsInItemId)
	}
	if o.UserId != "" {
		out.Append("userId", o.UserId)
	}
	if o.EnableImages != nil {
		out.Append("enableImages", strconv.FormatBool(*o.EnableImages))
	}
	return &out
}

// GetPersons calls GET /Persons. Gets all persons.
func (c Client) GetPersons(ctx context.Context, options GetPersonsOperationOptions) (result GetPersonsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/Persons",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model BaseItemDtoQueryResult
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}

// GetPersonsCompleteResult is every result GetPersonsComplete loaded.
type GetPersonsCompleteResult struct {
	LatestHttpResponse *http.Response
	Items              []BaseItemDto
}

// GetPersonsComplete calls GetPersons page by page from options.StartIndex until every
// result is loaded. options.Limit is the page size, client.DefaultPageSize when
// unset.
func (c Client) GetPersonsComplete(ctx context.Context, options GetPersonsOperationOptions) (result GetPersonsCompleteResult, err error) {
	limit := client.DefaultPageSize
	if options.Limit != nil && *options.Limit > 0 {
		limit = *options.Limit
	}
	options.Limit = &limit
	start := 0
	if options.StartIndex != nil {
		start = *options.StartIndex
	}
	for {
		var page GetPersonsOperationResponse
		page, err = c.GetPersons(ctx, options)
		result.LatestHttpResponse = page.HttpResponse
		if err != nil {
			err = fmt.Errorf("loading results: %w", err)
			return
		}
		if page.Model == nil || len(page.Model.Items) == 0 {
			return
		}
		result.Items = append(result.Items, page.Model.Items...)
		start += len(page.Model.Items)
		options.StartIndex = &start
		// a short page is the last; so is reaching the total, when the server
		// reports one (some Emby lists report 0 whatever they hold)
		if len(page.Model.Items) < limit || page.Model.TotalRecordCount > 0 && start >= page.Model.TotalRecordCount {
			return
		}
	}
}
