// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetPersonOperationResponse is the result of GetPerson.
type GetPersonOperationResponse struct {
	HttpResponse *http.Response
	Model        *BaseItemDto
}

// GetPersonOperationOptions holds the query and header parameters of GetPerson.
type GetPersonOperationOptions struct {
	// Optional. Filter by user id, and attach user data.
	UserId string
}

// ToHeaders returns the header parameters the options set.
func (o GetPersonOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetPersonOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.UserId != "" {
		out.Append("userId", o.UserId)
	}
	return &out
}

// GetPerson calls GET /Persons/{name}. Get person by name.
func (c Client) GetPerson(ctx context.Context, name string, options GetPersonOperationOptions) (result GetPersonOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          fmt.Sprintf("/Persons/%s", url.PathEscape(name)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model BaseItemDto
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
