// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// CreatePlaylistDto is the "CreatePlaylistDto" schema.
//
// Create new playlist dto.
type CreatePlaylistDto struct {
	// Gets or sets item ids to add to the playlist.
	Ids []string `json:"Ids,omitzero"`

	// Gets or sets a value indicating whether the playlist is public.
	IsPublic *bool `json:"IsPublic,omitempty"`

	// Gets or sets the media type.
	MediaType MediaType `json:"MediaType,omitempty"`

	// Gets or sets the name of the new playlist.
	Name string `json:"Name,omitempty"`

	// Gets or sets the user id.
	UserId string `json:"UserId,omitempty"`

	// Gets or sets the playlist users.
	Users []PlaylistUserPermissions `json:"Users,omitzero"`
}
