// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"net/http"
	"testing"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

func TestOperationInstallPackage(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 204, "", "")
	result, err := c.InstallPackage(t.Context(), "p/name", InstallPackageOperationOptions{
		AssemblyGuid:  "v-AssemblyGuid",
		Version:       "v-Version",
		RepositoryUrl: "v-RepositoryUrl",
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodPost, "/Packages/Installed/p%2Fname")
	expectQuery(t, r, "assemblyGuid", "v-AssemblyGuid")
	expectQuery(t, r, "version", "v-Version")
	expectQuery(t, r, "repositoryUrl", "v-RepositoryUrl")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 204 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.InstallPackage(t.Context(), "p/name", InstallPackageOperationOptions{
		AssemblyGuid:  "v-AssemblyGuid",
		Version:       "v-Version",
		RepositoryUrl: "v-RepositoryUrl",
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
