// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// UpdatePluginConfigurationOperationResponse is the result of UpdatePluginConfiguration.
type UpdatePluginConfigurationOperationResponse struct {
	HttpResponse *http.Response
}

// UpdatePluginConfiguration calls POST /Plugins/{pluginId}/Configuration. Updates plugin configuration.
func (c Client) UpdatePluginConfiguration(ctx context.Context, pluginId string) (result UpdatePluginConfigurationOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodPost,
		Path:       fmt.Sprintf("/Plugins/%s/Configuration", url.PathEscape(pluginId)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
