// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetRemoteImageProvidersOperationResponse is the result of GetRemoteImageProviders.
type GetRemoteImageProvidersOperationResponse struct {
	HttpResponse *http.Response
	Model        []ImageProviderInfo
}

// GetRemoteImageProviders calls GET /Items/{itemId}/RemoteImages/Providers. Gets available remote image providers for an item.
func (c Client) GetRemoteImageProviders(ctx context.Context, itemId string) (result GetRemoteImageProvidersOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod: http.MethodGet,
		Path:       fmt.Sprintf("/Items/%s/RemoteImages/Providers", url.PathEscape(itemId)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
