// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetTasksOperationResponse is the result of GetTasks.
type GetTasksOperationResponse struct {
	HttpResponse *http.Response
	Model        []TaskInfo
}

// GetTasksOperationOptions holds the query and header parameters of GetTasks.
type GetTasksOperationOptions struct {
	// Optional filter tasks that are hidden, or not.
	IsHidden *bool

	// Optional filter tasks that are enabled, or not.
	IsEnabled *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetTasksOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetTasksOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.IsHidden != nil {
		out.Append("isHidden", strconv.FormatBool(*o.IsHidden))
	}
	if o.IsEnabled != nil {
		out.Append("isEnabled", strconv.FormatBool(*o.IsEnabled))
	}
	return &out
}

// GetTasks calls GET /ScheduledTasks. Get tasks.
func (c Client) GetTasks(ctx context.Context, options GetTasksOperationOptions) (result GetTasksOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/ScheduledTasks",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
