// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// TaskInfo is the "TaskInfo" schema.
//
// Class TaskInfo.
type TaskInfo struct {
	// Gets or sets the category.
	Category string `json:"Category,omitempty"`

	// Gets or sets the progress.
	CurrentProgressPercentage float64 `json:"CurrentProgressPercentage,omitempty"`

	// Gets or sets the description.
	Description string `json:"Description,omitempty"`

	// Gets or sets the id.
	Id string `json:"Id,omitempty"`

	// Gets or sets a value indicating whether this instance is hidden.
	IsHidden *bool `json:"IsHidden,omitempty"`

	// Gets or sets the key.
	Key string `json:"Key,omitempty"`

	// Gets or sets the last execution result.
	LastExecutionResult *TaskResult `json:"LastExecutionResult,omitempty"`

	// Gets or sets the name.
	Name string `json:"Name,omitempty"`

	// Gets or sets the state of the task.
	State TaskState `json:"State,omitempty"`

	// Gets or sets the triggers.
	Triggers []TaskTriggerInfo `json:"Triggers,omitzero"`
}
