// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetSearchHintsOperationResponse is the result of GetSearchHints.
type GetSearchHintsOperationResponse struct {
	HttpResponse *http.Response
	Model        *SearchHintResult
}

// GetSearchHintsOperationOptions holds the query and header parameters of GetSearchHints.
type GetSearchHintsOperationOptions struct {
	// Optional. The record index to start at. All items with a lower index will be dropped from the results.
	StartIndex *int

	// Optional. The maximum number of records to return.
	Limit *int

	// Optional. Supply a user id to search within a user's library or omit to search all.
	UserId string

	// The search term to filter on.
	SearchTerm string

	// If specified, only results with the specified item types are returned. This allows multiple, comma delimited.
	IncludeItemTypes []BaseItemKind

	// If specified, results with these item types are filtered out. This allows multiple, comma delimited.
	ExcludeItemTypes []BaseItemKind

	// If specified, only results with the specified media types are returned. This allows multiple, comma delimited.
	MediaTypes []MediaType

	// If specified, only children of the parent are returned.
	ParentId string

	// Optional filter for movies.
	IsMovie *bool

	// Optional filter for series.
	IsSeries *bool

	// Optional filter for news.
	IsNews *bool

	// Optional filter for kids.
	IsKids *bool

	// Optional filter for sports.
	IsSports *bool

	// Optional filter whether to include people.
	IncludePeople *bool

	// Optional filter whether to include media.
	IncludeMedia *bool

	// Optional filter whether to include genres.
	IncludeGenres *bool

	// Optional filter whether to include studios.
	IncludeStudios *bool

	// Optional filter whether to include artists.
	IncludeArtists *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetSearchHintsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetSearchHintsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.StartIndex != nil {
		out.Append("startIndex", strconv.Itoa(*o.StartIndex))
	}
	if o.Limit != nil {
		out.Append("limit", strconv.Itoa(*o.Limit))
	}
	if o.UserId != "" {
		out.Append("userId", o.UserId)
	}
	if o.SearchTerm != "" {
		out.Append("searchTerm", o.SearchTerm)
	}
	for _, v := range o.IncludeItemTypes {
		out.Append("includeItemTypes", string(v))
	}
	for _, v := range o.ExcludeItemTypes {
		out.Append("excludeItemTypes", string(v))
	}
	for _, v := range o.MediaTypes {
		out.Append("mediaTypes", string(v))
	}
	if o.ParentId != "" {
		out.Append("parentId", o.ParentId)
	}
	if o.IsMovie != nil {
		out.Append("isMovie", strconv.FormatBool(*o.IsMovie))
	}
	if o.IsSeries != nil {
		out.Append("isSeries", strconv.FormatBool(*o.IsSeries))
	}
	if o.IsNews != nil {
		out.Append("isNews", strconv.FormatBool(*o.IsNews))
	}
	if o.IsKids != nil {
		out.Append("isKids", strconv.FormatBool(*o.IsKids))
	}
	if o.IsSports != nil {
		out.Append("isSports", strconv.FormatBool(*o.IsSports))
	}
	if o.IncludePeople != nil {
		out.Append("includePeople", strconv.FormatBool(*o.IncludePeople))
	}
	if o.IncludeMedia != nil {
		out.Append("includeMedia", strconv.FormatBool(*o.IncludeMedia))
	}
	if o.IncludeGenres != nil {
		out.Append("includeGenres", strconv.FormatBool(*o.IncludeGenres))
	}
	if o.IncludeStudios != nil {
		out.Append("includeStudios", strconv.FormatBool(*o.IncludeStudios))
	}
	if o.IncludeArtists != nil {
		out.Append("includeArtists", strconv.FormatBool(*o.IncludeArtists))
	}
	return &out
}

// GetSearchHints calls GET /Search/Hints. Gets the search hint result.
func (c Client) GetSearchHints(ctx context.Context, options GetSearchHintsOperationOptions) (result GetSearchHintsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/Search/Hints",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model SearchHintResult
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
