// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// ReportViewingOperationResponse is the result of ReportViewing.
type ReportViewingOperationResponse struct {
	HttpResponse *http.Response
}

// ReportViewingOperationOptions holds the query and header parameters of ReportViewing.
type ReportViewingOperationOptions struct {
	// The session id.
	SessionId string

	// The item id.
	ItemId string
}

// ToHeaders returns the header parameters the options set.
func (o ReportViewingOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o ReportViewingOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.SessionId != "" {
		out.Append("sessionId", o.SessionId)
	}
	if o.ItemId != "" {
		out.Append("itemId", o.ItemId)
	}
	return &out
}

// ReportViewing calls POST /Sessions/Viewing. Reports that a session is viewing an item.
func (c Client) ReportViewing(ctx context.Context, options ReportViewingOperationOptions) (result ReportViewingOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusNoContent,
		},
		HttpMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          "/Sessions/Viewing",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
