// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"net/http"
	"testing"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

func TestOperationPostCapabilities(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 204, "", "")
	result, err := c.PostCapabilities(t.Context(), PostCapabilitiesOperationOptions{
		Id:                           "v-Id",
		PlayableMediaTypes:           []MediaType{MediaTypeUnknown, MediaTypeBook},
		SupportedCommands:            []GeneralCommandType{GeneralCommandTypeMoveUp, GeneralCommandTypeSetPlaybackOrder},
		SupportsMediaControl:         new(true),
		SupportsPersistentIdentifier: new(true),
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodPost, "/Sessions/Capabilities")
	expectQuery(t, r, "id", "v-Id")
	expectQuery(t, r, "playableMediaTypes", "Unknown", "Book")
	expectQuery(t, r, "supportedCommands", "MoveUp", "SetPlaybackOrder")
	expectQuery(t, r, "supportsMediaControl", "true")
	expectQuery(t, r, "supportsPersistentIdentifier", "true")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 204 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.PostCapabilities(t.Context(), PostCapabilitiesOperationOptions{
		Id:                           "v-Id",
		PlayableMediaTypes:           []MediaType{MediaTypeUnknown, MediaTypeBook},
		SupportedCommands:            []GeneralCommandType{GeneralCommandTypeMoveUp, GeneralCommandTypeSetPlaybackOrder},
		SupportsMediaControl:         new(true),
		SupportsPersistentIdentifier: new(true),
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
