// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// PostCapabilitiesOperationResponse is the result of PostCapabilities.
type PostCapabilitiesOperationResponse struct {
	HttpResponse *http.Response
}

// PostCapabilitiesOperationOptions holds the query and header parameters of PostCapabilities.
type PostCapabilitiesOperationOptions struct {
	// The session id.
	Id string

	// A list of playable media types, comma delimited. Audio, Video, Book, Photo.
	PlayableMediaTypes []MediaType

	// A list of supported remote control commands, comma delimited.
	SupportedCommands []GeneralCommandType

	// Determines whether media can be played remotely..
	SupportsMediaControl *bool

	// Determines whether the device supports a unique identifier.
	SupportsPersistentIdentifier *bool
}

// ToHeaders returns the header parameters the options set.
func (o PostCapabilitiesOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PostCapabilitiesOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Id != "" {
		out.Append("id", o.Id)
	}
	for _, v := range o.PlayableMediaTypes {
		out.Append("playableMediaTypes", string(v))
	}
	for _, v := range o.SupportedCommands {
		out.Append("supportedCommands", string(v))
	}
	if o.SupportsMediaControl != nil {
		out.Append("supportsMediaControl", strconv.FormatBool(*o.SupportsMediaControl))
	}
	if o.SupportsPersistentIdentifier != nil {
		out.Append("supportsPersistentIdentifier", strconv.FormatBool(*o.SupportsPersistentIdentifier))
	}
	return &out
}

// PostCapabilities calls POST /Sessions/Capabilities. Updates capabilities for a device.
func (c Client) PostCapabilities(ctx context.Context, options PostCapabilitiesOperationOptions) (result PostCapabilitiesOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusNoContent,
		},
		HTTPMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          "/Sessions/Capabilities",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
