// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// MessageCommand is the "MessageCommand" schema.
//
// A command to display a message on a client.
type MessageCommand struct {
	// Gets or sets the message header.
	Header string `json:"Header,omitempty"`

	// Gets or sets the message text.
	Text string `json:"Text,omitempty"`

	// Gets or sets the timeout in milliseconds after which the message should be dismissed.
	TimeoutMs int64 `json:"TimeoutMs,omitempty"`
}
