// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// DisplayContentOperationResponse is the result of DisplayContent.
type DisplayContentOperationResponse struct {
	HttpResponse *http.Response
}

// DisplayContentOperationOptions holds the query and header parameters of DisplayContent.
type DisplayContentOperationOptions struct {
	// The type of item to browse to.
	ItemType BaseItemKind

	// The Id of the item.
	ItemId string

	// The name of the item.
	ItemName string
}

// ToHeaders returns the header parameters the options set.
func (o DisplayContentOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o DisplayContentOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.ItemType != "" {
		out.Append("itemType", string(o.ItemType))
	}
	if o.ItemId != "" {
		out.Append("itemId", o.ItemId)
	}
	if o.ItemName != "" {
		out.Append("itemName", o.ItemName)
	}
	return &out
}

// DisplayContent calls POST /Sessions/{sessionId}/Viewing. Instructs a session to browse to an item or view.
func (c Client) DisplayContent(ctx context.Context, sessionId string, options DisplayContentOperationOptions) (result DisplayContentOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusNoContent,
		},
		HTTPMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          fmt.Sprintf("/Sessions/%s/Viewing", url.PathEscape(sessionId)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
