// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// SendMessageCommandOperationResponse is the result of SendMessageCommand.
type SendMessageCommandOperationResponse struct {
	HttpResponse *http.Response
}

// SendMessageCommand calls POST /Sessions/{sessionId}/Message. Issues a command to a client to display a message to the user.
func (c Client) SendMessageCommand(ctx context.Context, sessionId string, input MessageCommand) (result SendMessageCommandOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusNoContent,
		},
		HttpMethod: http.MethodPost,
		Path:       fmt.Sprintf("/Sessions/%s/Message", url.PathEscape(sessionId)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
