// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// GeneralCommand is the "GeneralCommand" schema.
type GeneralCommand struct {
	Arguments         map[string]string `json:"Arguments,omitzero"`
	ControllingUserId string            `json:"ControllingUserId,omitempty"`

	// This exists simply to identify a set of known commands.
	Name GeneralCommandType `json:"Name,omitempty"`
}
