// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// ReportPlaybackStartOperationResponse is the result of ReportPlaybackStart.
type ReportPlaybackStartOperationResponse struct {
	HttpResponse *http.Response
}

// ReportPlaybackStart calls POST /Sessions/Playing. Reports playback has started within a session.
func (c Client) ReportPlaybackStart(ctx context.Context, input PlaybackStartInfo) (result ReportPlaybackStartOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusNoContent,
		},
		HttpMethod: http.MethodPost,
		Path:       "/Sessions/Playing",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
