// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetUpcomingEpisodesOperationResponse is the result of GetUpcomingEpisodes.
type GetUpcomingEpisodesOperationResponse struct {
	HttpResponse *http.Response
	Model        *BaseItemDtoQueryResult
}

// GetUpcomingEpisodesOperationOptions holds the query and header parameters of GetUpcomingEpisodes.
type GetUpcomingEpisodesOperationOptions struct {
	// The user id of the user to get the upcoming episodes for.
	UserId string

	// Optional. The record index to start at. All items with a lower index will be dropped from the results.
	StartIndex int

	// Optional. The maximum number of records to return.
	Limit int

	// Optional. Specify additional fields of information to return in the output.
	Fields []ItemFields

	// Optional. Specify this to localize the search to a specific item or folder. Omit to use the root.
	ParentId string

	// Optional. Include image information in output.
	EnableImages *bool

	// Optional. The max number of images to return, per image type.
	ImageTypeLimit int

	// Optional. The image types to include in the output.
	EnableImageTypes []ImageType

	// Optional. Include user data.
	EnableUserData *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetUpcomingEpisodesOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetUpcomingEpisodesOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.UserId != "" {
		out.Append("userId", o.UserId)
	}
	if o.StartIndex != 0 {
		out.Append("startIndex", strconv.Itoa(o.StartIndex))
	}
	if o.Limit != 0 {
		out.Append("limit", strconv.Itoa(o.Limit))
	}
	for _, v := range o.Fields {
		out.Append("fields", string(v))
	}
	if o.ParentId != "" {
		out.Append("parentId", o.ParentId)
	}
	if o.EnableImages != nil {
		out.Append("enableImages", strconv.FormatBool(*o.EnableImages))
	}
	if o.ImageTypeLimit != 0 {
		out.Append("imageTypeLimit", strconv.Itoa(o.ImageTypeLimit))
	}
	for _, v := range o.EnableImageTypes {
		out.Append("enableImageTypes", string(v))
	}
	if o.EnableUserData != nil {
		out.Append("enableUserData", strconv.FormatBool(*o.EnableUserData))
	}
	return &out
}

// GetUpcomingEpisodes calls GET /Shows/Upcoming. Gets a list of upcoming episodes.
func (c Client) GetUpcomingEpisodes(ctx context.Context, options GetUpcomingEpisodesOperationOptions) (result GetUpcomingEpisodesOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/Shows/Upcoming",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model BaseItemDtoQueryResult
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}

// GetUpcomingEpisodesCompleteResult is every result GetUpcomingEpisodesComplete loaded.
type GetUpcomingEpisodesCompleteResult struct {
	LatestHttpResponse *http.Response
	Items              []BaseItemDto
}

// GetUpcomingEpisodesComplete calls GetUpcomingEpisodes page by page from options.StartIndex until every
// result is loaded. options.Limit is the page size, client.DefaultPageSize when
// unset.
func (c Client) GetUpcomingEpisodesComplete(ctx context.Context, options GetUpcomingEpisodesOperationOptions) (result GetUpcomingEpisodesCompleteResult, err error) {
	if options.Limit <= 0 {
		options.Limit = client.DefaultPageSize
	}
	for {
		var page GetUpcomingEpisodesOperationResponse
		page, err = c.GetUpcomingEpisodes(ctx, options)
		result.LatestHttpResponse = page.HttpResponse
		if err != nil {
			err = fmt.Errorf("loading results: %w", err)
			return
		}
		if page.Model == nil || len(page.Model.Items) == 0 {
			return
		}
		result.Items = append(result.Items, page.Model.Items...)
		options.StartIndex += len(page.Model.Items)
		// a short page is the last; so is reaching the total, when the server
		// reports one (some Emby lists report 0 whatever they hold)
		if len(page.Model.Items) < options.Limit || page.Model.TotalRecordCount > 0 && options.StartIndex >= page.Model.TotalRecordCount {
			return
		}
	}
}
