// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetRemoteSubtitlesOperationResponse is the result of GetRemoteSubtitles.
//
// The operation answers text/*, left unread in HttpResponse.Body, which
// the caller must close.
type GetRemoteSubtitlesOperationResponse struct {
	HttpResponse *http.Response
}

// GetRemoteSubtitles calls GET /Providers/Subtitles/Subtitles/{subtitleId}. Gets the remote subtitles.
func (c Client) GetRemoteSubtitles(ctx context.Context, subtitleId string) (result GetRemoteSubtitlesOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:     http.MethodGet,
		Path:           fmt.Sprintf("/Providers/Subtitles/Subtitles/%s", url.PathEscape(subtitleId)),
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
