// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// IgnoreWaitRequestDto is the "IgnoreWaitRequestDto" schema.
//
// Class IgnoreWaitRequestDto.
type IgnoreWaitRequestDto struct {
	// Gets or sets a value indicating whether the client should be ignored.
	IgnoreWait *bool `json:"IgnoreWait,omitempty"`
}
