// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// SyncPlayLeaveGroupOperationResponse is the result of SyncPlayLeaveGroup.
type SyncPlayLeaveGroupOperationResponse struct {
	HttpResponse *http.Response
}

// SyncPlayLeaveGroup calls POST /SyncPlay/Leave. Leave the joined SyncPlay group.
func (c Client) SyncPlayLeaveGroup(ctx context.Context) (result SyncPlayLeaveGroupOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusNoContent,
		},
		HttpMethod: http.MethodPost,
		Path:       "/SyncPlay/Leave",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
