// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// PingRequestDto is the "PingRequestDto" schema.
//
// Class PingRequestDto.
type PingRequestDto struct {
	// Gets or sets the ping time.
	Ping int64 `json:"Ping,omitempty"`
}
