// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// SyncPlayRemoveFromPlaylistOperationResponse is the result of SyncPlayRemoveFromPlaylist.
type SyncPlayRemoveFromPlaylistOperationResponse struct {
	HttpResponse *http.Response
}

// SyncPlayRemoveFromPlaylist calls POST /SyncPlay/RemoveFromPlaylist. Request to remove items from the playlist in SyncPlay group.
func (c Client) SyncPlayRemoveFromPlaylist(ctx context.Context, input RemoveFromPlaylistRequestDto) (result SyncPlayRemoveFromPlaylistOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusNoContent,
		},
		HTTPMethod: http.MethodPost,
		Path:       "/SyncPlay/RemoveFromPlaylist",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
