// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// SyncPlaySetShuffleModeOperationResponse is the result of SyncPlaySetShuffleMode.
type SyncPlaySetShuffleModeOperationResponse struct {
	HttpResponse *http.Response
}

// SyncPlaySetShuffleMode calls POST /SyncPlay/SetShuffleMode. Request to set shuffle mode in SyncPlay group.
func (c Client) SyncPlaySetShuffleMode(ctx context.Context, input SetShuffleModeRequestDto) (result SyncPlaySetShuffleModeOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusNoContent,
		},
		HttpMethod: http.MethodPost,
		Path:       "/SyncPlay/SetShuffleMode",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
