// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// SyncPlayNextItemOperationResponse is the result of SyncPlayNextItem.
type SyncPlayNextItemOperationResponse struct {
	HttpResponse *http.Response
}

// SyncPlayNextItem calls POST /SyncPlay/NextItem. Request next item in SyncPlay group.
func (c Client) SyncPlayNextItem(ctx context.Context, input NextItemRequestDto) (result SyncPlayNextItemOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusNoContent,
		},
		HttpMethod: http.MethodPost,
		Path:       "/SyncPlay/NextItem",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
