// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// GroupQueueMode is the "GroupQueueMode" enum.
//
// Enum GroupQueueMode.
type GroupQueueMode string

// Values of GroupQueueMode.
const (
	GroupQueueModeQueue     GroupQueueMode = "Queue"
	GroupQueueModeQueueNext GroupQueueMode = "QueueNext"
)

// PossibleValuesForGroupQueueMode returns every value of GroupQueueMode.
func PossibleValuesForGroupQueueMode() []string {
	return []string{
		string(GroupQueueModeQueue),
		string(GroupQueueModeQueueNext),
	}
}

// GroupRepeatMode is the "GroupRepeatMode" enum.
//
// Enum GroupRepeatMode.
type GroupRepeatMode string

// Values of GroupRepeatMode.
const (
	GroupRepeatModeRepeatOne  GroupRepeatMode = "RepeatOne"
	GroupRepeatModeRepeatAll  GroupRepeatMode = "RepeatAll"
	GroupRepeatModeRepeatNone GroupRepeatMode = "RepeatNone"
)

// PossibleValuesForGroupRepeatMode returns every value of GroupRepeatMode.
func PossibleValuesForGroupRepeatMode() []string {
	return []string{
		string(GroupRepeatModeRepeatOne),
		string(GroupRepeatModeRepeatAll),
		string(GroupRepeatModeRepeatNone),
	}
}

// GroupShuffleMode is the "GroupShuffleMode" enum.
//
// Enum GroupShuffleMode.
type GroupShuffleMode string

// Values of GroupShuffleMode.
const (
	GroupShuffleModeSorted  GroupShuffleMode = "Sorted"
	GroupShuffleModeShuffle GroupShuffleMode = "Shuffle"
)

// PossibleValuesForGroupShuffleMode returns every value of GroupShuffleMode.
func PossibleValuesForGroupShuffleMode() []string {
	return []string{
		string(GroupShuffleModeSorted),
		string(GroupShuffleModeShuffle),
	}
}

// GroupStateType is the "GroupStateType" enum.
//
// Enum GroupState.
type GroupStateType string

// Values of GroupStateType.
const (
	GroupStateTypeIdle    GroupStateType = "Idle"
	GroupStateTypeWaiting GroupStateType = "Waiting"
	GroupStateTypePaused  GroupStateType = "Paused"
	GroupStateTypePlaying GroupStateType = "Playing"
)

// PossibleValuesForGroupStateType returns every value of GroupStateType.
func PossibleValuesForGroupStateType() []string {
	return []string{
		string(GroupStateTypeIdle),
		string(GroupStateTypeWaiting),
		string(GroupStateTypePaused),
		string(GroupStateTypePlaying),
	}
}
