// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// MetadataOptions is the "MetadataOptions" schema.
//
// Class MetadataOptions.
type MetadataOptions struct {
	DisabledImageFetchers    []string `json:"DisabledImageFetchers,omitzero"`
	DisabledMetadataFetchers []string `json:"DisabledMetadataFetchers,omitzero"`
	DisabledMetadataSavers   []string `json:"DisabledMetadataSavers,omitzero"`
	ImageFetcherOrder        []string `json:"ImageFetcherOrder,omitzero"`
	ItemType                 string   `json:"ItemType,omitempty"`
	LocalMetadataReaderOrder []string `json:"LocalMetadataReaderOrder,omitzero"`
	MetadataFetcherOrder     []string `json:"MetadataFetcherOrder,omitzero"`
}
