// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"net/http"
	"slices"
	"testing"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

func TestOperationGetLogEntries(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "application/json", "{}")
	result, err := c.GetLogEntries(t.Context(), GetLogEntriesOperationOptions{
		StartIndex:    new(7),
		Limit:         new(7),
		MinDate:       "v-MinDate",
		MaxDate:       "v-MaxDate",
		HasUserId:     new(true),
		Name:          "v-Name",
		Overview:      "v-Overview",
		ShortOverview: "v-ShortOverview",
		Type:          "v-Type",
		ItemId:        "v-ItemId",
		Username:      "v-Username",
		Severity:      LogLevelTrace,
		SortBy:        []ActivityLogSortBy{ActivityLogSortByName, ActivityLogSortByLogSeverity},
		SortOrder:     []SortOrder{SortOrderAscending, SortOrderDescending},
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/System/ActivityLog/Entries")
	expectQuery(t, r, "startIndex", "7")
	expectQuery(t, r, "limit", "7")
	expectQuery(t, r, "minDate", "v-MinDate")
	expectQuery(t, r, "maxDate", "v-MaxDate")
	expectQuery(t, r, "hasUserId", "true")
	expectQuery(t, r, "name", "v-Name")
	expectQuery(t, r, "overview", "v-Overview")
	expectQuery(t, r, "shortOverview", "v-ShortOverview")
	expectQuery(t, r, "type", "v-Type")
	expectQuery(t, r, "itemId", "v-ItemId")
	expectQuery(t, r, "username", "v-Username")
	expectQuery(t, r, "severity", "Trace")
	expectQuery(t, r, "sortBy", "Name", "LogSeverity")
	expectQuery(t, r, "sortOrder", "Ascending", "Descending")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	if result.Model == nil {
		t.Error("the model was not decoded")
	}

	// an answer that does not decode is an error, with the response
	c, _ = newOperationServer(t, 200, "application/json", "<html>")
	result, err = c.GetLogEntries(t.Context(), GetLogEntriesOperationOptions{
		StartIndex:    new(7),
		Limit:         new(7),
		MinDate:       "v-MinDate",
		MaxDate:       "v-MaxDate",
		HasUserId:     new(true),
		Name:          "v-Name",
		Overview:      "v-Overview",
		ShortOverview: "v-ShortOverview",
		Type:          "v-Type",
		ItemId:        "v-ItemId",
		Username:      "v-Username",
		Severity:      LogLevelTrace,
		SortBy:        []ActivityLogSortBy{ActivityLogSortByName, ActivityLogSortByLogSeverity},
		SortOrder:     []SortOrder{SortOrderAscending, SortOrderDescending},
	})
	if err == nil || client.StatusCode(err) != 0 || result.HttpResponse == nil {
		t.Errorf("an answer that does not decode = %v", err)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.GetLogEntries(t.Context(), GetLogEntriesOperationOptions{
		StartIndex:    new(7),
		Limit:         new(7),
		MinDate:       "v-MinDate",
		MaxDate:       "v-MaxDate",
		HasUserId:     new(true),
		Name:          "v-Name",
		Overview:      "v-Overview",
		ShortOverview: "v-ShortOverview",
		Type:          "v-Type",
		ItemId:        "v-ItemId",
		Username:      "v-Username",
		Severity:      LogLevelTrace,
		SortBy:        []ActivityLogSortBy{ActivityLogSortByName, ActivityLogSortByLogSeverity},
		SortOrder:     []SortOrder{SortOrderAscending, SortOrderDescending},
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}

func TestOperationGetLogEntriesComplete(t *testing.T) {
	t.Parallel()

	// the three ways a walk ends: the total is reached, an empty page when the
	// server reports no total, and a page shorter than the limit
	for _, tc := range []struct {
		name         string
		total, pages int
		options      GetLogEntriesOperationOptions
		items        int
		starts       []string
	}{
		{"total reached", 2, 9, GetLogEntriesOperationOptions{Limit: new(1)}, 2, []string{"", "1"}},
		{"empty page", 0, 2, GetLogEntriesOperationOptions{Limit: new(1)}, 2, []string{"", "1", "2"}},
		{"short page", 0, 9, GetLogEntriesOperationOptions{Limit: new(2)}, 1, []string{""}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			c, starts := pagedServer(t, "startIndex", "{}", tc.total, tc.pages)
			result, err := c.GetLogEntriesComplete(t.Context(), tc.options)
			if err != nil {
				t.Fatal(err)
			}
			if len(result.Items) != tc.items || !slices.Equal(*starts, tc.starts) || result.LatestHttpResponse == nil {
				t.Errorf("Complete = %d items over pages starting %q, want %d over %q", len(result.Items), *starts, tc.items, tc.starts)
			}
		})
	}
}
