// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// UtcTimeResponse is the "UtcTimeResponse" schema.
//
// Class UtcTimeResponse.
type UtcTimeResponse struct {
	// Gets the UTC time when request has been received.
	RequestReceptionTime string `json:"RequestReceptionTime,omitempty"`

	// Gets the UTC time when response has been sent.
	ResponseTransmissionTime string `json:"ResponseTransmissionTime,omitempty"`
}
