// Code generated by internal/pandorest; DO NOT EDIT.

package jf

// TrickplayOptions is the "TrickplayOptions" schema.
//
// Class TrickplayOptions.
type TrickplayOptions struct {
	// Gets or sets a value indicating whether or not to use HW acceleration.
	EnableHwAcceleration *bool `json:"EnableHwAcceleration,omitempty"`

	// Gets or sets a value indicating whether or not to use HW accelerated MJPEG encoding.
	EnableHwEncoding *bool `json:"EnableHwEncoding,omitempty"`

	// Gets or sets a value indicating whether to only extract key frames.
	// Significantly faster, but is not compatible with all decoders and/or video files.
	EnableKeyFrameOnlyExtraction *bool `json:"EnableKeyFrameOnlyExtraction,omitempty"`

	// Gets or sets the interval, in ms, between each new trickplay image.
	Interval int `json:"Interval,omitempty"`

	// Gets or sets the jpeg quality to use for image tiles.
	JpegQuality int `json:"JpegQuality,omitempty"`

	// Gets or sets the process priority for the ffmpeg process.
	ProcessPriority ProcessPriorityClass `json:"ProcessPriority,omitempty"`

	// Gets or sets the number of threads to be used by ffmpeg.
	ProcessThreads int `json:"ProcessThreads,omitempty"`

	// Gets or sets the ffmpeg output quality level.
	Qscale int `json:"Qscale,omitempty"`

	// Gets or sets the behavior used by trickplay provider on library scan/update.
	ScanBehavior TrickplayScanBehavior `json:"ScanBehavior,omitempty"`

	// Gets or sets number of tile images to allow in Y dimension.
	TileHeight int `json:"TileHeight,omitempty"`

	// Gets or sets number of tile images to allow in X dimension.
	TileWidth int `json:"TileWidth,omitempty"`

	// Gets or sets the target width resolutions, in px, to generates preview images for.
	WidthResolutions []int `json:"WidthResolutions,omitzero"`
}
