// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetTrickplayHlsPlaylistOperationResponse is the result of GetTrickplayHlsPlaylist.
//
// The operation answers application/x-mpegURL, left unread in HttpResponse.Body, which
// the caller must close.
type GetTrickplayHlsPlaylistOperationResponse struct {
	HttpResponse *http.Response
}

// GetTrickplayHlsPlaylistOperationOptions holds the query and header parameters of GetTrickplayHlsPlaylist.
type GetTrickplayHlsPlaylistOperationOptions struct {
	// The media version id, if using an alternate version.
	MediaSourceId string
}

// ToHeaders returns the header parameters the options set.
func (o GetTrickplayHlsPlaylistOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetTrickplayHlsPlaylistOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.MediaSourceId != "" {
		out.Append("mediaSourceId", o.MediaSourceId)
	}
	return &out
}

// GetTrickplayHlsPlaylist calls GET /Videos/{itemId}/Trickplay/{width}/tiles.m3u8. Gets an image tiles playlist for trickplay.
func (c Client) GetTrickplayHlsPlaylist(ctx context.Context, itemId string, width int, options GetTrickplayHlsPlaylistOperationOptions) (result GetTrickplayHlsPlaylistOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HTTPMethod:     http.MethodGet,
		OptionsObject:  options,
		Path:           fmt.Sprintf("/Videos/%s/Trickplay/%d/tiles.m3u8", url.PathEscape(itemId), width),
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
