// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"io"
	"net/http"
	"testing"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

func TestOperationGetTrickplayHlsPlaylist(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "application/x-mpegURL", "file bytes")
	result, err := c.GetTrickplayHlsPlaylist(t.Context(), "p/itemId", 7, GetTrickplayHlsPlaylistOperationOptions{
		MediaSourceId: "v-MediaSourceId",
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/Videos/p%2FitemId/Trickplay/7/tiles.m3u8")
	expectQuery(t, r, "mediaSourceId", "v-MediaSourceId")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	streamed, _ := io.ReadAll(result.HttpResponse.Body)
	_ = result.HttpResponse.Body.Close()
	if string(streamed) != "file bytes" {
		t.Errorf("streamed body = %q", streamed)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.GetTrickplayHlsPlaylist(t.Context(), "p/itemId", 7, GetTrickplayHlsPlaylistOperationOptions{
		MediaSourceId: "v-MediaSourceId",
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
