// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// UnmarkFavoriteItemOperationResponse is the result of UnmarkFavoriteItem.
type UnmarkFavoriteItemOperationResponse struct {
	HttpResponse *http.Response
	Model        *UserItemDataDto
}

// UnmarkFavoriteItemOperationOptions holds the query and header parameters of UnmarkFavoriteItem.
type UnmarkFavoriteItemOperationOptions struct {
	// User id.
	UserId string
}

// ToHeaders returns the header parameters the options set.
func (o UnmarkFavoriteItemOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o UnmarkFavoriteItemOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.UserId != "" {
		out.Append("userId", o.UserId)
	}
	return &out
}

// UnmarkFavoriteItem calls DELETE /UserFavoriteItems/{itemId}. Unmarks item as a favorite.
func (c Client) UnmarkFavoriteItem(ctx context.Context, itemId string, options UnmarkFavoriteItemOperationOptions) (result UnmarkFavoriteItemOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodDelete,
		OptionsObject: options,
		Path:          fmt.Sprintf("/UserFavoriteItems/%s", url.PathEscape(itemId)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model UserItemDataDto
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
