// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"net/http"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// UpdateUserPasswordOperationResponse is the result of UpdateUserPassword.
type UpdateUserPasswordOperationResponse struct {
	HttpResponse *http.Response
}

// UpdateUserPasswordOperationOptions holds the query and header parameters of UpdateUserPassword.
type UpdateUserPasswordOperationOptions struct {
	// The user id.
	UserId string
}

// ToHeaders returns the header parameters the options set.
func (o UpdateUserPasswordOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o UpdateUserPasswordOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.UserId != "" {
		out.Append("userId", o.UserId)
	}
	return &out
}

// UpdateUserPassword calls POST /Users/Password. Updates a user's password.
func (c Client) UpdateUserPassword(ctx context.Context, input UpdateUserPassword, options UpdateUserPasswordOperationOptions) (result UpdateUserPasswordOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusNoContent,
		},
		HTTPMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          "/Users/Password",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
