// Code generated by internal/pandorest; DO NOT EDIT.

package jf

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/embyfin-mcp/lib/client"
)

// GetYearsOperationResponse is the result of GetYears.
type GetYearsOperationResponse struct {
	HttpResponse *http.Response
	Model        *BaseItemDtoQueryResult
}

// GetYearsOperationOptions holds the query and header parameters of GetYears.
type GetYearsOperationOptions struct {
	// Skips over a given number of items within the results. Use for paging.
	StartIndex int

	// Optional. The maximum number of records to return.
	Limit int

	// Sort Order - Ascending,Descending.
	SortOrder []SortOrder

	// Specify this to localize the search to a specific item or folder. Omit to use the root.
	ParentId string

	// Optional. Specify additional fields of information to return in the output.
	Fields []ItemFields

	// Optional. If specified, results will be excluded based on item type. This allows multiple, comma delimited.
	ExcludeItemTypes []BaseItemKind

	// Optional. If specified, results will be included based on item type. This allows multiple, comma delimited.
	IncludeItemTypes []BaseItemKind

	// Optional. Filter by MediaType. Allows multiple, comma delimited.
	MediaTypes []MediaType

	// Optional. Specify one or more sort orders, comma delimited. Options: Album, AlbumArtist, Artist, Budget, CommunityRating, CriticRating, DateCreated, DatePlayed, PlayCount, PremiereDate, ProductionYear, SortName, Random, Revenue, Runtime.
	SortBy []ItemSortBy

	// Optional. Include user data.
	EnableUserData *bool

	// Optional. The max number of images to return, per image type.
	ImageTypeLimit int

	// Optional. The image types to include in the output.
	EnableImageTypes []ImageType

	// User Id.
	UserId string

	// Search recursively.
	Recursive *bool

	// Optional. Include image information in output.
	EnableImages *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetYearsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetYearsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.StartIndex != 0 {
		out.Append("startIndex", strconv.Itoa(o.StartIndex))
	}
	if o.Limit != 0 {
		out.Append("limit", strconv.Itoa(o.Limit))
	}
	for _, v := range o.SortOrder {
		out.Append("sortOrder", string(v))
	}
	if o.ParentId != "" {
		out.Append("parentId", o.ParentId)
	}
	for _, v := range o.Fields {
		out.Append("fields", string(v))
	}
	for _, v := range o.ExcludeItemTypes {
		out.Append("excludeItemTypes", string(v))
	}
	for _, v := range o.IncludeItemTypes {
		out.Append("includeItemTypes", string(v))
	}
	for _, v := range o.MediaTypes {
		out.Append("mediaTypes", string(v))
	}
	for _, v := range o.SortBy {
		out.Append("sortBy", string(v))
	}
	if o.EnableUserData != nil {
		out.Append("enableUserData", strconv.FormatBool(*o.EnableUserData))
	}
	if o.ImageTypeLimit != 0 {
		out.Append("imageTypeLimit", strconv.Itoa(o.ImageTypeLimit))
	}
	for _, v := range o.EnableImageTypes {
		out.Append("enableImageTypes", string(v))
	}
	if o.UserId != "" {
		out.Append("userId", o.UserId)
	}
	if o.Recursive != nil {
		out.Append("recursive", strconv.FormatBool(*o.Recursive))
	}
	if o.EnableImages != nil {
		out.Append("enableImages", strconv.FormatBool(*o.EnableImages))
	}
	return &out
}

// GetYears calls GET /Years. Get years.
func (c Client) GetYears(ctx context.Context, options GetYearsOperationOptions) (result GetYearsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/Years",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model BaseItemDtoQueryResult
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}

// GetYearsCompleteResult is every result GetYearsComplete loaded.
type GetYearsCompleteResult struct {
	LatestHttpResponse *http.Response
	Items              []BaseItemDto
}

// GetYearsComplete calls GetYears page by page from options.StartIndex until every
// result is loaded. options.Limit is the page size, client.DefaultPageSize when
// unset.
func (c Client) GetYearsComplete(ctx context.Context, options GetYearsOperationOptions) (result GetYearsCompleteResult, err error) {
	if options.Limit <= 0 {
		options.Limit = client.DefaultPageSize
	}
	for {
		var page GetYearsOperationResponse
		page, err = c.GetYears(ctx, options)
		result.LatestHttpResponse = page.HttpResponse
		if err != nil {
			err = fmt.Errorf("loading results: %w", err)
			return
		}
		if page.Model == nil || len(page.Model.Items) == 0 {
			return
		}
		result.Items = append(result.Items, page.Model.Items...)
		options.StartIndex += len(page.Model.Items)
		// a short page is the last; so is reaching the total, when the server
		// reports one (some Emby lists report 0 whatever they hold)
		if len(page.Model.Items) < options.Limit || page.Model.TotalRecordCount > 0 && options.StartIndex >= page.Model.TotalRecordCount {
			return
		}
	}
}
